graphql/graphiql

src/codemirror/lint/jsonLint.js

Self descriptive. It'll stay in the loop hoping to find `"`(34), only to fail.
Resolves #12.

fix an infinite loop caused by unclosed quotation tag

---

src/components/GraphiQL.js

I needed this on my electron wrapper around GraphiQL...but I think it could be useful to others if they're embedding GraphiQL in an application that uses localStorage already.

Add the ability to set a prefix for data stored in localStorage

---

package.json

Thus minimizing the dependency. Ran tests + built successfully from a fresh repo + example works.

remove babel-runtime dependency

---

src/components/GraphiQL.js

`result` seems to be switched out to `response` - caught some missing out I think.

modified result to response to properly update this.state.response

---

src/components/GraphiQL.js

Simply return the result query from filling leaves of the query, and either use that or the query from this.state to fetch results.

fixed to execute a version of query with auto-completed leafs

---

package.json

If you try to use latest React 0.14.2 with graphiql, it won't work. This PR fix it

Allow React 0.14.x in peer dependencies

---

example/package.json
example/server.js
package.json
src/components/DocExplorer.js

Adds `subscription` operation support that landed in graphql-js 0.4.8.
Do not merge until https://github.com/graphql/codemirror-graphql/pull/2 is merged and dependency is updated here.

Add `subscription` operation support

---

src/components/DocExplorer.js

With a schema without subscription/mutation types, this shows a console error. Check if the methods exist before executing them.

check if subscription/mutation types exist before trying to access them

---

css/app.css
css/loading.css
src/components/DocExplorer.js
src/components/GraphiQL.js

A CSS-driven loading spinner when running editor queries and fetching the schema, in case they take a while. Shown in a result window and documentation explorer (since it needs a schema to be rendered).

Loading spinner when running editor queries and fetching the schema

---

src/components/DocExplorer.js

Fixes: #69 
The `DocExplorer` component was incorrectly showing the type description text instead of the individual enum value description text for each enum value. (`type.description` was being passed instead of the correct `value.description`).

Fixes #69: Show correct description text for each enum value.

---

css/doc-explorer.css
src/components/DocExplorer.js

Search functionality in Documentation Explorer.
It's pretty basic with searching/getting results/clicking links - I'll incrementally add in more details in upcoming PRs.
EDIT: added no-search-result case and minimum character length

Search in Doc Explorer

---

src/components/QueryEditor.js

addresses #24. Added `Alt-Space` and `Shift-Space` as alternatives.

Enable extra key mappings for typeahead

---

css/app.css
src/components/GraphiQL.js
src/components/PrettifyButton.js

addresses #48
it adds a **`{}`** prettify button. this is implemented using `graphql` parse & print function: `print(parse(this.state.query))`
(pretty useful when you paste an obfuscated relay query and want to debug it)
on hover:
after clicking:

Fixes #48: add a prettify query button

---

resources/build.sh

This should prevent struggles like this one: http://stackoverflow.com/questions/35096635/error-in-building-graphiql/35470669#35470669

Warn when trying to build before having run `npm install`

---

src/components/GraphiQL.js

Rather than having it as a substitute of Toolbar, have it independent and always available regardless of a custom toolbar.

have prettify button independent to GraphiQLToolbar

---

css/app.css

Everybody seems to be using an OS with invisible scrollbars, but at least on Linux, `overflow: scroll` makes the scrollbars always visible.

Display the toolbar's scrollbar only when needed

---

README.md
src/components/ExecuteButton.js
src/components/GraphiQL.js

This supports the fetcher returning an Observable, which will let us begin to experiment with support for GraphQL subscriptions and observable "live queries".
To test this, I added the crappiest possible Observable implementation to example/index.html:
```js
if (graphQLParams.query.indexOf('subscription') === 0) {
// If the operation smells like a subscription (#clowntown) then return an "Observable".
return {
// The subscribe function accepts an "Observer" which has next, error, and complete functions.
subscribe(observer) {
try {
var i = 0;
var interval = setInterval(() => {
if (i > 10) {
clearInterval(interval);
observer.complete && observer.complete();
} else {
observer.next && observer.next({ data: i++ });
}
}, 500);
} catch (e) {
clearInterval(interval);
observer.error && …
```

[RFC] Support a fetcher that returns Observable

---

src/components/GraphiQL.js

Currently we write to persistable state on each change to any persistable state including the current query and variables as well as some the resizable elements of the UI. This suggests replacing that with only saving persistable state when the component is about to unmount.
This fixes a problem where opening multiple instances of GraphiQL at the same time can result in one query appearing across all views. Now, only the last window closed will save the query. This also fixes a frustration where accidentally closing a tab and then editing another instance of GraphiQL renders the accidentally closed tab harder to recover.
This also fixes a performance issue where setting into storage can be slightly expensive and we were performing this on every keystroke.
The primary drawback is the …

[RFC] Only store persistable state on unmount

---

src/components/DocExplorer.js

Step 1:
Take out search method to particular method `SearchDoc._isMatch` with old code.
Step 2:
Change `indexOf` to case insensetive `regexp`. Do not escape user pattern for regexp, for allowing to use regexp in search query string.

Case insensitive search + allow regexp in query

---

README.md
example/index.html
src/components/GraphiQL.js
src/utility/getQueryFacts.js
src/utility/getSelectedOperationName.js

This provides hooks for explicitly providing `operationName` to GraphiQL at init time as well as providing a function to be called whenever the `operationName` changes.
This also updates the example to illustrate how to use these new props.
Fixes #108

Provide props for operationName and onEditOperationName, similar to query and variables

---

package.json
src/components/GraphiQL.js
src/components/__tests__/GraphiQL-test.js

Hi, this happens when `queryFacts` is undefined, which occurs when either the schema or an initial query doesn't exist - the schema being absent is quite common by default

fix undefined exception

---

src/components/GraphiQL.js

During receiving new `props`, update query facts with a next available query string. This will update `operationName` appropriately.

Update query facts with a next available query

---

src/components/DocExplorer.js

Fixes #121.
Pass the schema down from DocExplorer into TypeDoc so that it can be used to resolve possible types for interfaces and unions.

Fix interfaces and unions in DocumentationExplorer

---

example/package.json
package.json

addresses #123. d5f027a already supports React#0.15.0 - this just upgrades the packages and ensures there aren't problems.

upgrade packages: React to 0.15.1 and express-graphql to 0.5.1

---

src/components/GraphiQL.js
src/components/__tests__/GraphiQL-test.js

Hi there, is GraphiQL correctly falling back to `props.defaultQuery`? 
I find that if I open http://graphql-swapi.parseapp.com/ with an incognito window, the query window is blank. But, I think it should include `defaultQuery` defined at the bottom of `GraphiQL.js`. 
I think the problem is that `this._storageGet("query")` returns `null` (https://developer.mozilla.org/en-US/docs/Web/API/Storage/getItem) if it is unset -- but the we treat that as useful value since it's `!== undefined`.
So, can we test it against `null` instead? 
I tried to write tests for this but I couldn't quite get it: `node.textContent` didn't contain the query string and `component.state` had `query: null`, so I think it may not have been initialized. Should I add a test for this? Happy to do it, but I'll need a …

fix(GraphiQL) fallback to defaultQuery if there's no stored query

---

src/components/DocExplorer.js

I'm getting the following warning when loading GraphiQL.
> warning.js:44 Warning: `value` prop on `input` should not be null. Consider using the empty string to clear the component or `undefined` for uncontrolled components.
I believe the attached PR fixes the issue.

Default state for search box should not be null

---

src/components/GraphiQL.js

Right now, if the onToggleDocs prop is not provided, GraphiQL errors. Let's check for the presence of that function before trying to call it.

Fix onToggleDocs behavior.

---

example/index.html

The GraphQL server happens to be mounted at `graphql` in this case (https://github.com/graphql/graphiql/blob/master/example/server.js#L28), but we shouldn't assume that.
This fix should allow the GraphQL server to be mounted anywhere.
The reason this is important is that we use this template in [GraphQL Elixir](https://github.com/graphql-elixir/graphql) (other implementations would likely do something similar). Our template can be found here https://github.com/graphql-elixir/plug_graphql/blob/master/templates/graphiql.eex
We found some issues when we took this template verbatim before line 111.

Don't assume server is mounted at `/graphql`

---

src/components/ExecuteButton.js

Since the `<li>`'s `onMouseUp` handler will set `optionsOpen` to false, we don't need to do that here if we click on the `<li>`. Fixes #150.

Fixes #150.

---

package.json

Hey @leebyron, @spikebrehm and I were able to get GraphiQL successfully running on React 14.8 at Airbnb, but NPM install complains because it it has a peer dependency for React 15. Can you confirm that GraphiQL works properly with React 14?

[Dependencies] add support for React >=0.14.8

---

src/components/GraphiQL.js
src/components/QueryEditor.js
src/components/VariableEditor.js

An alternative solution for a issue discussed in #152. The original solution can be found in #154.

Use CoreMirror's key maps instead of global event handler to run query at a cursor

---

src/components/DocExplorer.js

The GraphQL specification [states clearly](https://facebook.github.io/graphql/#sec-Deprecation):
> Tools built using GraphQL introspection should respect deprecation by
> discouraging deprecated use through information hiding or
> developer‐facing warnings.
Currently, however, GraphiQL doesn't give any indication of whether or
not a field or enum value is deprecated. This patch rectifies this by
adding some red text next to field names and enum value names that just
says "(DEPRECATED)". If a deprecation reason is given for a field or
enum value, that is rendered (also in red) underneath the field or
value's description.
Closes #34.
Signed-off-by: David Celis <davidcelis@github.com>

Show deprecation information in the Docs sidebar

---

README.md

The relative link was ending up at `https://github.com/graphql/graphiql/blob/master/graphql/graphiql/releases`

fix releases link in README

---

src/components/DocExplorer.js

Relates to:
https://github.com/graphql/graphiql/pull/157#issuecomment-245028499
Correcting usages of `field.isDeprecated` in docs to look at `field.deprecationReason` instead restores this functionality.
--
**CC:** @davidcelis @globegitter

resolving broken deprecation message in docs

---

src/components/GraphiQL.js

Pretty often I end up in this kind of situation:
Steps to reproduce it:
1. When creating a GraphiQL component, provide a prop: `variables: null`
2. Refresh a page couple of times
3. Remove `variables: null`
4. Refresh the page (the result is shown on the screenshot)
This PR tries to address this issue by preventing null/undefined variables from being stored.

Handle null/undefined variables

---

src/components/GraphiQL.js

During one of the discussions with @stubailo and @lacker at https://github.com/graphql/graphql.github.io we decided to suggest this change (tried to find the original discussion, but looks like it's gone due to fair amount of rebasing). 
Also current best practice documentation suggests that variables should be provided as a JSON object and not as a string (at the moment GraphiQL provides variables as a string with stringified JSON inside):
http://graphql.org/learn/serving-over-http/#post-request

Provide variables as a JSON `Object` instead of a `String`

---

src/components/GraphiQL.js

As discussed in #168, this PR improves error reporting for variable parsing:
Here I handle 3 general cases:
* variables are `null`/`undefined` or an empty string - variables set to `null`
* variables string contains malformed JSON - result pane will show a detailed error message
* variables JSON is valid, but does not contain a JSON object - result pane will show an error message: `"Variables are not a JSON object."`
Along the way I also noticed that `"Fetcher did not return Promise or Observable."` error was not reported correctly. Existing code was setting the state, but after `_fetchQuery` is finished, the state is immediately reset once again. It works for all other scenarios because they all set the state in an async callbacks, but it's not that case with  `"Fetcher did not return …

Improved error handling for variables parsing

---

src/components/GraphiQL.js

since the fetcher shouldn't know if it is expected to return promise or observable,
it added a small logic to convert observable into promises when promise is a must.

single interface for fetch

---

README.md

Hey, this is kind of a trivial pull, but the CustomGraphiQL example fails to compile because of the error:
Syntax error: 'this' is not allowed before super()
...
constructor(props) {
this.state = {
^
....
Thanks!

fix custom graphiql example

---

src/components/GraphiQL.js

Addresses: https://github.com/graphql/graphiql/issues/187 by persisting doc-explorer state into storage, loading on mount

Saving doc-exploreer status into storage, loading on mount

---

src/components/DocExplorer.js

@asiandrummer this is something I found while trying to dynamically set schemas in a custom graphiql.
Changing the schema does not currently trigger an update on TypeDoc components. I feel like it should ? Right now the Doc pane shows the old fields even if the schema has been updated.
Let me know what you think!

Update TypeDoc when schema changes

---

src/components/DocExplorer.js
src/components/DocExplorer/FieldDoc.js
src/components/DocExplorer/MarkdownContent.js
src/components/DocExplorer/SchemaDoc.js
src/components/DocExplorer/SearchBox.js
src/components/DocExplorer/SearchResults.js
src/components/DocExplorer/TypeDoc.js
src/components/DocExplorer/TypeLink.js

Just to make things easier to find: rather than thinking "where does the search box live?" I can just type "search" into my editor's fuzzy finder and go straight to the component.

Split DocExplorer into smaller files

---

css/doc-explorer.css
src/components/GraphiQL.js

As suggested by @leebyron here:
https://github.com/graphql/graphiql/pull/244#issuecomment-266163750

Hide parent type name when doc explorer is narrow

---

css/app.css

Regression introduced in f9de00729998225a.
Tested on Firefox 45 (old, was broken), 49 (previous, still works), 50 (latest, still works) and Chrome 54 (current, still works).
Closes: https://github.com/graphql/graphiql/issues/250

Fix display issues on older Firefox

---

css/app.css
css/codemirror.css
css/doc-explorer.css
css/foldgutter.css
css/lint.css
css/loading.css
css/show-hint.css
package.json
resources/build.sh
yarn.lock

Follow-up to 8b4fe782c3d713ce. We shouldn't have to be manually micro-managing our CSS prefixes, which is an error prone process.
Instead, let's use autoprefixer. This commit sets that up and also removes the now-unnecessary prefixes from the source CSS. To get a sense of what's changed, here are the diffs between:
- the original output; and:
- the original source files piped through autoprefixer:
https://gist.github.com/wincent/bdc72e085b97158e4cc87e8c1226dd25
- the original output; and:
- the stripped down source files piped thorugh autoprefixer:
https://gist.github.com/wincent/bd41cb2d0cb92c6b77eec74d02db0798
Exceptions: I didn't remove the `-o-ellipsis-lastline` prefix nor the `-webkit-tap-highlight-color` one, because those aren't handled by autoprefixer (it only deals with stuff in …

[RFC] Use autoprefixer

---

css/doc-explorer.css
src/components/DocExplorer.js
src/components/GraphiQL.js

When introspection fails to load a schema (or a schema is intentionally excluded via providing `null` as the prop), the doc explorer currently continues to show a loading indicator. This change alters that behavior to instead declare that no schema exists. This also ensures schema is set to `null` after failure to load via introspection.
Fixes #212

Indicate when schema cannot be loaded in doc explorer.

---

README.md
src/components/GraphiQL.js

localStorage coerces everything to a String before saving it, so setting undefined results in getting "undefined". This change causes falsey values to be removed rather than being string coerced. It also introduces a fix to dirty storage from this issue.
Fixes #234

Ensure saving a non-value to storage actually removes it.

---

css/info.css
css/jump.css
package.json
src/components/DocExplorer.js
src/components/GraphiQL.js
src/components/QueryEditor.js
test/index.html
test/schema.js
yarn.lock

This leverages https://github.com/graphql/codemirror-graphql/pull/96 to provide cmd+click to jump to the docs for tokens in the query and mouse-over tool tops to provide in context documentation as well.
Closes #97

Add Jump-to-docs and Info tooltips

---

css/doc-explorer.css
src/components/DocExplorer/Argument.js
src/components/DocExplorer/FieldDoc.js
src/components/DocExplorer/SearchResults.js
src/components/DocExplorer/TypeDoc.js

As requested on issue #133, this PR displays the default value of a parameter on the Docs sidebar.
About the tests, I was thinking about adding `enzyme` to test the components, or we should keep the `react-test-renderer` only?
That's how it looks, let me know what do you think or if I should do something different:

Display defaultValue of parameters on the Docs

---

css/doc-explorer.css
src/components/DocExplorer/TypeDoc.js

Updates the CSS rules for the arguments of a field in the doc explorer to render one per line when there are more than one.
As suggested in #272

Break many arguments onto separate lines in doc explorer.

---

css/app.css
css/doc-explorer.css
css/show-hint.css
src/utility/onHasCompletion.js

This adds additional rendering in the hint typehead to indicate when a field hinted is deprecated. The styling matches that used in the info hover tooltips.
As mentioned in #273

Show deprecation warnings in hint typeahead

---

README.md

Just a tinsie-tiny one to add syntax highlighting to one of the code blocks in README.md. 
I noticed that this wasn't highlighted while installing GraphiQL earlier today and thought it could use a bit of color! 💅

Docs: syntax-highlight code-block in README.md

---

.babelrc
package.json
src/components/GraphiQL.js
src/components/__tests__/GraphiQL-test.js
yarn.lock

Closes #223
Right now, if a new fetching function is provided, GraphiQL doesn't refetch the schema with it. That can result in different schema running queries and used within the tool for insights.
This change causes the new fetcher to be called with introspection to get a new schema.
If GraphiQL is rerendered by the fetcher function is the same, then nothing will happen.
BREAKING: Note that if you provide a fetching function that is generated on every render, such as a non-autobound function in a parent React component, this will cause it to re-fetch the schema every time it's rerendered. To avoid this, it's important to ensure the fetching function changes only when intentionally using new behavior (such as a new endpoint to fetch from).

Run introspection again if fetcher changes.

---

css/app.css
css/doc-explorer.css
css/info.css
src/components/DocExplorer/FieldDoc.js
src/components/DocExplorer/TypeDoc.js

Closes #286
Adds a deprecated section for fields and enum values, moving deprecated references out of the common path, hiding them by default.

Update deprecation styles in doc explorer

---

css/show-hint.css
src/utility/onHasCompletion.js

Codemirror has behavior for scrolling with the typeahead open to track the current token. Our previous wrapping technique broke with this behavior. This PR simplifies the augmenting technique which no longer breaks.
Fixes #284

Fix: typeahead breaks on scroll.

---

README.md
src/components/GraphiQL.js

Currently there is a hard-coded prettify button in the toolbar, however not all clients of GraphQL wish to have that button, or to have that button in that particular position. This PR replaces hard-coding with a default toolbar that contains the prettify button.
This means if you pass a `<GraphiQL.Toolbar>` child to `<GraphiQL>` that the Prettify button will no longer appear. If you want the Prettify button, you can copy the existing source. Here is an example of adding a Toolbar with a Prettify button (elaborated in Readme example):
```js
class CustomGraphiQL extends React.Component {
render() {
return (
<GraphiQL ref={c => this.graphiql = c} ...>
<GraphiQL.Toolbar>
<GraphiQL.Button title="Prettify" onClick={this.handlePrettify}>
</GraphiQL.Toolbar>
</GraphiQL>
);
}
handlePrettify = () …
```

Default toolbar with prettify button.

---

src/components/GraphiQL.js

Closes #152
This adds two new public API methods to the `<GraphiQL>` component.
`getVariableEditor()` gets the CodeMirror instance for editing variables.
`refresh()` will refresh all CodeMirror instances, this may be helpful after changing the size of the containing element or after making it visible for the first time.

Add getVariableEditor() and refresh()

---

css/app.css

Fix bug where the dropdowns are only scrollable inside the toolbar

---

package.json
yarn.lock

For a required bug fix:
https://github.com/graphql/codemirror-graphql/releases/tag/v0.6.3

Update codemirror-graphql dependency

---

src/components/ExecuteButton.js

Needed to prevent the button click from refreshing the page in some situations, depending on where the component is added.

Update ExecuteButton to have type set to button

---

example/server.js
test/server.js

https://github.com/graphql/graphiql/pull/320 suggested changing the hard-coded port number in the example server so that it doesn't collide with the test app.
Instead of that, let's use random port numbers, which will strictly avoid any port collisions, including with apps that have nothing to do with this repo, because the OS will assign an unused port.
Tested by simultaneously launching:
cd example
npm install
npm run start # prints: Started on http://localhost:51638/
npm run dev # prints: Started on http://localhost:51578/
Then hit both links and see they work.

Use random port numbers in test and example apps

---

src/components/DocExplorer.js
src/components/GraphiQL.js

Adds a private `reset` method to `DocExplorer` which resets its `navStack`, returning it to the root doc page.
When `fetcher` is changed and introspection query re-runs, the docs need to be reset (#312)

Reset docs to root when fetcher is updated. Closes #312

---

css/app.css
src/components/GraphiQL.js
src/components/ToolbarMenu.js
src/components/ToolbarSelect.js

Made select and open have more typical behavior.

Menu doesnt stay open on click

---

src/components/GraphiQL.js

If a new query string is passed in (and `componentWillReceiveProps` is called) without manually editing query (e.g. programmatically modifying the content within the editor without key events), it's possible to have both `_updateQueryFacts` and `componentWillReceiveProps` trying to update `operationName` by calling the `setState` method, most often times the one in `componentWillReceiveProps` winning incorrectly.
The fix is to treat the outcome from `_updateQueryFacts` as truth and properly updating what to update during the component lifecycle.

handle the race condition in updating operationName

---

src/components/GraphiQL.js

This ensures updateQueryFacts runs and is applied even if no schema has loaded yet.

Update query facts fix

---

css/app.css

This is an quick initial fix for #328, it would be nice to leave the issue open anyway so that we can get some sort of overflow menu in.

Add css property so that toolbar truncates instead of stacking

---

css/doc-explorer.css
src/components/DocExplorer/TypeDoc.js
test/schema.js

Wubalubadubdub! First pass at the old inline-field descriptions. There is an edge-case though, since the doc-explorer has a `min-width` of 300px. So when the explorer is <300px, the ellipsis gets lost. I'd hate to alter that behavior as it can introduce regressions elsewhere:
Addresses: #169

First-pass at inline-field descriptions in doc-explorer

---

src/components/QueryEditor.js

Discussed in #353. There is a bug in GraphiQL with non-QWERTY keyboards that, because the key mapping is different from the English keyboard, the autocompletion pop-up is shown for incorrect set of characters (in QWERTZ keyboard for instance, `Alt-8` types `{` character, which the code recognizes within the whitelisted boundary).
Fixed by matching the exact key character.

fire autocompletion by matching the actual key content typed in

---

.eslintrc

Silences:
> The babel/no-await-in-loop rule is deprecated. Please use the built in no-await-in-loop rule instead.
During `{npm,yarn} run test`.

Silence eslint warning about deprecated babel rule

---

resources/build.sh

Disable source map to remove long line. Fix https://github.com/graphql/graphiql/issues/439.

Disable source map

---

package.json
yarn.lock

To match the one in codemirror-graphql.
Partially addresses: https://github.com/graphql/graphiql/issues/453

Loosen codemirror peer-dependency

---

package.json
yarn.lock

In the 0.14.x series, picked 0.14.9 because that is the lowest reported version to work with prop-types; see the README at:
https://github.com/reactjs/prop-types
Closes: https://github.com/graphql/graphiql/issues/453

Loosen React peer dependency

---

resources/build.sh

`npm run build` currently fails due to an uglify option that is no longer supported.
The option `screw-ie8` is no longer supported with 3.0.x version of uglify. It has been superseded by the option `ie8` which has the opposite effect so does not need to be specified.

Remove option screw-ie8 from build.sh uglify command

---

package.json

Make this library work with more peer-dependencies.
See: https://nodejs.org/en/blog/npm/peer-dependencies/
"One piece of advice: peer dependency requirements, unlike those for regular dependencies, should be lenient. You should not lock your peer dependencies down to specific patch versions. It would be really annoying if one Chai plugin peer-depended on Chai 1.4.1, while another depended on Chai 1.5.0, simply because the authors were lazy and didn't spend the time figuring out the actual minimum version of Chai they are compatible with."

package.json: expand accepted peerDependencies

---

src/components/QueryHistory.js
src/utility/HistoryStore.js
src/utility/StorageAPI.js

There are two possible scenarios where the storage quota may exceed:
- Obviously if we end up saving too many/large things
- When the mobile safari gets into the private browsing mode (the quota is set to 0)
GraphiQL started noticing this issue when there were too large of a query saved in the query history (`graphiql:queries`). Guard against this case by cleaning up the `HistoryStore` entries one by one until the saving is safe.

catch the error fired when the storage quota exceeds

---

package.json

Undoes #512.
We generally want to keep peerDependencies as liberal as possible.

Relax peerDependencies back to where they were

---

src/components/GraphiQL.js

It is fairly common to see tools with this capability (e.g. left/right panels in Atom), so I mechanically tried to double-click the resize area to reset the main section to 50%/50% before realizing I was not on a desktop tool :)
After adding this to the main section, I figured docs section could benefit from it as well. Because of how toggling variables section works (single click), it is not possible to add this to the variables section at the moment. I did not have enough time to investigate more as this would require a bigger UI change, which I would not do without starting a discussion anyway, so it is better left to a future work. This already adds value as it is, I think.
(The circle around the mouse on click is a thing from the screencast tool, not my PR obviously 😅)

Reset initial size of main and doc panels when double-clicking their resize area

---

src/components/GraphiQL.js
src/components/ResultViewer.js

Fixes #569 
If you specify environment variable `TRACING=true yarn dev` it adds tracing information to dev server. ResultViewer component removes tracing info from response and shows it as tooltip when you hover part of response.
For this to work patch to codemirror-graphql is needed, I will submit PR there in just a moment.
Screenshot:

Allow to specify result tooltip as prop (was: Implement hover trace display)

---

css/app.css

For instance, if there are too many toolbar items and the window is small, the doc explorer will not expand, which makes it pretty difficult to use.

let the toolbar elements to be overflowable

---

README.md
src/components/GraphiQL.js
src/components/QueryEditor.js
src/components/VariableEditor.js

Resolves #379.
This applies from the query editor and the variable editor, just like the "Run Query" keyboard shortcut.
I have successfully tried this using `npm run dev`, and `npm test` passes locally.
It took me forever to find a key combination that was not already taken over by another part of the system, and none of those mentioned in #379 worked. In the end, <kbd>Cmd</kbd>/<kbd>Ctrl</kbd>+<kbd>P</kbd> was the only combination that worked. I'm guessing CodeMirror (or else) attempts to leave it free for browser native behavior.
The real question is: does GraphiQL really need the print console to be accessible *from a keyboard shortcut* or not? If yes, feel free to pull this PR and play with different combinations.
(I am speaking at an event in less than a week where I am going to …

Add a keyboard shortcut to prettify the query from the editor

---

src/components/QueryEditor.js
src/components/VariableEditor.js

In v0.11.5 these errors display in the console:
```
Warning: Failed prop type: QueryEditor: prop type `readOnly` is invalid; it must be a function, usually from React.PropTypes.
Warning: Failed prop type: VariableEditor: prop type `readOnly` is invalid; it must be a function, usually from React.PropTypes.
```
Quick research looks like these prop types are invalid, and after changing this the errors go away

Fix readOnly prop type

---

css/doc-explorer.css
src/components/DocExplorer/Argument.js
src/components/DocExplorer/DefaultValue.js
src/components/DocExplorer/TypeDoc.js
test/schema.js

GraphiQL can now show default values for input object types. Currently, GraphiQL only shows default value for args that are scalar values, not input objects. This PR aims to solve this problem.
I think this solution is especially useful for a relay-compliant schemas where mutations are performed using a single `input`object argument.
Let me know what you think!
Here is a screenshot of what it looks like with the new addition:

Default values for input object types are now displayed in Doc Explorer

---

src/components/ExecuteButton.js

Currently hovering away from a menu item is causing the following exception:
```js
Warning: Received `false` for non-boolean attribute `className`. If this is expected, cast the value to a string.
in li (created by ExecuteButton)
in ul (created by ExecuteButton)
in div (created by ExecuteButton)
in ExecuteButton (created by GraphiQL)
in div (created by GraphiQL)
in div (created by GraphiQL)
in div (created by GraphiQL)
in div (created by GraphiQL)
```
As a result every menu item that gets highlighted stays permanently highlighted.
Culprit is the `selected` condition passing `false` as `className` , which is invalid. Returning `null` fixes this bug.

Fix `false` being passed as `className` to ExecuteButton's  menu list

---

README.md

- onSelect instead of onClick
- add labels, otherwise menus just appear as triangles

fix MenuItem example in README

---

css/history.css
src/components/HistoryQuery.js
src/components/QueryHistory.js
src/utility/QueryStore.js

Adds the ability to set and edit names of saved queries in history and favorites. Uses an inline text input field that is activated pressing a button, and dismissed on blur or **Enter**. Implements #637.
See screen recording: https://youtu.be/7Gbg9E9ryxc

Adds ability to set and edit names of queries in history and favorites

---

src/utility/normalizeWhitespace.js

When some text gets pasted into the editor, the pipe character ( | ) would be removed from the text.
I think the regex that normalizes the whitespace uses the character set so it doesn't need the pipe to mean "match any character in the set"

fixed pipe character being removed when pasting

---

example/index.html

It used to show Â for the cursor in code mirror.
The problem is due to the encoding.
Either setting charset in html or in building will help to fix it.

fix encoding problem when using min.js

---

css/app.css

This height is should be `30px` to match the `2px` in vertical border, `14px` in line height and `14px` in vertical padding. It seems [it used to be but was inexplicably changed](https://github.com/graphql/graphiql/commit/d5f027ae851d357c6d83e6b908baba888b5b7282) quite a while ago (maybe not intentional?). Here's an example of the of the difference that fixes the annoying `1px` overflow problem:

Fix variable-editor height

---

src/components/GraphiQL.js
src/components/QueryEditor.js
src/components/VariableEditor.js
src/utility/__tests__/mergeAst-fixture.js
src/utility/__tests__/mergeAst-test.js
src/utility/mergeAst.js

Create a button on the toolbar to defragment a query.
All fragments found on the editor pane will be stripped and their contents will be inserted as InlineFragment in all of their usage on queries and mutations.
This feature will improve readability and debugging, since it's hard to understand how strongly-fragmented queries relate to each other.
Before:
```
query TestQuery {
...Fragment
}
fragment Fragment on Test {
id
}
```
After:
```
query TestQuery {
... on Test {
id
}
}
```

Add merge feature

---

src/components/QueryEditor.js
src/components/ResultViewer.js
src/components/VariableEditor.js

My usage of search in Chrome/Firefox is generally:
1. Cmd-F to open the search input
2. Type my query
3. Type Cmd-G to iterate through the search results
When I do this out of muscle memory in GraphQL, I get suck since the
`Cmd-G` gets captured by the browser and puts my focus in the browsers
search input.
With this fix, my normal flow works as expected.
Tested on Chrome/Mac

Capture Cmd/Ctrl-G

---

src/components/QueryHistory.js

Tiny fix; without this you have to refresh the page after clicking a star in the history to see it updated.
Before:
After:

Fix updating UI after favoriting

---

package.json

Now that the license is MIT, then I think this should be fine to move back to MIT so tooling can pick it up.

Sets MIT in the package.json now that GraphiQL is MIT

---

src/components/DocExplorer/__tests__/FieldDoc-test.js
src/components/DocExplorer/__tests__/TypeDoc-test.js
src/components/DocExplorer/__tests__/TypeLink-test.js
src/components/__tests__/DocExplorer-test.js
src/components/__tests__/ExampleSchema.js

Seemed like a good place to start
- create ExampleSchema for tests
- full coverage for `TypeLink`, `FieldDoc`
- extensive coverage for `TypeDoc`
- starting point for `DocExplorer`

Add unit test coverage for DocExplorer components

---

package.json
src/components/GraphiQL.js
src/components/QueryEditor.js
yarn.lock

This PR adds a `Copy` button to the default toolbar.
Often times a query or mutation executed in GraphiQL will be copied to another destination. 
By adding a `Copy` button (as well as a keyboard shortcut), this allows a user a quick way of copying the specified query / mutation (in all fairness, `Command + A, Command + C` is not exactly a particularly time-intensive set of operations).
I can see a number of reasons why a `Copy` button in and of itself might be ambiguous (is this copying the query? the response?). That being said, I still think that there is _some_ utility in adding this button.
I can also see an argument to label the button `Copy Query`, but I was also trying to stay consistent with the `Prettify` and `Merge` buttons.
I also made the decision to copy a formatted query to …

Add a toolbar button to copy the existing query to clipboard

---

README.md
src/components/GraphiQL.js

This change allows `readOnly` to be passed to GraphiQL (the default export) which will pass it to `QueryEditor` and `VariableEditor`. Both `QueryEditor` and `VariableEditor` already accept `readOnly`, this just exposes it.

Add readOnly prop and pass to `QueryEditor` and `VariableEditor`

---

css/app.css

Hi, I came across this issue where an overridden style prevents the GraphQL error message from being displayed in `monospace`. This prevents the alignment of source code columns from working properly..
For example:
The illegal char is the silly "smart" quote, but the `^` points to the `m`
It works just fine if the font override is removed....

Remove font-family for hover error message

---

.flowconfig
packages/graphql-language-service-server/package.json
packages/graphql-language-service-server/src/findGraphQLTags.js
yarn.lock

@babel/parser is the supported parser for babel v7. This
upgrades usage of babylon to @babel/parser and passes some
additional options.

Replace babylon with @babel/parser

---

packages/graphiql/src/components/QueryEditor.js
packages/graphiql/src/components/VariableEditor.js

Submitting another PR because I missed two cases in my earlier PR https://github.com/graphql/graphiql/pull/791.

The hint dom nodes lives outside the codemirror dom tree currently.

---

packages/codemirror-graphql/package.json
packages/codemirror-graphql/src/__tests__/hint-test.js
yarn.lock

- Update tests to support `__typename` in object type hint suggestions :shrug:
- Quite a breaking change! This should bump codemirror-graphql to 0.9.0

Upgrade codemirror-graphql to gls interface/parser 2.0x

---

packages/graphiql/src/components/GraphiQL.js

This patch exposes `formatResult` as static function on `GraphiQL` component.
Default implementation is backward compatible `JSON.stringify(result, null, 2)`

Allow customize of result formatting (Prettier for example)

---

packages/graphql-language-service-interface/src/__tests__/getAutocompleteSuggestions-test.js
packages/graphql-language-service-interface/src/getAutocompleteSuggestions.js

This has the sortText in completion items reflect the order in which they appear in the schema. This appears to add more value then alphabetical sorting, since fields are often ordered and grouped semantically.
This also ensures completion items returned from the graphql language server are sorted at the top of the completion list when working inside tagged templates.

Add completion priority logic for tagged template completion requests

---

packages/graphiql/package.json
packages/graphiql/src/index.js
yarn.lock

- upgrade graphiql to use codemirror-graphql 0.9.0
- because we are using parser/interface 2.x, we are using utils 2.x which deprecates support for graphql versions below 0.12.x, thus update peer resolutions to reflect this
- upgrade development graphql to latest
- add `regenerator-runtime`
- deduplicate lockfile
- extensive manual testing, looks good!
(had been broken before because it required a change to the example project which has been implemented)
(P.S. I know I'm foregoing the proper babel-runtime/etc plugin route, but requiring `regenerator-runtime` directly was much simpler, and tree shaking can take care of it in build environments that duplicate this config. we can get more clever with it at a later iteration)

upgrade graphiql to codemirror-graphql 0.9.0, interface/parser 2.x

---

packages/graphiql/src/components/GraphiQL.js
packages/graphiql/src/components/__tests__/GraphiQL.spec.js
packages/graphiql/test/index.html

This bug was introduced with the `docExplorerOpen` PR merge. The last PR I merged, for codemirror-graphql upgrades for graphiql, I hadn't manually checked after the rebase. It appears that I made a typo in this previous PR related to default `DocExplorer` state.
The potentially impactful change this makes is actually unmounting the docs component when it's closed. Is that an issue?

Doc explorer fix

---

packages/graphiql/src/components/QueryEditor.js

`this.editor` might be undefined if error occured during `componentDidMount`, like #665

fix: check `this.editor` exist before `this.editor.off` in QueryEditor

---

packages/graphiql/src/components/GraphiQL.js

Fixes https://github.com/graphql/graphiql/pull/636  
Fixes https://github.com/graphql/graphiql/pull/722
This approach allows overriding the error handler. By default it uses `JSON.stringify` on the error; if the result is `'{}'` then it will instead create a `{message,stack}` error to stringify (since `JSON.stringify(new Error("Something"))` is `'{}'`).

Fix formatting of GraphiQL errors

---

packages/graphiql/src/components/GraphiQL.js

Sorry @acao, turns out there's situations where arrays of errors are returned which then outputs:
```json
[
{}
]
```
which is not super useful. This PR replaces the new formatError function with one that handles this situation better.
(Note this error message comes from `subscriptions-transport-ws` rather than from us)

Have arrays of errors output message if available

---

packages/graphql-language-service-parser/src/onlineParser.js

Fixes https://github.com/graphql/graphiql/issues/735
Basically the bad token wasn't being "eaten" so it literally was failing to advance the stream. This fix consumes it.

Fix 'Mode graphql failed to advance stream'

---

packages/graphiql/src/components/QueryEditor.js
packages/graphiql/src/components/ResultViewer.js
packages/graphiql/src/components/VariableEditor.js
packages/graphiql/src/utility/commonKeys.js

1. Extract common keys to utility
2. Preserve `ctrl-f` for macOS for moving forward (Emacs style key binding)

preserve `ctrl-f` for macOS for moving forward

---

packages/graphiql/src/utility/commonKeys.js

- dont expect window to be present for extraKeys MacOs detection logic
- use existing graphiql convention for detecting the presence of window

fix:(graphiql) - for SSR, regression from extraKeys bugfix, fixes #942 

---

CHANGELOG.md
packages/codemirror-graphql/package.json
packages/graphiql/package.json
packages/graphql-language-service-interface/package.json
packages/graphql-language-service-parser/package.json
packages/graphql-language-service-server/package.json
packages/graphql-language-service-types/package.json
packages/graphql-language-service-utils/package.json
packages/graphql-language-service/package.json

- add changelog
- remove peer deps
- minor version bumps for GLS + codemirror because of license change
- everything ready for next release but GraphiQL

prepare for next round of releases

---

packages/graphql-language-service-server/src/__tests__/GraphQLCache-test.js
yarn.lock

Result of running `npx yarn-deduplicate && yarn install --force` - turns out we had duplicate GraphQL modules installed.
Incidentally I decided `deps:` is better than `chore(deps):`; thoughts?

deps: yarn-deduplicate

---

resources/README.md

These tools were removed in https://github.com/graphql/graphiql/commit/be1e5fc718a3b8278d25560bfac37b78306fe52b, so we should remove them from the README too.
(`bumpVersion.js` sounds useful given our recent discussions, @acao?)

docs(tooling): remove docs for removed tooling

---

packages/graphiql/README.md

According to [this](https://github.com/graphql/graphiql/commit/07fc6fee2780cb65668c1ca6b03688cdb82fcf44) commit, apparently the files from `graphiql/example` were moved to `packages/graphiql-examples/cdn/` but the README.md still points to the old files. This PR fixes this.

docs: correct the examples links

---

packages/graphql-language-service-interface/README.md
packages/graphql-language-service-parser/README.md
packages/graphql-language-service-server/README.md
packages/graphql-language-service-types/README.md
packages/graphql-language-service-utils/README.md

Some of the links pointing to packages were broken following the move to the monorepo.

Updated broken links to packages in README files

---

packages/graphiql/test/index.html

Only for the GraphiQL dev environment: add websocket subscriptions support powered by `subscriptions-transport-ws` (note: this only affects the `subscription` operation, other operations delegate to the previous fetcher).

dev: add ws subscriptions support to test environment

---

packages/graphiql/src/utility/StorageAPI.js

Hi !
I was trying to use GraphiQL with Gatsby but I got `window is not defined` issue.

fix: check `window` is defined before using it

---

.eslintrc.js
.travis.yml
packages/codemirror-graphql/src/utils/jump-addon.js
packages/codemirror-graphql/src/variables/lint.js
packages/graphiql/src/utility/mergeAst.js
packages/graphql-language-service-server/src/__tests__/GraphQLCache-test.js
yarn.lock

- Fixed 6 lint errors
- Use a frozen yarn lockfile on CI so that attempts to change it (e.g. when there are merge conflicts, or out of date dependencies) are caught (see [this build](https://travis-ci.org/graphql/graphiql/jobs/590013798) to see this in action)
- Fix merge conflicts in yarn.lock

Fix yarn.lock merge conflict; prevent recurrence

---

packages/graphiql/css/app.css
packages/graphiql/css/doc-explorer.css
packages/graphiql/css/history.css
packages/graphiql/src/components/DocExplorer.js
packages/graphiql/src/components/DocExplorer/SearchBox.js
packages/graphiql/src/components/DocExplorer/TypeLink.js
packages/graphiql/src/components/GraphiQL.js
packages/graphiql/src/components/HistoryQuery.js
packages/graphiql/src/components/QueryEditor.js
packages/graphiql/src/components/QueryHistory.js
packages/graphiql/src/components/ResultViewer.js
packages/graphiql/src/components/ToolbarButton.js

This pull request brings a baseline of accessibility to the various GraphiQL components with a focus on making them usable by keyboard and/or screen readers. Some highlights worth mentioning:
- The various sections of the interface are now implemented as regions (using `<section>` elements) with proper accessible names (using `aria-label`) for identifying their purpose. This is especially important for users who rely on screen readers as it's otherwise very difficult to identify and navigate the different parts of the interface, in particular the query editor and the results viewer.
- All components are now navigable by keyboard, with especially the history pane benefitting from this. Previously, the history pane could not be navigated by keyboard at all as interactions relied solely on …

fix(accessibility): improve accessibility of all components

---

packages/graphiql/css/app.css

As discussed in #969 this is a simple fix, just added a `flex-basis: 1em` value to `graphiql/packages/graphiql/css/app.css`.
Since the goal is to keep the panel from disappearing when resized all the way to the left, any value small enough to allow the panel to still be visible and "draggable" by the mouse should work.
I think is a simple solution, nothing in the UI breaks by using the value, but I'm open to listen to other ways or recommendations to implement this change.

fix(css): added minimum width for result panel in GraphiQL

---

packages/graphiql/package.json
packages/graphiql/resources/build.sh
tsconfig.base.json

The current source used for minifying graphiql in the build script is wrong. Therefore the build is broken. After debugging for the reason while the build was failing, I figured out that in order to use the correct source for the build, we need all the packages used in the build to be transpiled to their es5 equivalents for the build process to work. Main reason being that uglify doesn't support es6 syntax and **requires** es5 to minify the file. Given that the tsconfig specified the target as `esnext`, the builds were transpiled to their es6/es7 equivalents, which is required by graphiql as a dependency, and so uglify breaks.
I'm not sure why we decided to set the tsconfig to `esnext`, but this question should be answered before merging this PR.
This closes #976

Fix broken GraphiQL minified build

---

packages/graphiql/cypress/integration/prettify.spec.js
packages/graphiql/src/components/GraphiQL.js
packages/graphiql/src/utility/__tests__/find.spec.js

Closes #990 
and rid of unnecessary editors updates when content not changed during prettification

feat(graphiql): Prettify also formats query variables

---

README.md

Fix a typo (missing 'p' in GraphiQL) in the last sentence of the _Intro_ section.

Fix typo in 'Intro' section

---

packages/graphiql/package.json
yarn.lock

Resolves #1004 by upgrading to a version of `markdown-it` that addresses the vulnerability.

fix: security bump for markdown-it, resolves #1004

---

packages/graphiql/css/show-hint.css

As I understand, `graphiql` have copied CodeMirror CSS files and sorted properties by alphabet, but it causes the problem: `overflow` override `overflow-y` and disable vertical scroll for the hints.
CodeMirror source file for the hints: https://github.com/codemirror/CodeMirror/blob/master/addon/hint/show-hint.css#L21

fix: hints vertical scroll

---

packages/codemirror-graphql/src/utils/info-addon.js

graphql/codemirror-graphql#246
From the original PR
> This PR fixes a [Content Security Policy (CSP) violation](https://www.html5rocks.com/en/tutorials/security/content-security-policy/)  for those who are using CSP headers and do not have `script-src` of `unsafe-eval` enabled.
> The way the code is written now, `onHover` is `undefined` in [this call to `setTimeout`](https://github.com/graphql/codemirror-graphql/blob/master/src/utils/info-addon.js#L52). Passing `undefined` to `setTimeout` triggers a CSP violation for `'unsafe-eval'` because `setTimeout` thinks you are passing a string, which is [not allowed](https://developer.chrome.com/extensions/contentSecurityPolicy#JSEval).
> The CSP Violation: `Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source …

fix: csp headers violation @gracenoah 

---

packages/graphiql/src/components/GraphiQL.js
packages/graphiql/src/components/__tests__/GraphiQL.spec.js

This should fix #671.
The core issue here was that when `GraphiQL.xxx` got wrapped by some other component, `.type` would on the child would be of that wrapper causing the the type equality check to fail. 
By checking for `displayName` first, consumers can set `displayName` on their wrapped components and still be able to override graphiql components.

fix: prefer displayName over type equality for children overrides

---

packages/graphql-language-service-parser/src/Rules.ts

originally by @PascalSenn in graphql/graphql-language-service#220
- fixes `Mode graphql failed to advance stream` further down in the LSP
- same bug we worked around in GraphiQL or graphql-cm? months ago.
- resolves the issue at the LSP level (parser), for both server/browser contexts

fix: exclusion for nonbreakable whitespace chars

---

examples/graphiql-webpack/package.json
packages/graphiql/package.json
packages/graphiql/src/components/GraphiQL.js
packages/graphiql/src/components/QueryHistory.js
packages/graphiql/src/components/__tests__/DocExplorer.spec.js
packages/graphiql/src/components/__tests__/GraphiQL.spec.js
packages/graphiql/src/components/__tests__/HistoryQuery.spec.js
packages/graphiql/src/components/__tests__/QueryHistory.spec.js
packages/graphiql/src/components/__tests__/fixtures.js
packages/graphiql/src/components/__tests__/helpers/storage.js
resources/enzyme.config.js
yarn.lock

- use `UNSAFE_` for one `componentWillUpdateProps`
- refactor another `componentWillUpdateProps` via @ryan-m-walker's PR
- deprecate peer resolution for react 15
- dev dependencies bumped to react 16
- `react-test-renderer` and `enzyme` bumped to react 16
- add test coverage via @ryan-m-walker's PR as well, as codecov was failing the PR because of a drop in test coverage
BREAKING CHANGE: Deprecate support for React 15. Please use React 16.8 or greater for hooks support.
thanks @ryan-m-walker for doing most of this!

feat: deprecate support for 15, support react 16 features

---

.eslintignore
package.json
yarn.lock

this ameliorates a few linting issues that had arisen from new build artifacts
to reproduce the issue:
1. run `yarn test` locally which will run the entire CI, including the storybook and webpack example
2. then run `yarn lint` or even just `yarn eslint` and then you get

chore: minor tweaks for a clean build/lint

---

README.md

Remove single quotes and leading `.`, which were making the links lead to GitHub 404 pages.

docs: fix README.md relative links

---

packages/graphiql/resources/renderExample.js

lets use our own swapi-api example as a reference example. because we use a wildcard we need to omit credentials in the example.

chore(examples): switch to using our own swapi-api

---

examples/graphiql-cdn/index.html

Missed out from this review comment: https://github.com/graphql/graphiql/pull/1061/files#r356005286
(`response.json()` [returns a promise](https://developer.mozilla.org/en-US/docs/Web/API/Body/json)) so it'll never throw synchronously assuming `response` is a response object, so the `try/catch` wasn't doing anything.

docs: fix CDN example fetcher text fallback

---

.eslintignore
DEVELOPMENT.md
jest.config.js
netlify.toml
package.json
packages/codemirror-graphql/package.json
packages/graphiql/package.json
packages/graphql-language-service-interface/package.json
packages/graphql-language-service-parser/package.json
packages/graphql-language-service-server/tsconfig.esm.json
packages/graphql-language-service-server/tsconfig.json
packages/graphql-language-service-types/package.json
packages/graphql-language-service-utils/package.json
yarn.lock

- fix jest issue w/ moduleNameMapper, so tests don't need a build to run
- reconfigured build tooling for more streamlined ci. fails more quickly.
- test = jest now
- remove most scripts from subpackages, almost everything should be done from root now

chore: improve CI scripts, fix crosswise test resolution, cleanup

---

packages/graphql-language-service-utils/src/validateWithCustomRules.ts

I'm looking into cleaning up how validation rules are exported in
`15.0.0`. So I decided to refactor this code and switch rules imports to
use `*Rule` that is public API instead of importing internal files
directly. Sadly we forget to expose `ExecutableDefinitions` rule in
public API but I will fix it in `15.0.0` and backport into `14.x.x`

chore: switch to importing validation rules from graphql's public API

---

.github/workflows/ci.yml

https://github.com/cypress-io/github-action#important ah we just need to fix the action to 16.04, actions rolled over to 18.04 overnight

chore: cypress container/action for cypress

---

packages/graphql-language-service-interface/src/GraphQLLanguageService.ts
packages/graphql-language-service-interface/src/__tests__/getDefinition-test.ts

This PR makes it possible to jump to the definition of a named scalar type. 
How this would look like once integrated into VSCode for example:

feat(definition): get scalar definition

---

packages/graphql-language-service-server/src/__tests__/GraphQLCache-test.ts
resources/test.config.js

```
/Users/keita/Desktop/starPlatinum/graphQL/graphiql/packages/graphql-language-service-server/src/__tests__/GraphQLCache-test.ts
34:11  warning  'configDir' is already declared in the upper scope  no-shadow
/Users/keita/Desktop/starPlatinum/graphQL/graphiql/resources/test.config.js
1:11  warning  'jsdom' is defined but never used  no-unused-vars
✖ 2 problems (0 errors, 2 warnings)
```
fixed this warning

fix: eslint warining fixes

---

packages/graphql-language-service-server/src/__tests__/GraphQLCache-test.ts

I got the following errors in packages/graphql-language-service-server/src/__tests__/GraphQLCache-test.ts
```
Argument of type 'Map<unknown, unknown>' is not assignable to parameter of type 'Map<string, ObjectTypeInfo>'.
Type 'unknown' is not assignable to type 'string'
```
So added types to receive benefits of typescript

fix: type check

---

packages/graphql-language-service/README.md

> The node executable contains several commands: server and a command-line language service methods (lint, autocomplete, outline).
https://github.com/graphql/graphiql/blob/master/packages/graphql-language-service/README.md#using-the-command-line-interface
@IvanGoncharov the current `help` command does not list the required options 
````
At least one command is required.
Commands: "server, validate, autocomplete, outline"
```
What about adding them to the help flag.

docs: lint command is not available

---

packages/graphiql/src/components/GraphiQL.tsx
packages/graphiql/src/state/GraphiQLSchemaProvider.tsx
packages/graphiql/src/state/MigrationContext.tsx

This PR in essence wraps the entirety of GraphiQL in an aggregated
context provider to which other context providers can be attached. 
The short term goal of this is to separate out what is now GraphiQL state
into separate, smaller contexts which can be hooked into my plugins, etc
Being as we must ensure the provider is wrapped around GraphiQL I had to make
a facade component to do the wrapping and proxy props to the actual class.

WIP: feat: Add migration context to enable GraphiQL refactoring

---

packages/graphql-language-service/src/client.ts

print to stderr even if falsy value is thrown or thrown error does not have property `stack`. it was intended to implement by #1381

chore: improve the way to print to stderr

---

packages/graphiql/src/utility/introspectionQueries.ts

this should be all we need for introspection queries, especially as they are becoming increasingly dynamic with GraphQL 15
would be nice to allow users to pass settings to `getIntrospectionQuery()` via props or plugins eventually

chore: refactor introspection utility for easier maintenance

---

packages/graphql-language-service/package.json
packages/graphql-language-service/src/cli.ts

The current `--help` output of the `graphql-language-service` CLI misses the possible <commands>.

chore: improved the CLI's help output

---

working-group/agendas/2020-03-10.md

- `yarn ci` fails due to markdown format, so fix the format

fix: markdown format

---

packages/graphiql/README.md

previous link was directing to `https://github.com/graphql/graphiql/blob/master/packages/graphiql/README.md#1165`

fix: update issue link

---

packages/graphql-language-service-interface/src/getDefinition.ts
packages/graphql-language-service-server/src/Logger.ts
packages/graphql-language-service-server/src/startServer.ts

seems that vscode-languageserver deprecated writing to stderr by default
also removing direct calls to process in the underlying language service so that it's compatible with non-node runtimes. trapping the exceptions in startServer should handle exceptions, but we should make sure that the editor events that we don't return from in those cases continue firing as normal?
CC: @divyenduz , @zth

fix: restore error handling for server #1306

---

packages/graphql-language-service-interface/src/GraphQLLanguageService.ts
packages/graphql-language-service-interface/src/getAutocompleteSuggestions.ts
packages/graphql-language-service-interface/src/getDiagnostics.ts
packages/graphql-language-service-interface/src/index.ts
packages/monaco-graphql/package.json
packages/monaco-graphql/src/graphqlMode.ts
packages/monaco-graphql/src/graphqlWorker.ts
packages/monaco-graphql/src/languageFeatures.ts
packages/monaco-graphql/src/monaco.contribution.ts
packages/monaco-graphql/src/monaco.d.ts
packages/monaco-graphql/src/typings/refs.d.ts
packages/monaco-graphql/src/workerManager.ts

Re https://github.com/graphql/graphiql/pull/1421 
Had a good discussion offline with @acao about how to incrementally support GraphQL LSP in Monaco and we agreed to implement Completion first, with which we can test the runtime agnostic GraphQL LS and get a good understanding of integration between Monaco and GraphQL LS.
The code is still not demo-ready due to three blockers, which can be resolved later:
* runtime agnostic GraphQL LS
* `GraphQLCache` initialization
* Convert AST token kind to `CompletionItemKind` https://github.com/graphql/graphiql/pull/1428/files#diff-6d88bd46b01fdd44682f45d55e5202bdR59

feat: Monaco graphql Completion

---

packages/graphql-language-service-server/src/GraphQLCache.ts
packages/graphql-language-service-server/src/MessageProcessor.ts
packages/graphql-language-service-server/src/startServer.ts

This allows supplying a pre-existing graphql-config to the LS. The idea is that external consumers, like a vscode extension, should be able to provide defaults and extensions of the existing config (or generate it programatically all together) in a way that can be supplied directly to the LS.
It's basically https://github.com/graphql/graphiql/pull/1272 but rebased.

feat: optionally provide LSP an instantiated GraphQLConfig

---

packages/graphql-language-service-server/README.md
packages/graphql-language-service-server/src/GraphQLCache.ts
packages/graphql-language-service-server/src/Logger.ts
packages/graphql-language-service-server/src/MessageProcessor.ts
packages/graphql-language-service-server/src/__tests__/GraphQLCache-test.ts
packages/graphql-language-service-server/src/__tests__/MessageProcessor-test.ts
packages/graphql-language-service-server/src/constants.ts
packages/graphql-language-service-server/src/findGraphQLTags.ts
packages/graphql-language-service-server/src/parseDocument.ts
packages/graphql-language-service-server/src/startServer.ts

- introduces typescript, tsx and jsx support via babel parser plugins
- #1263 by @zth is an alternative to solving this problem which also supports reasonml, and potentially other  a non-ast branch by @zth using regular expressions should  be reconsidered.
-tests for typecript and tsx added
- `getQueryAndRange` changed to `parseDocument`, and made override-able as `parse` by `startServer`.

feat: typescript, tsx, jsx support for LSP server using babel

---

packages/graphql-language-service-server/src/GraphQLCache.ts
packages/graphql-language-service-server/src/MessageProcessor.ts
packages/graphql-language-service-server/src/__tests__/GraphQLCache-test.ts

This ensures that a custom parser is used if passed to the server.

fix: make sure that custom parser is used if passed to process

---

packages/graphql-language-service-server/src/MessageProcessor.ts

This adds `@` as an explicit trigger character for code completion in the LS. What this does is that it brings up the autocomplete list as soon as you type "@", rather than you needing to manually activate autocomplete (ctrl+space) to autocomplete directives.

feat: make sure @ triggers directive completion automatically

---

README.md
working-group/README.md

- add a landing readme for the working group directory
- add a reference in the Community section in the root readme

chore: add working group landing readme

---

packages/graphql-language-service-interface/tsconfig.esm.json
packages/graphql-language-service-interface/tsconfig.json
packages/graphql-language-service-parser/tsconfig.esm.json
packages/graphql-language-service-parser/tsconfig.json
packages/graphql-language-service-server/tsconfig.esm.json
packages/graphql-language-service-server/tsconfig.json
packages/graphql-language-service-types/tsconfig.esm.json
packages/graphql-language-service-types/tsconfig.json
packages/graphql-language-service-utils/tsconfig.esm.json
packages/graphql-language-service-utils/tsconfig.json
packages/graphql-language-service/tsconfig.json

`rootDir` doesn't imply `include`, so output files were being incorrectly included as inputs.  Besides being less efficient, this made it necessary to clean before each TypeScript build.

build: add missing include lists

---

README.md

these were old and sending folks to the wrong channel

chore(docs): discord links in root readme

---

packages/graphql-language-service-utils/package.json

lol, oops this probably sucked on the install side. my bad i didnt remove this a while ago

chore: remove engine strict from utils, import() not used anymore

---

.nvmrc
examples/graphiql-webpack/package.json
netlify.toml
yarn.lock

- netlify build has issues with babel
- nvmrc to use latest lts in netlify
- bump babel/webpack dependencies in examples as well (need preset 7.9.0+)

ci: fix netlify build issues with babel

---

DEVELOPMENT.md
package.json
packages/graphiql/tsconfig.json
resources/README.md
yarn.lock

Especially locally, `tsc --build` without `--force` flag seems to give us some issues after removing `tsc --build --clean` as a prelminary step.
For example, for the last GraphiQL alpha, the index.js file didn't publish, despite my running `yarn build-ts` beforehand!

ci: force build

---

babel.config.js
packages/graphql-language-service-interface/package.json
yarn.lock

tested the last alpha.7 downstream in codesandbox, and this is broken

fix: graphiql@1.0.0-alpha.7 has broken reference to vscode types

---

packages/graphql-language-service-interface/src/GraphQLLanguageService.ts
packages/graphql-language-service-server/src/startServer.ts
packages/graphql-language-service/src/cli.ts
packages/graphql-language-service/tsconfig.json

This should do what @divyenduz set out to do in #1481 more universally. Any exception in any of the handlers bubbles up to the GLS output channel now.
It also repairs the CLI. It was targeting `esnext` by default, thus a use of nullish coalescing was breaking the CLI (not supported natively in node yet). 
So, I set it to `target: es2017` for node 10 support.
Additionally, CLI should default method to `node` as advertised.
Tested with both the CLI using validate command, and `vscode-graphql` - the only issue there is the custom prisma extension is throwing an error. the extension works great if you remove that extension. I think it just needs to be upgraded for the new graphql-config?

fix: repair CLI, handle all schema and LSP errors

---

packages/graphiql/src/components/QueryHistory.tsx
packages/graphiql/src/components/ResultViewer.tsx

these are auto-added by vscode because of the tsconfig somehow, and usually work for builds but sometimes break tests

chore: relative paths for imports

---

examples/graphiql-webpack/webpack.config.js
packages/graphiql/resources/webpack.config.js
packages/graphql-language-service-interface/src/GraphQLLanguageService.ts
packages/graphql-language-service-interface/src/getAutocompleteSuggestions.ts
packages/graphql-language-service-types/src/index.ts

this re-uses vscode's own CompletionItemKind to introduce completion kinds at the LSP interface level.  these will make different icons appear for different types on completion. currently kind values are not returned, so it's up to the user to specify them.
also, introduce a const for RuleKinds lookup that will be used by monaco. using these, monaco has slightly different kinds that we will configure in a simple lookup object in a later PR

feat: introduce proper vscode completion kinds

---

examples/graphiql-webpack/src/index.jsx
examples/monaco-graphql-webpack/src/index.ts
packages/graphiql/resources/renderExample.js
packages/monaco-graphql/src/defaults.ts

trying to figure out the situation with netlify support still, but the swapi netlify tld switched from .com to .app at some point and I can't switch it back?
this fixes our master build, but swapi itself is another matter.

chore: netlify swapi schema urls are broken

---

README.md

The Working group link in the `Community` section was broken.

docs: fix working Group link in README.md

---

packages/graphql-language-service-interface/src/getAutocompleteSuggestions.ts

I got an type error when using `graphql-language-service-server`.
```
server/node_modules/graphql-language-service-interface/dist/getAutocompleteSuggestions.d.ts:2:26 - error TS2305: Module '"../../graphql-language-service-types/dist"' has no exported member 'ContextToken'.
server/node_modules/graphql-language-service-interface/dist/getAutocompleteSuggestions.d.ts:2:40 - error TS2305: Module '"../../graphql-language-service-types/dist"' has no exported member 'State'.
```
It seems that `ContextToken` and `State` are defined in `graphql-language-service-parser instead` of `graphql-language-service-types`. So I removed the `@ts-nocheck` flag and fix the type errors.
@acao can you help me to review this

fix: remove @ts-nocheck and fix type errors

---

packages/graphiql/src/components/VariableEditor.tsx

Closes #1532 
Initialised `ignoreChangeEvent` to `false` in Variables Editor
@acao can you review this

fix: trigger edit variables on first render

---

packages/graphiql/src/components/common/Resizer/ResizeHandler.tsx
packages/graphiql/src/components/common/Resizer/Resizer.stories.tsx
packages/graphiql/src/components/common/Resizer/Resizer.tsx
packages/graphiql/src/components/common/Resizer/index.ts
packages/graphiql/src/components/common/Resizer/types.ts
packages/graphiql/src/components/common/Resizer/util.ts

This PR adds a new Resizer component. So we will be able to resize the editors. We can simply wrap the editor with resizer component like this
```ts
<Resizer
border="bottom"
handlerStyle={{ backgroundColor: 'rgba(0, 0, 0, 0.2)' }}
>
<main>{`Main content`}</main>
</Resizer>
```
This above example will add a resizer option below the `main` tag and we can also pass the required styles to it.
@acao can you review this

improvement: add resizer component

---

README.md

This was likely some instructions on markdown & html image; but with the info text still there

docs: remove copy/paste artifact

---

packages/graphiql/README.md
packages/graphiql/resources/renderExample.js
packages/graphiql/src/components/GraphiQL.tsx
packages/graphiql/src/components/HeaderEditor.tsx
packages/graphiql/src/components/HistoryQuery.tsx
packages/graphiql/src/components/QueryHistory.tsx
packages/graphiql/src/components/VariableEditor.tsx
packages/graphiql/src/components/__tests__/GraphiQL.spec.tsx
packages/graphiql/src/components/__tests__/HistoryQuery.spec.tsx
packages/graphiql/src/components/__tests__/fixtures.ts
packages/graphiql/src/css/app.css
packages/graphiql/src/utility/QueryStore.ts

This adds a header editor, for submitting HTTP headers when executing a query, as described in #59.
This is especially useful when you want to send an authentication token with your request, for example.
This adds an optional `headers` parameter to the `fetcher` which can then be merged into any other headers that the application sets itself.
```js
import React from 'react';
import ReactDOM from 'react-dom';
import GraphiQL from 'graphiql';
import fetch from 'isomorphic-fetch';
function graphQLFetcher(graphQLParams, headers) {
return fetch(window.location.origin + '/graphql', {
method: 'post',
headers: Object.assign(headers, { 'Content-Type': 'application/json' }),
body: JSON.stringify(graphQLParams),
}).then(response => response.json());
}
ReactDOM.render(<GraphiQL …
```

feat: Add Headers Editor to GraphiQL

---

packages/graphiql/src/components/GraphiQL.tsx
packages/graphiql/src/components/__tests__/GraphiQL.spec.tsx

Closes #1560 
This PR will display variable editor when headers editor is not enabled
@acao can you review this :)

fix: display variable editor when headers are not enabled

---

packages/codemirror-graphql/src/__tests__/hint-test.js

Fix test cases inside `hint-test.js` of `codemirror-graphql` because the change of test cases made by #902 was appropriate when using the version of ^14.0.2 of `graphql` as a dependency but `codemirror-graphql` currently uses 15.0.0.

test: fix test cases for codemirror-graphql

---

packages/graphiql/src/api/providers/GraphiQLEditorsProvider.tsx
packages/graphiql/src/api/providers/GraphiQLSchemaProvider.tsx
packages/graphiql/src/api/providers/GraphiQLSessionProvider.tsx

It's referenced here that the returned dispatcher from useReducer doesn't need to be passed as a dependency to useCallback because the reducer is evaluated directly in the render phase.
https://github.com/facebook/react/issues/14099#issuecomment-436647120

fix: remove reducer dispatcher from useCallback dependencies

---

packages/graphql-language-service-interface/src/__tests__/getDiagnostics-test.ts
packages/graphql-language-service-interface/src/getDiagnostics.ts

Connects https://github.com/graphql/graphiql/issues/1565
fixes highlightNode `xxx in xxx` syntax to revert back to simple dot notation for checking of existence

fix: highlightNode xxx in xxx syntax to revert back to simple dot notation for checking of existence

---

examples/monaco-graphql-webpack/package.json
lerna.json
netlify.toml
packages/codemirror-graphql/README.md
packages/codemirror-graphql/package.json
packages/codemirror-graphql/resources/checkgit.sh
packages/codemirror-graphql/resources/mochaBootload.js
packages/graphiql/README.md
packages/graphiql/package.json
packages/graphiql/resources/checkgit.sh
packages/graphiql/src/components/GraphiQL.tsx
packages/graphiql/src/types/index.ts
packages/graphql-language-service-cli/package.json
packages/graphql-language-service-interface/README.md
packages/graphql-language-service-interface/package.json
packages/graphql-language-service-interface/src/getHoverInformation.ts
packages/graphql-language-service-parser/README.md
packages/graphql-language-service-parser/package.json
packages/graphql-language-service-server/README.md
packages/graphql-language-service-server/package.json
packages/graphql-language-service-types/README.md
packages/graphql-language-service-types/package.json
packages/graphql-language-service-utils/README.md
packages/graphql-language-service-utils/package.json
packages/graphql-language-service/package.json

- update links in package.json and readme
- update configuration in a few places
- update some comments
- update some of the scripts we don't really use anymore
- no `master`s left, suckas!
unrelated:
- switch back to `prepublishOnly` (accidentally merged rewrite without upstream improvements, warrants further checks, oops!) for windows/etc support

chore: finish converting to main branch

---

packages/monaco-graphql/README.md

typedoc builds are still broken, so meanwhile, find the docs at the last working build I guess?

docs: add temporary typedoc link

---

packages/graphiql/src/components/GraphiQL.tsx
packages/graphiql/src/components/HeaderEditor.tsx

- headers tab does not re-fetch schema with same headers when fetcher prop changes
- codemirror mode for json, `graphql-headers` is a non-existant mode
- resolves #1592

fix: headers tab - highlighting and schema fetch

---

packages/graphiql/jest.config.js
packages/graphiql/src/utility/__tests__/mergeAst-fixture.ts
packages/graphiql/src/utility/__tests__/mergeAst.spec.ts
packages/graphiql/src/utility/mergeAst.ts

Some massive improvements to `mergeAsts`:
- Doesn't inline fields/fragments if they use directives
- Doesn't drop following selection sets using same field name (merges them instead)
- Factors in types if optional schema is provided, allowing for deeper merging (i.e. no more `... on User {...}` when you're already referring to the User type)
- Stronger types throughout
- Tighter conversion to `InlineFragment` (doesn't add extraneous attributes)
- Still manages this on a single `visit`

feat(merge): make fragment merging type-aware

---

packages/graphiql/README.md

the documentation incorrectly indicates that `headers` prop is persisted by default

docs: clarify use of headers prop

---

packages/graphql-language-service-interface/src/getAutocompleteSuggestions.ts

fixes #1622
Restores completion for variable definitions. When we fixed a bug that broke non-null lists in the parser, we did not update the completions for this change to the parser. this impacts monaco-graphql, graphiql, etc

fix: regression for variable def completion #1622

---

packages/graphql-language-service-interface/src/autocompleteUtils.ts
packages/graphql-language-service-interface/src/getAutocompleteSuggestions.ts
packages/monaco-graphql/src/utils.ts

this was only kinda working with emmet completion before, so now we can differentiate our types from emmet types, and ensure the item added on completion replaces and doesn't double up the `$` character as it does. this impacts codemirror, graphiql, monaco-graphql, and IDE extension implementatons
Monaco Example: (shows type at the end of completion row, cut off in gif capture)

improvement: completion for defined variables

---

packages/graphiql/src/components/GraphiQL.tsx

need to make sure `variables` is typed as any, since it comes in as an object literal, not a string. resolves #1632

variables in FetcherParams

---

packages/graphql-language-service-interface/src/GraphQLLanguageService.ts

This LSP service class is only used by the LSP server currently, so this only effects the server
This actually prevents the server from running at all!

improvement: server only LSP bugfix for config extensions

---

packages/graphql-language-service-parser/src/types.ts

was having this issue:
`_Kind` was not even needed to begin with! can just be inferred from `typeof Kind`. it must be that they dropped it in 15 sometime after `15.0.0`

chore: _Kind is causing issues in graphql 15

---

.vscode/settings.json
packages/graphql-language-service-server/src/GraphQLCache.ts
packages/graphql-language-service-server/src/Logger.ts
packages/graphql-language-service-server/src/MessageProcessor.ts
packages/graphql-language-service-server/src/__tests__/MessageProcessor-test.ts
packages/graphql-language-service-server/src/startServer.ts

- requires using `createConnection()` strategy
- extension settings on server side for the first time
- allow graphql-config `loadConnfig()` `baseDir` to be configured
- properly calculate offsets for inline operation fragment defs

feat: custom config baseDir, embedded fragment def offsets

---

packages/graphiql/src/components/DocExplorer/Directive.tsx
packages/graphiql/src/components/DocExplorer/FieldDoc.tsx
packages/graphiql/src/components/DocExplorer/__tests__/FieldDoc.spec.tsx

Directives are not exposed in the introspection schema (discussion here: https://github.com/graphql/graphql-spec/issues/300). Nevertheless, if GraphiQL is supplied with an SDL schema, it can access AST directives for fields. It would be useful to show field directives in Doc Explorer for that case.

improvement: Show directives inside of FieldDoc.

---

packages/graphiql/src/components/GraphiQL.tsx

this fix is a recreation of #987 by @jimmybergman

fix: dont use initial query on every re-render

---

packages/graphql-language-service-server/README.md
packages/graphql-language-service-server/package.json
packages/graphql-language-service-server/src/MessageProcessor.ts
packages/graphql-language-service-server/src/startServer.ts
yarn.lock

- require `dotenv` in the server runtime (for loading graphql config values), and allow a `graphql-config.dotEnvPath` configuration to specify specific paths
- reload server on workspace configuration changes
- reload severside `graphql-config` and language service on config file changes. definitions cache/etc will be rebuilt
- note: client not configured to reload on graphql config changes yet (i.e endpoints)
- accept all `graphql-config.loadConfig()` options
- readme updates

improvement: dotenv, reload on config changes

---

packages/codemirror-graphql/src/__tests__/hint-test.js
packages/codemirror-graphql/src/hint.js

Currently `codemirror-graphql` plugin ignores the fields of an interface type and doesn't give suggestions for those fields as hints because `getSuggestionsForFieldNames` uses `isObjectType` that returns `false` for interface types.

fix(codemirror-graphql): give interface field name suggestions

---

.github/workflows/ci.yml

- update github action v1 to v2
- v2 is faster than v1 
- https://github.com/actions/checkout#whats-new

chore: update github action v1 to v2

---

.npmrc
package.json

- prevent npm command for safety
- in this repo, yarn is used. Sometimes ppl accidentally use npm instead of yarn. In order to prevent it, this PR is created.

fix: prevent npm usage

---

packages/graphiql/resources/renderExample.js
packages/graphiql/src/components/GraphiQL.tsx

fixes #1677 
This PR is to enable variable editor when the header editor is not enabled

fix: enable variable editor when header editor is not enabled

---

packages/graphql-language-service-parser/package.json

This should reduce the size of node_modules when using graphiql by quite a bit!

chore: move typescript to devDependencies

---

packages/graphiql/src/components/GraphiQL.tsx

Follow up to #1542; this passes the schema through to mergeAST so that the query can be further simplified in a type-aware way (i.e. spreading a fragment of type `Test` inside a scope that can only be type `Test` will result in the fragment being fully inlined).
Given this query:
```graphql
{
test {
id
...T
}
}
fragment T on Test {
isTest
}
```
Pressing "Merge" previously simplified to:
```graphql
{
test {
id
... on Test {
isTest
}
}
}
```
But with this change, it now simplifies to:
```graphql
{
test {
id
isTest
}
}
```

feat: deeper fragment merging

---

CONTRIBUTING.md
packages/graphql-language-service-server/src/Logger.ts
packages/graphql-language-service-server/src/MessageProcessor.ts
packages/graphql-language-service-server/src/__tests__/Logger-test.ts
packages/graphql-language-service-server/src/__tests__/MessageProcessor-test.ts
packages/graphql-language-service-server/src/startServer.ts

Don't write log messages to stdout in "stream" mode. stdout is reserved
for communicating with the LSP client in the "stream" mode. Write all
types of log messages to stderr.
Fixes LSP server crashing on the first message it receives (or maybe
LSP client closing it because it received an invalid response).
Also:
- the callback to socket.write() was always logging the "err" parameter
even if there was undefined which caused spurious lines in the
console. Only actually log that if "err" is truthy.
- Avoid too many newlines at the end of the log message as that also
causes spurious empty lines in the log and the console.
- Gracefully handle the case when the response for "workspace/configuration"
returns a null value. Those configuration options have sane defaults
and don't need to be …

fix: crash on receiving an LSP message in "stream" mode

---

packages/graphql-language-service-interface/src/getDefinition.ts

This removes the dependency on the native Node.js `assert` module. The dependency required including a polyfill for the module when bundling GraphiQL.

fix: remove assert module dependency

---

packages/graphql-language-service-server/src/__tests__/GraphQLCache-test.ts

- check if directive contains `isRepeatable` property.
The reason why https://github.com/graphql/graphiql/pull/871#issuecomment-529152156 happened is probably because it had multiple versions of `graphql` module as a dependency and the one where `isRepeatable` property wasn't contained in `GraphQLDirective` class was used in this test. Currently it has only one version of `graphql` module where `isRepeatable` property is contained in the `GraphQLDirective` class.
- replase `toMatchObject` with `toEqual` since the meanings aren't changed in those tests
and toEqual is more offen used and easier to understand.
(If you aren't familiar with the difference between `toMatchObject` and `objectContaining`,
see this:
https://stackoverflow.com/questions/45692456/whats-the-difference-between-tomatchob …

chore: cleanup test code for GraphQL cache

---

packages/graphql-language-service-interface/src/getDiagnostics.ts

don't use new deprecation rule yet, and don't restore the previous logic either. a single way to evaluate deprecation rules for now. fixes #1723

fix: dont use new deprecation rule yet

---

packages/graphql-language-service-interface/src/getDiagnostics.ts

Fix #1740 
assert is a node package that webpack 4 included automatically. 
Webpack 5 does not, so any dependency on it will bork the package.
With only a handful of uses, it doesn't make sense to add the invariant package that would minify away the messages, so we just do a quick & dirty to get it working again. can test this out by building it with webpack 5.
@acao let me know if this is what you had in mind.

use cheap invariant

---

DEVELOPMENT.md
README.md
examples/graphiql-cdn/README.md
examples/graphiql-create-react-app/README.md
examples/graphiql-parcel/README.md
examples/graphiql-webpack/README.md
examples/monaco-graphql-webpack/README.md
examples/monaco-graphql-webpack/src/index.ts
jest.config.base.js
lerna.json
package.json
packages/graphql-language-service/package.json
packages/graphql-language-service/src/LanguageService.ts
yarn.lock

- removing examples from workspaces config led to resolution errors, so we've restored that
- monaco webpack example uses github API now, using simple prompt. should replace with ouath

chore: fix and improve examples

---

packages/graphql-language-service-interface/src/__tests__/__schema__/StarWarsSchema.graphql
packages/graphql-language-service-interface/src/__tests__/getAutocompleteSuggestions-test.ts
packages/graphql-language-service-interface/src/getAutocompleteSuggestions.ts
packages/graphql-language-service-parser/src/CharacterStream.ts
packages/graphql-language-service-parser/src/Rules.ts
packages/graphql-language-service-parser/src/__tests__/OnlineParser-test.ts
packages/graphql-language-service-parser/src/__tests__/OnlineParserUtils.ts
packages/graphql-language-service-parser/src/onlineParser.ts
packages/graphql-language-service-parser/src/types.ts

This introduces a few new language features for `implements` syntax, including the new(ish) `&` operator, both for interfaces & types.
This implements support for & in the parser, which means highlighting support for codemirror graphql
Previously there was no autocompletion for any of this
```graphql
type Interface implements So▌
```
and
```graphql
type Interface implements Something & So▌
```
now we have 
it will also autocomplete for inline interfaces that may not be in the schema yet, for writing SDL files for example.
```graphql
interface Example { id: String }
type Interface implements Ex▌
```
- parser & interface
- `graphql-language-service-server`
- `vscode-graphql`
- `monaco-graphql`
- `codemirror-graphql` highlighting for & syntax works because of the parser implementation in …

feat: interfaces implementing interfaces for the LSP

---

packages/graphql-language-service-utils/package.json

Fixes the issue seen in https://github.com/backstage/backstage/issues/3961
Projects that don't use `graphql-language-service-server` may run into this issue, since that's the only package that declares the existing `nullthrows` dependency.

fix: add missing nullthrows dependency to utils

---

README.md

hey there @yoshiakis and @imolorhe, here it is as promised finally!
- [@imolorhe](https://github.com/imolorhe)
- [@yoshiakis](https://github.com/yoshiakis)
both colleauges have contributed great value to all three and now one of these repos for years. they have also helped triage issues and addressed user concerns in objective ways that demonstrate very good maintainer habits
@benjie do you want to be listed as active or not?
@brianwarner will let us know what we should do next. should i just make this into its own MAINTAINERS.md file?

docs: Add maintainers section, including new maintainers

---

packages/graphiql/src/components/GraphiQL.tsx

Fix for issue #1717 
Fire onToggleDocs, when resizing the doc explorer to a small size and finally the docExplorerOpen state is set to false.

fix: run onToggleDocs when setting docExplorerOpen to false

---

packages/graphiql/src/css/doc-explorer.css

Closes #1773 
Since using `top` can't produce the same result in different screens due to many reasons, I changed the `search-box` display to flex, and centered the icons inside it. 
let me know if you do prefer using different approach.

fix: search icon misalignment

---

packages/graphql-language-service-parser/src/__tests__/CharacterStream-test.ts
packages/graphql-language-service-parser/src/__tests__/OnlineParser-test.ts
packages/graphql-language-service-parser/src/__tests__/OnlineParserUtils.ts

Fixes #899
I couldn't reproduce the original error. It looks like there have been [more guards](https://github.com/graphql/graphiql/blob/main/packages/graphql-language-service-parser/src/onlineParser.ts#L231) added to prevent that from happening. Added a regression test nonetheless.

added regression test for state.rule bug

---

.github/workflows/license-check.yml
.github/workflows/push-pr.yml

fix the `name` properties on the workflows and some steps to even further improve visibility. 
remove codecov from cypress for now until we can instrument coverage from cypress
add a few more node versions to the unit test matrix for fun

ci: cleanup labelling for ci

---

.github/workflows/deploy-preview.yml
.github/workflows/deploy.yml
.github/workflows/push-pr.yml

This should be faster than netlify build, still get the benefits of netlify deploy, and it costs us less netlify resources, and potentially give us some more flexibility (to eventually create multiple deployments, etc)
based on example from:
https://github.com/marketplace/actions/netlify-actions#usage

ci: deploy to netlify using github actions

---

.changeset/young-bottles-taste.md
package.json
packages/codemirror-graphql/package.json
packages/graphiql-2-rfc-context/package.json
packages/graphiql-toolkit/package.json
packages/graphiql/package.json
packages/graphql-language-service-cli/package.json
packages/graphql-language-service-interface/package.json
packages/graphql-language-service-parser/package.json
packages/graphql-language-service-server/package.json
packages/graphql-language-service-types/package.json
packages/graphql-language-service-utils/package.json
packages/graphql-language-service/package.json
packages/monaco-graphql/package.json
yarn.lock

this provides more targeted peer resolutions, based on known compatibility. `graphql@14.5.0` is when built-in `graphql` types are required. the last `14.4.x` release before that also added a new method that we use.
this also limits the scope of the workspaces to monaco, so that both start commands work, and the yarn lockfile can shrink in size and duplicate resolution complexity because of create-react-app/etc in other examples
prompts for review:
1. should we add `|| experimental-defer-stream`?
2. does not adding it create peer resolution problems for consumers? webpack example should be representative of that?
3. there is a project called `manypkg` that has a `fix` command that will normalize the dependency versions of all the workspaces, preventing issues with clashing versions. it …

fix: peer resolutions, limit example workspaces

---

.changeset/two-bulldogs-doubt.md
packages/graphiql-toolkit/README.md
packages/graphiql-toolkit/docs/create-fetcher.md
packages/graphiql-toolkit/package.json
packages/graphiql-toolkit/src/create-fetcher/__tests__/buildFetcher.spec.ts
packages/graphiql-toolkit/src/create-fetcher/__tests__/lib.spec.ts
packages/graphiql-toolkit/src/create-fetcher/createFetcher.ts
packages/graphiql-toolkit/src/create-fetcher/index.ts
packages/graphiql-toolkit/src/create-fetcher/lib.ts
packages/graphiql-toolkit/src/create-fetcher/types.ts
packages/graphiql-toolkit/src/index.ts
packages/graphiql/package.json
yarn.lock

feat: createFetcher legacyClient option, simplify, docs

---

.changeset/metal-cougars-fry.md
.github/workflows/deploy-preview.yml
.github/workflows/license-check.yml
.github/workflows/push-pr.yml
packages/graphiql/src/components/GraphiQL.tsx
packages/graphiql/src/components/__tests__/GraphiQL.spec.tsx

Rendering the history panel only when it's toggled instead of using CSS to hide it.

chore: render query history panel only when it's toggled

---

.github/workflows/deploy-preview.yml
.github/workflows/deploy.yml

For now, we will avoid running CI *only* if there are changes to markdown
Too difficult to decide what else can change but won't impact CI

chore: make deploys less selective

---

.changeset/silly-scissors-bow.md
packages/graphiql-toolkit/package.json
packages/graphiql-toolkit/src/create-fetcher/lib.ts
yarn.lock

fix(ws): Subscriptions async iterator completes and better error handling

---

packages/graphiql/README.md

I found a dead link on [this README](https://github.com/graphql/graphiql/tree/main/packages/graphiql). It should be pointed one additional directory up to [here](https://github.com/graphql/graphiql/tree/main/examples/graphiql-cdn).
It's a small fix, but I figured I'd post it for others that are looking for it 👍 .

Docs: Fixing a dead link for graphiql-cdn

---

packages/graphiql/src/components/DocExplorer/MarkdownContent.tsx
packages/graphiql/test/schema.js

This PR allows url content to be rendered as clickable links in the MarkdownContent used by the DocExplorer. I updated `packages/graphiql/test/schema.js` as well to provide an example
|--------|------|
|<img width="349" alt="Screen Shot 2021-06-07 at 5 31 26 PM" src="https://user-images.githubusercontent.com/14367599/121234459-b80a5580-c861-11eb-9ad0-3e0c51a0e0fd.png">|<img width="351" alt="Screen Shot 2021-06-07 at 5 30 59 PM" src="https://user-images.githubusercontent.com/14367599/121234423-ade85700-c861-11eb-99cc-0756684d3fee.png">|
@cshaver @acao

feat: render markdown content urls as links

---

.changeset/strange-pugs-brush.md
packages/graphiql/src/index.ts

It looks like `ToolbarSelect` is exported from the index module but `ToolbarSelectOption` isn't. We are upgrading from v0.14.2 to v1.4.2 and noticed that the `GraphiQL.Select` and `GraphiQL.SelectOption` properties are no longer available and appear to be [commented out](https://github.com/graphql/graphiql/blob/65aa64811ccd40c5e8ba99edec825a91115a3c8b/packages/graphiql/src/components/GraphiQL.tsx#L692-L694). When looking at moving over to `ToolbarSelect`  it seemed like it would be better if `ToolbarSelectOption` was also exported. `ToolbarMenu`/`ToolbarMenuItem` also appears to have the same issue. 
Thanks!

feat: export ToolbarSelectOption and ToolbarMenuItem

---

.changeset/short-mirrors-occur.md
packages/graphiql/README.md
packages/graphiql/src/components/GraphiQL.tsx
packages/graphiql/src/components/QueryHistory.tsx
packages/graphiql/src/components/__tests__/GraphiQL.spec.tsx
packages/graphiql/src/utility/HistoryStore.ts

fixes: #1892 
Since the history store is inside the query history panel, it's not getting updated until we open the panel, so instead, I created a new historyStore util to manage the store.

fix: new util to manage historyStore outside of query history component

---

.changeset/three-ligers-tie.md
packages/graphiql/src/css/app.css

close #1919 
`editorTheme` option apply theme uniformly on all the codemirror instances so we can considerate that this background is specific to the graphiql theme. Other theme should be able to override correctly this color.

Fix css theme override on result window

---

README.md
packages/codemirror-graphql/README.md
packages/graphiql-2-rfc-context/README.md
packages/graphiql-toolkit/README.md
packages/graphiql/README.md
packages/graphql-language-service-interface/README.md
packages/graphql-language-service-parser/README.md
packages/graphql-language-service-server/README.md
packages/graphql-language-service-utils/README.md
packages/graphql-language-service/README.md
packages/monaco-graphql/README.md
working-group/README.md

thank you to @urigo and @benjie for leading the initiative for getting us moved over to a community graphql discord! one discord server to unite us all!
this adds links to graphiql at the root, and then to appropriate rooms for each nested readme, which will be helpful on npmjs

add discord invite links to the community graphql server

---

packages/graphiql/README.md

Fix typo in README.md. A sentence was duplicated.

Fix typo in README.md

---

.github/workflows/license-check.yml
.github/workflows/pr-check.yml
.github/workflows/pr-tests.yml

At the moment we are using `ubuntu-16.04` which is no longer supported (https://github.blog/changelog/2021-04-29-github-actions-ubuntu-16-04-lts-virtual-environment-will-be-removed-on-september-20-2021/#:~:text=April%2029%2C%202021-,GitHub%20Actions%20%3A%20Ubuntu%2016.04%20LTS%20virtual%20environment%20will%20be%20removed,Actions%20on%20September%2020%2C%202021.)

Update GitHub Actions workflow image to `ubuntu-20.04`

---

.changeset/slow-books-repeat.md
.eslintignore
.prettierignore
packages/graphql-language-service-server/src/__tests__/MessageProcessor-test.ts
packages/graphql-language-service-server/src/findGraphQLTags.ts

The `#graphql`-annotated strings weren't properly detected by the language server:
Fixes https://github.com/graphql/vscode-graphql/issues/294

Adds support for #graphql in the language server

---

.changeset/short-mirrors-occur.md

for reasons that will soon be revealed, we can only perform patch increments of `graphiql` currently
it may be worth considering reverting this PR to introduce the `feat` seperately, because otherwise it's tricky for semver

fix: patch versions only for graphiql package

---

working-group/README.md

This PR adds the correct calendar link and removes the note about meetings being on hold :)

Update WG Readme

---

js-green-licenses.json

`argparser` which is used somewhere by `markdown-it` has a Python 2.0 License which is not in the default list https://github.com/google/js-green-licenses#configurations

safelist argparser

---

.changeset/forty-apes-retire.md
packages/graphql-language-service-interface/src/getAutocompleteSuggestions.ts

`CodeMirror.Token` is identical to `ContextTokenForCodeMirror`
see https://github.com/graphql/vscode-graphql/pull/335#issuecomment-957665844
---
this will allow updating the vscode-graphql to update to the latest packages from this project without having to add codemirror as a dependency

build: remove codemirror dependency from lsp

---

.changeset/large-points-add.md
.changeset/slow-cooks-hear.md
.changeset/thirty-doors-trade.md

As mentioned in https://github.com/graphql/graphiql/pull/2010#issuecomment-962743181
- Added missing changeset for graphql-language-service-utils
- Added patch changeset for graphql-language-service-utils dependants
I also found that graphql-language-service-types was not published with the only change it had, which is adding graphql 16 in the peer dependencies:
- Added patch changeset for graphql-language-service-types
@acao

Add missing changesets

---

.changeset/config.json

Configure changesets to automatically publish internal dependents, ala #2013 
it seems that lerna publish automatically handled this, whereas changesets allows you to change packages without publishing their changes. I think this option will *force* it, even if a user removes packages from the changeset

Configure changesets to automatically publish internal dependents

---

.changeset/red-laws-argue.md
packages/codemirror-graphql/package.json
packages/codemirror-graphql/src/hint.ts
packages/codemirror-graphql/src/info.ts
packages/codemirror-graphql/src/jump.ts
packages/codemirror-graphql/src/lint.ts
packages/codemirror-graphql/src/results/mode.ts
packages/codemirror-graphql/src/utils/forEachState.ts
packages/codemirror-graphql/src/utils/getTypeInfo.ts
packages/codemirror-graphql/src/utils/runParser.ts
packages/codemirror-graphql/src/variables/__tests__/lint-test.ts
packages/codemirror-graphql/src/variables/hint.ts
packages/codemirror-graphql/src/variables/mode.ts
packages/codemirror-graphql/tsconfig.esm.json
packages/codemirror-graphql/tsconfig.json

use `graphql-language-service` instead of `graphql-language-service-utils`, etc - towards eventually combining them.
it makes it easier to manage dependency versions as well

use graphql-lang-service in codemirror-graphql

---

packages/graphiql/src/components/GraphiQL.tsx
packages/graphiql/src/components/QueryEditor.tsx
packages/graphiql/src/utility/fillLeafs.ts
packages/graphiql/src/utility/getQueryFacts.ts
packages/graphiql/src/utility/mergeAst.ts

Fixes https://github.com/graphql/graphiql/issues/2028
The `schema` prop of the GraphiQL component currently has the type `GraphQLSchema | undefined`. The correct type is `GraphQLSchema | null | undefined` because `null` is an accepted value. This PR fixes the type in the props, state and other functions that use the prop/state.

fix: schema prop type fix

---

packages/codemirror-graphql/package.json
packages/graphiql-2-rfc-context/package.json
packages/graphiql-toolkit/package.json
packages/graphiql/package.json
packages/graphql-language-service-cli/package.json
packages/graphql-language-service-interface/package.json
packages/graphql-language-service-parser/package.json
packages/graphql-language-service-server/package.json
packages/graphql-language-service-types/package.json
packages/graphql-language-service-utils/package.json
packages/graphql-language-service/package.json
packages/monaco-graphql/package.json

this should work better for consumers

fix graphql peer deps

---

.changeset/nervous-squids-flow.md
.github/workflows/canary.yml
.github/workflows/deploy-preview.yml
.github/workflows/deploy.yml
.github/workflows/license-check.yml
.github/workflows/pr-check.yml
.github/workflows/pr-tests.yml
.github/workflows/release.yml
.nvmrc
packages/graphiql/test/schema.js
yarn.lock

the node 16 upgrade seems to make yarn install about ~40s faster in github actions!

missing changeset, fix e2e, node 16

---

.changeset/grumpy-dolphins-behave.md
packages/codemirror-graphql/package.json
packages/graphiql-2-rfc-context/package.json
packages/graphiql/package.json
packages/graphql-language-service-cli/package.json
packages/graphql-language-service-interface/package.json
packages/graphql-language-service-parser/package.json
packages/graphql-language-service-server/package.json
packages/graphql-language-service-types/package.json
packages/graphql-language-service-utils/package.json
packages/graphql-language-service/package.json

Currently some build tools (**cough** react-scripts on webpack 5 **cough**) error out when trying to build source maps for the graphiql packages. This makes development much harder than it needs to be. By including the source code in the packages we build, the source maps are more likely to work...

Include source code in all packages to fix source maps.

---

.changeset/cuddly-games-protect.md
packages/graphql-language-service-server/README.md
packages/graphql-language-service-server/package.json
packages/graphql-language-service-server/src/GraphQLCache.ts
packages/graphql-language-service-server/src/Logger.ts
packages/graphql-language-service-server/src/MessageProcessor.ts
packages/graphql-language-service-server/src/__tests__/.graphqlrc.yml
packages/graphql-language-service-server/src/__tests__/Logger-test.ts
yarn.lock

this fixes the URI scheme related bugs and make sure config works
sdl first dev experience should work again
`fileURLToPath` had been introduced by a contributor and I didnt test properly, it broke sdl file loading!
i only tested with remote schemas before releasing my bad!
definitions, autocomplete, diagnostics, etc should work again
also hides the more verbose logging output for now
still the cache miss error will get that next
This should fix:
#2021 #2018 #1672 #1977 
and many others issues `vscode-graphql` repository

fix: a few major bugs with SDL and remote schema in the language server

---

.changeset/short-fireants-shake.md
packages/graphql-language-service-server/src/parseDocument.ts

There are many more extensions people are using these days for javascript so it's time to honor all of them. This *should* fix #1955 when published to `vscode-graphql`, though graphql shouldn't be trying to parse those files anyways, so a bit more digging is in order

LSP Server should parse more JS extensions

---

.changeset/fifty-actors-sleep.md
packages/graphql-language-service-server/package.json
packages/graphql-language-service-server/src/GraphQLCache.ts
packages/graphql-language-service-server/src/MessageProcessor.ts
packages/graphql-language-service-server/src/__tests__/MessageProcessor-test.ts
yarn.lock

using the standard `vscode-uri` package, this should fix the parsing of file URIs by `graphql-language-service-server` in cases such as:
- windows without WSL
- special/unicode characters in filenames 
- likely other cases
previously we were using the old approach of `URL(uri).pathname` which was not working! it was url-encoding these characters which is not helping anyone haha
also, when switching back from `fileURLToPath`, we left one case in `GraphQLCache` which may impact how the fragment and object type cache are being loaded with a global file glob. this existing feature has led users to expect fragments and objects to load magically from config without configuration and we will need to change it, but for now we will keep the magic glob from rootDir. this is set from the graphql …

fix: lsp server paths for windows, special chars, fragment/object cache

---

.changeset/green-ghosts-agree.md
packages/graphql-language-service-interface/src/__tests__/getAutocompleteSuggestions-test.ts
packages/graphql-language-service-interface/src/getAutocompleteSuggestions.ts
packages/graphql-language-service-server/src/MessageProcessor.ts
packages/graphql-language-service-types/src/index.ts
packages/monaco-graphql/src/GraphQLWorker.ts
packages/monaco-graphql/src/languageFeatures.ts
packages/monaco-graphql/src/utils.ts
yarn.lock

fixes #2068 🎉  and #1894 (i think - @rchl do you agree?)
simplifies the code a bit. untangles a mess that I left when introducing argument value completion last year.
introduces more `triggerCharacters` to `monaco-graphql` as a precursor to #1997 
fixes this bug across the entire ecosystem by fixing the issue at the core `graphql-language-service-server` level

fix: autocompletion for argument values, more trigger characters

---

.changeset/real-boxes-clap.md
packages/graphql-language-service-interface/src/GraphQLLanguageService.ts
packages/graphql-language-service-interface/src/getHoverInformation.ts
packages/graphql-language-service-server/src/MessageProcessor.ts
packages/graphql-language-service/src/LanguageService.ts

This applies to all implementations essentially. because it's opt-in for direct usage with `getAutocompleteSuggestions`, `codemirror-graphql` will be unaffected.
the lsp server, monaco-graphql and others will be able to use the markdown output
this is just the start!
where to test:
1. `monaco-graphql`
2. `graphql-language-service-server`

Add hover syntax highlighting for types

---

.changeset/smooth-elephants-eat.md
package.json
packages/graphiql/cypress/integration/docs.spec.ts
packages/graphiql/src/components/DocExplorer/FieldDoc.tsx
packages/graphiql/src/components/DocExplorer/TypeDoc.tsx
packages/graphiql/src/components/DocExplorer/__tests__/FieldDoc.spec.tsx
packages/graphiql/src/components/__tests__/DocExplorer.spec.tsx
packages/graphiql/src/components/__tests__/ExampleSchema.ts
packages/graphiql/src/utility/introspectionQueries.ts
packages/graphiql/test/schema.js

Not sure why `schemaDescription` wasn't already enabled for GraphiQL introspection queries?
Either way, this fixes the DocExplorer `schema.description` issue in #2027 when `fetcher` is provided instead of `schema` prop.
Also added support for input type `deprecationReason`

Enable schemaDescription & inputTypeDeprecation

---

.changeset/early-clouds-speak.md
package.json
packages/codemirror-graphql/src/__tests__/hint-test.ts
packages/graphql-language-service-interface/src/__tests__/getAutocompleteSuggestions-test.ts
packages/graphql-language-service-interface/src/getAutocompleteSuggestions.ts
yarn.lock

fix a potential issue where field(arg: $| in codemirror-graphql might have autocompletion insert of $\$variable because of recent changes to completion for monaco-graphql/vscode-graphql

fix: append insertText instead of variable labels

---

.changeset/weak-elephants-do.md
.github/workflows/deploy-preview.yml
packages/graphql-language-service-interface/src/__tests__/getAutocompleteSuggestions-test.ts
packages/graphql-language-service-interface/src/getAutocompleteSuggestions.ts
packages/graphql-language-service-interface/src/index.ts
packages/monaco-graphql/src/languageFeatures.ts
packages/monaco-graphql/src/utils.ts

introduces `insertText` and completion for field `selectionSets` for the appropriate `field.type`s
works across the lsp ecosystem where `insertText` is used, such as `monaco-graphql` and `graphql-language-service-server`.
though the changeset is bumping a patch for `codemirror-graphql`, `insertText` is not used by `codemirror`, and thus this will not change the `codemirror-graphql` experience.

Auto-expand selection sets & invoke completion with all fields on newline

---

.changeset/silver-trainers-double.md
packages/graphiql/resources/renderExample.js
packages/graphiql/src/components/GraphiQL.tsx
packages/graphiql/src/utility/introspectionQueries.ts

I think this will fix #2085 
provides a prop for `inputValueDeprecation` when invoking `getIntrospectionQuery()` to avoid causing issues with graphql servers who do not yet support this introspection option

fix: graphiql introspection bug with <graphql@16 servers

---

.changeset/short-toes-whisper.md
packages/graphql-language-service/package.json
yarn.lock

This PR:
https://github.com/micromatch/picomatch/pull/73
introduces browser support for `picomatch`
I created a temporary npm package as a fork of `picomatch` that includes the changes in this PR
`picomatch` works fine with CRA and other common webpack configs, but not so well with vite and some other bunders.
I can confirm that this fixes the issue in vite:
https://stackblitz.com/edit/vitejs-vite-nsepqi?file=src%2Fmain.tsx

use temporary fork of picomatch based on browser support PR

---

.changeset/fuzzy-ants-float.md
packages/monaco-graphql/src/LanguageService.ts

Introduced this slight bug with major impact to `monaco-graphql` last night whilst moving things around. 
**Actual Behavior:**
No language features appear. Schema request completes but the editor doesn't appear to load features.
**Expected behavior:**
Language features should appear
Followup:
Need a basic jest and/or cypress suite for `monaco-graphql` asap! Jest looks difficult with `monaco-editor` from what I've read

fix monaco-graphql bug with `_cacheSchemas()`

---

.changeset/orange-wombats-help.md
examples/monaco-graphql-react-vite/package.json
examples/monaco-graphql-webpack/package.json
examples/monaco-graphql-webpack/src/index.ts
packages/monaco-graphql/package.json
packages/monaco-graphql/src/languageFeatures.ts
packages/monaco-graphql/src/utils.ts
yarn.lock

We fixed this already, but I think we reverted it because folks were having issues with older versions. This makes it work for *all* versions of `monaco-editor`, how about that?

fix: monaco `getModeId` bug for `monaco-editor@^0.30.0`

---

.changeset/little-glasses-sort.md
packages/graphiql/src/components/DocExplorer/MarkdownContent.tsx
packages/graphiql/src/components/DocExplorer/__tests__/TypeDoc.spec.tsx
packages/graphiql/src/components/__tests__/ExampleSchema.ts
packages/graphiql/test/schema.js

Proposed fix to close #2137 
Issue: Line breaks do not render for descriptions in the Doc Explorer.

fix: correctly render new lines for doc explorer description fields

---

examples/graphiql-webpack/src/index.jsx

After fighting all day with cors headers because 'shouldpersistheaders' was not an allowed key, I realized that the example is wrong 🤦🏼‍♂️

fix: example uses the opts as headers

---

.changeset/ten-pianos-report.md
packages/graphql-language-service-server/src/MessageProcessor.ts
packages/graphql-language-service-server/src/__tests__/MessageProcessor-test.ts
packages/graphql-language-service-server/src/findGraphQLTags.ts
packages/graphql-language-service-server/src/parseDocument.ts

I've had vscode-graphql be un-usable for a few days because I have no idea which file is doing this on load:
```sh
[Info  - 4:06:51 PM] Connection to server got closed. Server will restart.
[Info  - 4:06:51 PM] The graphql server has stopped running
[Info  - 4:06:51 PM] The graphql server has stopped running
2/16/2022, 4:06:51 PM [3] (pid: 57218) graphql-language-service-usage-logs: {"type":"usage","messageType":"initialize"}
/Users/ortatherox/.vscode-insiders/extensions/graphql.vscode-graphql-0.3.50/out/server/server.js:99551
const err = new SyntaxError(message);
^
SyntaxError: Unexpected token, expected "," (21:7)
at Object._raise (/Users/ortatherox/.vscode-insiders/extensions/graphql.vscode-graphql-0.3.50/out/server/server.js:99551:21)
at Object.raiseWithData …
```

Adds better error messages for unparsable babel files:

---

.changeset/odd-cougars-unite.md
packages/graphql-language-service-server/package.json
yarn.lock

Who is to say if #2175 is because I'm using new TypeScript language features, in either case, this updates the babel parser to the latest version

Update babel parser in the graphql language server

---

.changeset/chilly-birds-poke.md
packages/graphql-language-service-server/src/MessageProcessor.ts

Helps folks get a bit more insight into what's going on when this error is thrown:

Improve the document cache miss error message

---

.changeset/seven-ties-march.md
packages/graphiql/src/components/GraphiQL.tsx

This is a proposal for starting the discussion on such an API.
Currently, the only way of having the schema information outside of GraphiQL is to move the logic higher up in the tree and then pass the `GraphQLSchema` instance to `GraphiQL` via the `schema` property.
Having this convenient callback simplifies accessing the schema outside the `GraphiQL` component.

feat: onSchemaChange callback

---

.changeset/orange-cups-dress.md
packages/graphiql/src/components/GraphiQL.tsx
packages/graphiql/src/css/app.css

Apply variable editor title text styles via class `variable-editor-title-text` instead of using inline-styles. This allows better customization of styles. An active element also has the class `active`. This allows overriding the inactive state color using the selector `.graphiql-container .variable-editor-title-text` and overriding the active state color using the selector `.graphiql-container .variable-editor-title-text.active`.

feat: apply variable editor title text via CSS classes instead of inline styles

---

.changeset/blue-jeans-try.md
packages/graphiql/src/components/GraphiQL.tsx

This allows inserting content such as the following:

feat: allow inserting content before the top bar

---

working-group/agendas/2022-03-08.md

As the working group happens every month per the [GraphQL Foundation Calendar](https://calendar.google.com/calendar/embed?src=linuxfoundation.org_ik79t9uuj2p32i3r203dgv5mo8@group.calendar.google.com), the next meeting is set for March 8.
Here's a proposed agenda, but of course happy to shuffle things around.
We'd like to present the new GraphiQL v2 design and discuss next steps for the implementation.

Add Working Group 9 agenda

---

.changeset/tasty-pillows-compare.md
packages/graphiql/src/components/GraphiQL.tsx

This addresses issue: https://github.com/graphql/graphiql/issues/2155
It corrects the fixes made by https://github.com/graphql/graphiql/pull/2166 and https://github.com/graphql/graphiql/pull/2167.
Those PRs changed the code to compare `typeof global` to `undefined` which would always return true, negating the effects my original PR https://github.com/graphql/graphiql/pull/2156 and not resolving the issue (I tested version 1.6.0).

fix: should not depend on 'global' global variable (#2155)

---

packages/graphiql/src/css/app.css

Added max height 100% to editor bar component
Relevant issue: https://github.com/graphql/graphiql/issues/2074

fix(variable editor): limit height of editor

---

.changeset/swift-pumpkins-sort.md
packages/graphiql/src/css/codemirror.css

Remove the [star property hack](https://stackoverflow.com/a/14927670/808699) that was for IE 5.5 to 7 from CSS of graphiql.
solve https://github.com/graphql/graphiql/issues/2211

style: remove IE7 CSS star property hack

---

packages/graphiql/src/components/QueryEditor.tsx

Updates codemirror when the `externalFragments` prop changes.
Without this change, GraphiQL must be remounted for any changes to `externalFragments` to take effect.

fix: Trigger editor update when externalFragments change

---

.changeset/rare-roses-give.md
packages/graphql-language-service-server/src/GraphQLCache.ts
packages/graphql-language-service-server/src/MessageProcessor.ts

Fixes #2212
Use `URI.file` instead of `URI.parse` to convert fs path to fileUri 
I found in some places there's the variable `filePath: Uri` which is a bit confusing because type says it's an Uri, but variable name says it's a path.

fix: fix Windows fileUri to resolve type definition

---

packages/graphql-language-service/tsconfig.esm.json

set `es6` as tsc `target`, instead of `esnext`

default to es6 target for language service, fix #2240

---

.changeset/brown-eggs-tulip.md
packages/monaco-graphql/src/workerManager.ts

In `monaco-graphql`, the language worker is creating a new instance of itself every time the config changes (schema, etc), which isn't how it should be working.
for reference, `monaco-json`'s `workerManager` does not do this, so I wonder if there is something wrong somewhere else.
I checked and made sure that the demos still worked on config changes
CC @cshaver

fix worker creation problem when changing config

---

.changeset/witty-owls-sit.md
packages/codemirror-graphql/src/utils/hintList.ts
packages/codemirror-graphql/src/utils/info-addon.ts
packages/codemirror-graphql/src/utils/jump-addon.ts
packages/codemirror-graphql/src/variables/hint.ts

this should resolve #2260. i cannot recreate the bug inside the repository for some reason so I'm not sure. the canary will appear and can be used!

fix ts path resolution, for #2260

---

.changeset/big-ads-pull.md
.eslintignore
package.json
packages/vscode-graphql/README.md
packages/vscode-graphql/package.json

I think this will publish the extension? Let's find out

finish migration, this should publish

---

.changeset/wet-bobcats-chew.md
packages/graphql-language-service-server/src/MessageProcessor.ts
packages/graphql-language-service-server/src/__tests__/MessageProcessor-test.ts
packages/graphql-language-service-server/src/startServer.ts

this might be impacting more than just vim users! #2230
we were making some assumptions about vscode default config that were not helpful to non-vscode users of the server (CLI users for example)

LSP on config change bug fixes for #2230

---

packages/graphql-language-service-server/src/MessageProcessor.ts

when the server is initialized without a graphql config present, we should warn instead of erroring. ideally, the language server should just quit, since the vast majority of features don't work without the configuration.

fix: warn with no graphql config, instead of error

---

.changeset/blue-baboons-begin.md
.eslintrc.js
packages/graphiql-toolkit/src/create-fetcher/createFetcher.ts

`typeof window !== null` **always** returns `false`

turn `valid-typeof` as `error`

---

package.json
packages/vscode-graphql/package.json
packages/vscode-graphql/yarn.lock

This sucks, we have to use an older and patched version of vsce because of yarn workspaces :/
https://github.com/microsoft/vscode-vsce/issues/300

use patched vsce

---

packages/vscode-graphql/.vscodeignore
packages/vscode-graphql/package.json

* we forgot `.vscodeignore` so the extension is publishing HUGE now
* open vsix requires full `--pat` argument now?

more vscode-graphql migration

---

.changeset/chilled-pillows-warn.md
packages/graphql-language-service/tsconfig.esm.json

I believe #2247 was supposed to fix this, but that change does not seem to be in the main branch.
Closes #2240

Update tsconfig.esm.json to not target ESNext

---

.changeset/sixty-squids-peel.md
examples/cm6-graphql-parcel/package.json
examples/cm6-graphql-parcel/src/index.ts
packages/codemirror-graphql/package.json
packages/codemirror-graphql/src/cm6-legacy/mode.ts
packages/graphiql/package.json
yarn.lock

It looks like when [CodeMirror 6 support](https://github.com/graphql/graphiql/issues/2022) was [first added](https://github.com/graphql/graphiql/pull/2035) to the `codemirror-graphql` package, `@codemirror/stream-parser` was mistakenly added as a regular dependency rather than a peer dependency (unlike the CM5 `codemirror` package).
This may lead to conflicts when upgrading upstream CM6 packages in a project that depends on this package (especially when upgrading major/minor versions) since you end up with multiple versions of core packages like `@codemirror/view` which leads to bugs. This is especially relevant as there is now a new release for each of the core CodeMirror packages ([`0.20.0`](https://discuss.codemirror.net/t/release-0-20-0/4302)).
This PR moves `@codemirror/` packages to …

fix: move @codemirror packages to peer deps, upgrade to 0.20.0

---

.changeset/wise-birds-notice.md
packages/graphql-language-service-server/src/MessageProcessor.ts
packages/graphql-language-service/src/interface/getAutocompleteSuggestions.ts

I introduced these accidentally and they have caused a lot of issues!
should fix #2376 and many others

gently trap graphql parse errors in the LS and LSP

---

babel.config.js

We had [a very strange `babel-loader` failure](https://github.com/graphql/graphiql/runs/6245830017?check_suite_focus=true#step:5:53) in a PR today, which appears to be caused by some kind of regression in an upstream babel dependency. Perhaps should consider pinning dev dependencies. When we move to vite as proposed #2371, we will be removing babel

fix babel config for webpack build

---

.changeset/perfect-teachers-repeat.md
packages/graphql-language-service-server/README.md
packages/graphql-language-service-server/src/MessageProcessor.ts

users receive duplicate validation messages when using our LSP alongside existing validation tools like `graphql-eslint`
resolves #2363 and partially solves #2309

feat: allow disabling validation (diagnostics)

---

.changeset/moody-oranges-move.md
packages/graphql-language-service-server/src/GraphQLLanguageService.ts
packages/graphql-language-service-server/src/__tests__/GraphQLLanguageService-test.ts
packages/monaco-graphql/src/GraphQLWorker.ts
packages/monaco-graphql/src/LanguageService.ts

**Current Behavior:**
The lsp server shows useless validation errors for empty graphql strings
**Expected Behavior:**
Ignore newlines and whitespace
**Details:**
the last release eliminated parse errors that would actually crash the server - these were my mistake, oops!
this fixes another annoying, non-useful parse error that is often seen when authoring a new operation
this should work in most cases, except for cases where there are only comments and no actual graphql types, but it's hard to come up with an efficient pass. this takes care of this bug, when authoring graphql and your cursor is here:
```ts
gql`|`
```
or with newlines:
```ts
gql`
|
`
```
or with whitespace & newlines:
```ts
gql`
|
`
```
or something as short as:
```ts
typ
```
where op validation doesn't need to kick in yet.

prevent display of "unexpected EOF" parser errors in diagnostics

---

.changeset/sweet-ants-knock.md
packages/graphiql/src/css/app.css

In React 18 the event handling has changed, I believe this is why in React 18 clicking on the specific arrow on the Menu results in no action (whereas clicking the rest of the button works fine). This is easily solved with the `pointer-events: none` CSS trick for the SVG as used elsewhere.

fix(css): use pointer-events:none on Menu dropdown SVG

---

.changeset/twelve-dogs-report.md
packages/graphiql-2-rfc-context/src/types/index.ts
packages/graphiql-toolkit/src/create-fetcher/createFetcher.ts
packages/graphiql-toolkit/src/create-fetcher/lib.ts
packages/graphiql-toolkit/src/create-fetcher/types.ts
packages/graphiql/src/components/GraphiQL.tsx

`operationName` can be null, or can be not specified at all; however our TypeScript types mark it as required. This tiny PR fixes that.

fix(toolkit): operationName is optional

---

.changeset/happy-kangaroos-taste.md
packages/vscode-graphql/package.json

This gets `vscode-graphql` publishing properly in concert with `changesets`.
When the workspace is marked `private: true`, we can't expect `postpublish` to fire, but `postversion` should!

fix vscode publishing with changesets

---

.eslintrc.js
examples/graphiql-webpack/src/index.jsx
packages/graphiql-2-rfc-context/src/components/DocExplorer.tsx
packages/graphiql-2-rfc-context/src/components/DocExplorer/FieldDoc.tsx
packages/graphiql-2-rfc-context/src/components/DocExplorer/SchemaDoc.tsx
packages/graphiql-2-rfc-context/src/components/DocExplorer/SearchResults.tsx
packages/graphiql-2-rfc-context/src/components/DocExplorer/TypeDoc.tsx
packages/graphiql-2-rfc-context/src/components/DocExplorer/TypeLink.tsx
packages/graphiql-2-rfc-context/src/components/GraphiQL.tsx
packages/graphiql-2-rfc-context/src/components/__tests__/GraphiQL.spec.tsx
packages/graphiql-2-rfc-context/src/components/common/Layout.stories.tsx
packages/graphiql-2-rfc-context/src/components/common/List/List.stories.tsx
packages/graphiql-2-rfc-context/src/components/common/Nav.stories.tsx
packages/graphiql-2-rfc-context/src/components/common/Resizer/Resizer.stories.tsx
packages/graphiql-2-rfc-context/src/components/common/Toolbar/Tabs.stories.tsx
packages/graphiql-2-rfc-context/src/components/common/Toolbar/Toolbar.stories.tsx
packages/graphiql-2-rfc-context/src/components/common/Type.stories.tsx
packages/graphiql/src/components/DocExplorer.tsx
packages/graphiql/src/components/DocExplorer/Directive.tsx
packages/graphiql/src/components/DocExplorer/FieldDoc.tsx
packages/graphiql/src/components/DocExplorer/SchemaDoc.tsx
packages/graphiql/src/components/DocExplorer/SearchResults.tsx
packages/graphiql/src/components/DocExplorer/TypeDoc.tsx
packages/graphiql/src/components/DocExplorer/TypeLink.tsx
packages/graphiql/src/components/GraphiQL.tsx
packages/graphiql/src/components/QueryHistory.tsx
packages/graphiql/src/components/Tabs.tsx
packages/graphiql/src/components/__tests__/GraphiQL.spec.tsx

It's anti-practice in React as it's unnecessary JSX expressions and provokes confusing

enable `react/jsx-curly-brace-presence` rule and remove `react/jsx-no-literals` rule

---

.changeset/hungry-colts-raise.md
examples/graphiql-webpack/package.json
yarn.lock

I added a bad changeset in #2397 that contained ignored packages. This currently breaks the `release` workflow: https://github.com/graphql/graphiql/runs/6395880044?check_suite_focus=true
I also changed the dependencies in the webpack example to avoid the warnings printed above the error.

fix bad changeset and avoid warnings

---

.changeset/rude-singers-tap.md
.changeset/wise-maps-divide.md
packages/graphiql-toolkit/src/async-helpers/index.ts
packages/graphiql-toolkit/src/create-fetcher/types.ts
packages/graphiql-toolkit/src/format/index.ts
packages/graphiql-toolkit/src/index.ts
packages/graphiql/src/components/GraphiQL.tsx

In particular we move over:
- Async helper functions (promises, observables and async-iterables)
- Formatting functions for result JSON and errors
I also noticed that the `shouldPersistHeaders` property that is part of the fetcher options is never used for anything, and after searching through issues and commit history I found no good reason why they should be in there. (@acao maybe I'm lacking context here?) This PR deprecates it and intends to remove it in the next major version of `graphiql`.

move more reusable logic into toolkit package

---

.changeset/slimy-tips-sort.md
.changeset/slow-sloths-suffer.md
package.json
packages/graphiql-react/.eslintrc
packages/graphiql-react/.gitignore
packages/graphiql-react/package.json
packages/graphiql-react/src/explorer.tsx
packages/graphiql-react/src/index.ts
packages/graphiql-react/src/vite-env.d.ts
packages/graphiql-react/tsconfig.json
packages/graphiql-react/tsconfig.node.json
packages/graphiql-react/vite.config.ts
packages/graphiql/package.json
packages/graphiql/src/components/DocExplorer.tsx
packages/graphiql/src/components/DocExplorer/DefaultValue.tsx
packages/graphiql/src/components/DocExplorer/FieldDoc.tsx
packages/graphiql/src/components/DocExplorer/TypeDoc.tsx
packages/graphiql/src/components/DocExplorer/types.ts
packages/graphiql/src/components/GraphiQL.tsx
packages/graphiql/src/components/QueryEditor.tsx
packages/graphiql/src/components/__tests__/DocExplorer.spec.tsx
yarn.lock

This PR adds a new package `@graphiql/react` to the monorepo. The idea for this package is to provide all the building blocks (context providers, hooks to work with the state managed by the context, reusable components, etc.) for building a GraphiQL-like UI. The main `graphiql` package will become the reference implementation for how to use the components from `@graphiql/react`.
As a first step towards this goal, we add the following to the new package:
- A React context `ExplorerContext` that shall contain all the state and logic related to the docs/explorer. We wrap with in a component `ExplorerContextProvider` that has to be rendered at the top of the tree that contains other GraphiQL-components that need to access or change this state.
- For easy access in functional components we …

feat: add `@graphiql/react` package

---

.changeset/four-mangos-warn.md
packages/graphiql-toolkit/src/create-fetcher/__tests__/lib.spec.ts
packages/graphiql-toolkit/src/create-fetcher/lib.ts

Moving `graphql-ws` to a dynamic import and display a nice message when not found

---

.changeset/witty-papayas-remain.md
packages/graphiql/src/components/GraphiQL.tsx

The logic for persisting headers in tabs was exactly switched, i.e. we stripped headers when `shouldPersistHeaders` was `true`. This also caused GraphiQL to open duplicate tabs when the `headers` prop was used: #2380

fix persisting headers in tab state

---

.github/workflows/canary.yml
.github/workflows/release.yml
yarn.lock

- canary release can use normal `GITHUB_TOKEN`
- release step only uses `GH_TOKEN` for creating PRs
- add environment tokens for publishing the vscode extensions
- lockfile change from last cleanup PR

cleanup - token usage in actions

---

.changeset/tough-jobs-shave.md
.changeset/warm-kings-rhyme.md
packages/graphiql-react/src/editor/completion.ts
packages/graphiql-react/src/editor/header-editor.tsx
packages/graphiql-react/src/editor/hooks.ts
packages/graphiql-react/src/editor/query-editor.tsx
packages/graphiql-react/src/editor/variable-editor.tsx
packages/graphiql-react/src/explorer.tsx
packages/graphiql/package.json
packages/graphiql/src/components/DocExplorer.tsx
packages/graphiql/src/components/GraphiQL.tsx

In addition we can now also move the logic for clicking references to get to the docs into `@graphiql/react`, that way we don't need to pass the `onClickReference` and `onHintInformationRender` props to the editors anymore.

move state for doc explorer visibility to explorer context in `@graphiql/react`

---

.changeset/mean-trees-work.md
packages/graphiql-react/src/schema/context.tsx

Fixes #2441 
We only start introspecting when there is no schema provided via props. When `null` is passed we also don't introspect and run GraphiQL without schema. We also make sure to avoid race conditions between prop changes (that also update the state) and the async introspection request, i.e. if the state changed between starting and resolving the introspection request, we don't override the state with the new schema.

don't introspect the schema if it's provided via props

---

packages/graphiql/src/components/GraphiQL.tsx

since this method is private, no need to changesets
also fixed other typos in this file

rename handleTabClickProp`o`gation() to handleTabClickProp`a`gation

---

.changeset/friendly-cougars-happen.md
packages/graphiql-react/src/editor/context.tsx
packages/graphiql-react/src/editor/header-editor.tsx
packages/graphiql-react/src/editor/query-editor.tsx
packages/graphiql-react/src/editor/variable-editor.tsx
packages/graphiql-react/src/schema.tsx
packages/graphiql/__mocks__/@graphiql/react.ts
packages/graphiql/src/components/GraphiQL.tsx

Fixes #2442 
After introducing the schema context, we might dispatch introspection queries after the initial one that don't use the latest header values, but the initial ones. This PR fixes this:
- We derive the initial editor values in the `EditorContextProvider` and also expose them on the context value. The editor hooks don't need to do this logic anymore and can just consume the initial value from the context.
- Also syncing the prop value with the editor state (i.e. the calls to `useSynchronizeValue`) have been moved to the `EditorContextProvider`, that way we only need to pass the `defaultQuery`, `query`, `variables`, and `headers` prop to the context provider and not also the editor hooks.
- We consume the editor context inside the `SchemaContextProvider` to make sure that we use …

always use the latest header values for introspection

---

packages/graphiql-react/src/execution.tsx

I messed this up in #2453 (which is not published yet), there is no global try-catch anymore, so we need to avoid throwing early.

show proper error when headers or variables are invalid json

---

scripts/canary-release.js

messy PRs lead to silent failures in github actions leads to sleepy tooling 😴 
this should make canary releases happy again

i broke the canary release script! 😬

---

.changeset/tidy-ghosts-happen.md
.vscode/settings.json
package.json
packages/graphql-language-service-server/src/GraphQLCache.ts
packages/graphql-language-service-server/src/MessageProcessor.ts
packages/graphql-language-service/src/types.ts
scripts/prepublish.sh

Aims to resolve #2421
- graphql config errors only log to output channel, no longer crash the LSP
- improve readability, add a helpful link for users
- more performant LSP request no-ops for failing/missing config
this used to fail silently in the output channel, but vscode introduced a new retry and notification for this. in previous versions of vscode, the server exited non-0, but this didn't cause notifications for the user. this should introduce bugfixes and improvements for non-vscode users of the LSP server as well.
would like to provide more helpful graphql config DX in the future but this should be better for now.
if your LSP server cli implementation needs a non-zero exit for missing/invalid lsp config, let me know and we can add a feature to enable a non-zero failure on config …

don't crash lsp server on graphql config errors

---

.changeset/sharp-bags-appear.md
packages/vscode-graphql/README.md
packages/vscode-graphql/grammars/graphql.js.json
packages/vscode-graphql/package.json

At least a partial fix for #2356, enables highlighting for template strings with typescript type parameters
Borrowed from https://github.com/apollographql/vscode-graphql/blob/main/syntaxes/graphql.js.json
Also casually bump the version for vscode-graphql once since 0.4.9 is released already from my local, so 0.4.10 becomes the next resolution we want.
This is not the most ideal way of accomplishing this, but I couldn't get it working with a single pattern

Ensure highlighting works with typescript type parameters

---

.changeset/chilly-geese-dress.md
packages/graphiql/src/components/GraphiQL.tsx

Fixes #2466 
As proposed in the issue, we wrap the current exported `GraphiQL` component with yet another class component to roll-back the breaking change introduced with 1.9.0 while keeping the new contexts for state management. It's ugly, but we can drop this with the upcoming v2 major release.

make exported GraphiQL component a class again

---

.changeset/violet-peaches-compete.md
package.json
packages/graphql-language-service-server/src/MessageProcessor.ts
scripts/prepublish.sh

I also made a change to the LSP server to make sure we see releases in tandem.
It removes dotenv from the LSP server itself, as the docs now reccomend requiring it in-file

run release script if specified for non npm releases

---

.changeset/itchy-bananas-wink.md
packages/graphql-language-service-server/src/GraphQLLanguageService.ts
packages/graphql-language-service-server/src/MessageProcessor.ts
packages/graphql-language-service-server/src/__tests__/GraphQLLanguageService-test.ts
packages/graphql-language-service/src/index.ts
packages/graphql-language-service/src/interface/getDefinition.ts

Related to #2472 
- Goto definition for operation fields
https://user-images.githubusercontent.com/6255130/172580684-b8831b99-7021-41bb-8fa8-ad60184ca162.mp4

feature: add definition support for operation fields

---

.eslintrc.js
examples/graphiql-2-rfc-context/src/workers/graphql.worker.ts
packages/monaco-graphql/src/graphql.worker.ts

Why:
1. this rule is included in the default `eslint:recommended` config
2. just rethrowing an error in the catch block is redundant and confusing

apply fixes for ESLint `no-useless-catch` rule

---

examples/cm6-graphql-parcel/package.json
examples/graphiql-2-rfc-context/package.json
examples/graphiql-parcel/package.json
examples/monaco-graphql-webpack/package.json
package.json
packages/codemirror-graphql/src/utils/jsonParse.ts
packages/codemirror-graphql/src/variables/lint.ts
packages/graphiql-react/src/history/context.tsx
packages/graphiql/package.json
packages/graphiql/src/components/QueryHistory.tsx
packages/graphiql/src/components/ToolbarButton.tsx
packages/graphql-language-service-cli/src/cli.ts
packages/graphql-language-service-cli/src/client.ts
packages/graphql-language-service-server/src/GraphQLLanguageService.ts
packages/graphql-language-service-server/src/MessageProcessor.ts
packages/graphql-language-service-server/src/findGraphQLTags.ts
packages/graphql-language-service-server/src/startServer.ts
packages/graphql-language-service/package.json
packages/graphql-language-service/src/interface/getDiagnostics.ts
packages/graphql-language-service/src/parser/Rules.ts
yarn.lock

GraphQL.js 17 requires TypeScript >= 4.4; This is a base PR for a stacked GraphQL v17 update PR.

chore: use the same TypeScript version throughout the monorepository

---

.changeset/short-gifts-heal.md
packages/graphiql-react/src/editor/header-editor.tsx
packages/graphiql-react/src/editor/hooks.ts
packages/graphiql-react/src/editor/query-editor.tsx
packages/graphiql-react/src/editor/variable-editor.tsx
packages/graphiql-react/src/execution.tsx

For users of `@graphiql/react` we want to make clear which hook or component is missing which context provider. We achieve this by forwarding the function that was called by the user via `caller` attributes to the editor consumers that require a certain context to be present.
We are already doing this for lots of places, just in some this was missing (which is my oversight 😅 ), so this is just a tiny usability fix.

add missing `caller` arguments

---

packages/graphiql-react/src/editor/style/codemirror.css
packages/graphiql/src/css/app.css

Following up on #2528, setting the editor background to white by default works for query, variable, and header editors, but it's not the right default for the response editor. This PR addresses that by adding a new CSS variable `--editor-background` that allows to define the background for a specific editor. The default is still white.

set default background colors via css variables

---

packages/graphiql-react/src/editor/components/header-editor.tsx
packages/graphiql-react/src/editor/components/query-editor.tsx
packages/graphiql-react/src/editor/components/response-editor.tsx
packages/graphiql-react/src/editor/components/variable-editor.tsx
packages/graphiql-react/src/editor/style/editor.css
packages/graphiql/src/style.css

Tiny fix: Moving over some styles that are specific to the editor component to `@graphiql/react`

move editor styles to `@graphiql/react`

---

packages/codemirror-graphql/package.json
packages/graphiql-react/README.md
packages/graphiql-react/package.json
packages/graphiql-toolkit/README.md
packages/graphiql/package.json
packages/graphql-language-service-cli/package.json
packages/graphql-language-service-server/README.md
packages/graphql-language-service-server/package.json
packages/graphql-language-service/README.md
packages/graphql-language-service/package.json
packages/monaco-graphql/README.md
packages/vscode-graphql/README.md

the absolute links are for npm and other repo mirrors of course
can't wait to improve our typedoc output and use it in a proper docs website soon!
the gatsby docs site experiment I did about 2 years ago is a good starting point, the branch is somewhere, but there are many approaches we can look at. graphql dot org was being rebuilt with gatsby at the time so I figured so should we. whatever folks are comfortable using is fine

clean up repository references, more readmes and links

---

.changeset/three-rice-matter.md
custom-words.txt
package.json
packages/graphql-language-service-server/src/__tests__/MessageProcessor-test.ts
packages/graphql-language-service-server/src/__tests__/findGraphQLTags-test.ts
packages/graphql-language-service-server/src/findGraphQLTags.ts
packages/vscode-graphql/grammars/graphql.js.json

This PR enables highlight & intellisense on common `gql()` calls without need to add a `#graphql` tag or equivalent.
Before:
After:

feat: add gql call expressions support

---

packages/graphql-language-service-server/src/__tests__/GraphQLCache-test.ts
packages/graphql-language-service-server/src/__tests__/findGraphQLTags-test.ts

another boring incremental improvement PR 😆 
- re-enable some tests for GraphQLCache that were disabled after an update to `graphql-config` after I found a proper mocking workaround
- add more tests for cases in `findGraphQLTags.ts` as a follow up to #2509

add more tests for findGraphQLTags, fix cache/schema tests

---

packages/graphiql-react/src/editor/components/header-editor.tsx
packages/graphiql-react/src/editor/components/variable-editor.tsx
packages/graphiql/src/components/GraphiQL.tsx

A small quality-of-life improvement: Currently you have to "manually" refresh the codemirror editor after hiding and then again showing an editor, in particular the `GraphiQL` component does this for the variable- and header-editors. This PR moves the logic into the editor components exported from `@graphiql/react`.

refresh editor after hiding

---

packages/graphiql-react/src/editor/components/header-editor.tsx
packages/graphiql-react/src/editor/components/query-editor.tsx
packages/graphiql-react/src/editor/components/response-editor.tsx
packages/graphiql-react/src/editor/components/variable-editor.tsx
packages/graphiql-react/src/editor/header-editor.tsx
packages/graphiql-react/src/editor/query-editor.tsx
packages/graphiql-react/src/editor/response-editor.tsx
packages/graphiql-react/src/editor/variable-editor.tsx

Small quality-of-life improvement: When rendering an editor component without the necessary context, the error message will now blame the component instead of the hook.

add caller argument to editor hooks

---

.changeset/flat-humans-attend.md
.changeset/warm-weeks-allow.md
packages/graphiql-react/src/schema.tsx
packages/graphiql/src/components/GraphiQL.tsx

Fixes #2503 
This broke when we introduced the `SchemaContextProvider` from `@graphiql/react` in v1.9.3 (see #2420)

fix the `onSchemaChange` prop

---

packages/graphiql/src/components/GraphiQL.tsx
packages/graphiql/src/components/__tests__/GraphiQL.spec.tsx
packages/graphiql/src/css/app.css
packages/graphiql/src/style.css

Quick one: This fixes the layout for the custom footer that is displayed beneath the response editor. As there is none in the preview, here's the visual diff:
| --- | --- |
| <img width="822" alt="CleanShot 2022-07-04 at 17 55 33@2x" src="https://user-images.githubusercontent.com/22288634/177188700-3cacfaec-b595-4add-84d5-c709d5969d00.png"> | <img width="822" alt="CleanShot 2022-07-04 at 17 55 50@2x" src="https://user-images.githubusercontent.com/22288634/177188706-f6882de4-f7d9-4746-81b5-0e8c84a8558a.png"> |
Note: No changeset here, we already have one for the redesign in #2523

[redesign] footer

---

.changeset/tame-owls-wink.md
packages/graphiql-react/src/editor/common.ts

Fixes #2368 
This should fix breaking imports of `@graphiql/react` (or its dependent `graphiql`) in non-browser environments like Node.js. Remix for example breaks during SSR because these imports also get loaded and executed. `codemirror` assumes to always run in a browser env though.

avoid top-level dynamic codemirror imports

---

cspell.json

Fixes #2551. I think?
These don't need to be spellchecked because they are generated files. The source markdown files already are covered by cspell when added to .changeset

Permanently fix cspell + changeset bug

---

.changeset/dual-poems-call.md
custom-words.txt
packages/graphql-language-service-server/package.json
yarn.lock

Re-creating the PR created by user @xuanduc987

fix the lsp cli for vim users

---

.changeset/chatty-insects-poke.md
packages/graphql-language-service-cli/src/cli.ts
packages/graphql-language-service-server/package.json
packages/graphql-language-service-server/src/MessageProcessor.ts
packages/graphql-language-service-server/src/startServer.ts
packages/graphql-language-service/package.json
packages/graphql-language-service/src/interface/__tests__/getAutocompleteSuggestions-test.ts
packages/graphql-language-service/src/interface/getAutocompleteSuggestions.ts
packages/graphql-language-service/src/types.ts
packages/monaco-graphql/package.json
packages/vscode-graphql/package.json
packages/vscode-graphql/src/apis/statusBar.ts
packages/vscode-graphql/src/extension.ts
yarn.lock

upgrades the `vscode-languageserver` and `vscode-jsonrpc` reference implementations for the lsp server. also upgrades `vscode-languageclient` in `vscode-graphql` to 8. seems to work fine for IPC in `vscode-graphql` at least!
hopefully this solves #2230 once and for all!

upgrade vscode-languageserver

---

.changeset/wild-wasps-retire.md
packages/graphiql-react/src/editor/header-editor.tsx
packages/graphiql-react/src/editor/query-editor.tsx
packages/graphiql-react/src/editor/variable-editor.tsx

Follow-up on #2501, we forgot to add the `keyMap` prop as effect dep.

add missing effect deps for `keyMap` prop

---

packages/vscode-graphql/README.md

fix vscode readme md link to the LSP Server configuration docs

fix link typo in `vscode-graphql` readme

---

.changeset/nine-elephants-retire.md
.changeset/nine-eyes-relax.md
.changeset/serious-ties-compete.md
packages/graphiql-react/src/schema.tsx
packages/graphiql/src/components/GraphiQL.tsx

This is a small QoL improvement: The `schema` prop now also accepts introspection data as an alternative to a `GraphQLSchema` instance. Also, this fixes a bug where the schema was not updated after rerunning introspection.
We had a use-case for this feature at Stellate: We store introspection data for different endpoints, and we want to use this to render GraphiQL on the client without running introspection (because this is likely to be disabled for lots of production APIs). We'd now have to add `graphql` as first-class dependency just to call `buildClientSchema` once. With this tiny change the `SchemaContextProvider` does that for us, which is a lot nicer DX.
💡 Reviewing with whitespace turned off halves the LOCs!

feat(graphiql): pass introspection data to `schema` prop

---

packages/graphiql-react/src/editor/completion.ts
packages/graphiql-react/src/editor/header-editor.tsx
packages/graphiql-react/src/editor/hooks.ts
packages/graphiql-react/src/editor/query-editor.tsx
packages/graphiql-react/src/editor/variable-editor.tsx
packages/graphiql/src/components/GraphiQL.tsx

Clicking on the type name in the hint tooltip is currently broken because we don't toggle the doc explorer container that is using the drag-resizing utility.

fix opening doc explorer when clicking references

---

examples/graphiql-2-rfc-context/package.json
jest.config.base.js
package.json
yarn.lock

Did a quick run through, and this is all stuff that we don't use anywhere for sure.
@acao not sure why we had the jest environment packages installed explicitly, they seem to already come via transitive dependencies of `jest` itself.

[housekeeping] remove unused shared dependencies

---

.changeset/five-pillows-fail.md
.changeset/ninety-pumpkins-reflect.md
packages/graphiql-react/src/explorer/components/search.css
packages/graphiql-react/src/index.ts
packages/graphiql-react/src/style/root.css
packages/graphiql-react/src/theme.ts
packages/graphiql-react/src/toolbar/execute.css
packages/graphiql-react/src/ui/button-group.css
packages/graphiql-react/src/ui/button-group.tsx
packages/graphiql-react/src/ui/index.ts
packages/graphiql/__mocks__/@graphiql/react.tsx
packages/graphiql/src/components/GraphiQL.tsx
packages/graphiql/src/style.css

FINALLY 🌚 🌚 🌚 
This PR adds a dark theme. By default GraphiQL chooses the preferred system color scheme. In any case the theme can explicitly be chosen in the settings dialog.

[redesign] add dark mode

---

README.md

Living up to his username, @jonathanawesome has done an awesome job helping @thomasheyenbrock, and I would like him to be able to triage tickets and approve @thomasheyenbrock's PRs for the 2.0 rewrite branch, and if he would like, the ability to approve PRs to `main`.
Passionate about graphiql user experience, he has built fantastic prototypes, and like Thomas and others, has spent countless hours in the issue queues, chat histories and beyond to gain a deeper understanding of what a user-driven roadmap looks like for graphiql.
What's more, @thomasheyenbrock tells me he would be delighted to have him as a co-maintainer.

Proposing @jonathanawesome as a maintainer

---

packages/graphiql-react/src/editor/style/codemirror.css

These styles went missing when reworking the editors, now the editor search shows up again in new glory.

add back styles for editor search

---

.changeset/pre.json

put `graphql-language-service-server` into `@next` tag pre-release mode, but leave `vscode-graphql` stable and also depending on stable `graphql-language-service-server`.
workspaces support will come with some optimizations and some rewrites that we want to fine tune and test first

pre release for lsp

---

.changeset/pre.json

Reverting pre-release state for LSP temporarily while we get a vscode-graphql stable release out with the new syntax extension

Revert pre-release state

---

packages/graphql-language-service-server/src/GraphQLLanguageService.ts
packages/vscode-graphql-syntax/CHANGELOG.md
packages/vscode-graphql/README.md

this keeps happening ope just this adding `private: true` here
also, cleanup markdown

the syntax extension keeps trying to publish to npm!

---

.changeset/green-mayflies-notice.md
packages/graphiql-react/src/style/root.css
packages/graphiql/src/components/GraphiQL.tsx
packages/graphiql/src/style.css

This adds a dialog that shows all the current short keys.

add a dialog that shows all available shortkeys

---

.changeset/curly-poets-pump.md
packages/vscode-graphql-syntax/package.json

If a `.graphql` or `.gql` file is not found in `includes` or `documents` it seems to cause a warning sometimes when handled by the message processor, but in the language service, a missing project for a graphql file seems to actually crash the server.  This appeared to fix the issue in the case where I could reproduce it.
This error is completely unnecessary! I don't know why we ever showed it. It seems I added it by accident during the typescript migration.
for now, when schema information isn't present we just no-op. eventually I would like to offer a lot more schemaless features, in new major versions of the language services where we refactor the interfaces

changeset & publishing fix for LSP bugfix

---

.changeset/shy-parents-bow.md
.changeset/wild-rings-leave.md
packages/graphiql-react/src/schema.tsx
packages/graphiql/src/components/DocExplorer/__tests__/TypeDoc.spec.tsx
packages/graphiql/src/components/GraphiQL.tsx
packages/graphiql/src/components/__tests__/DocExplorer.spec.tsx
packages/vscode-graphql-syntax/CHANGELOG.md

This PR add a function that contains the logic for running introspection to the schema context from `@graphiql/react`. It also adds a toolbar button and a short key that can be used to trigger this.
(After the refactoring that we did this turned out to be super simple, so I figured we can as well to another minor to push this out in 1.x.)
https://user-images.githubusercontent.com/22288634/182157907-8884b42a-fabd-4508-a306-a31c565e2ad1.mp4

manually re-trigger introspection

---

packages/graphiql-react/src/explorer/components/doc-explorer.css
packages/graphiql-react/src/explorer/components/field-link.css
packages/graphiql-react/src/explorer/components/type-link.css
packages/graphiql-react/src/index.ts
packages/graphiql-react/src/style/root.css

Fixes #2629
In fact, this is set of fixes for the doc explorer:
- The issue obviously, i.e. fixing the selector specificity and making sure to load the `root.css` file first.
- Making sure the headline in the docs is hidden only when the search input is focussed, in particular not hiding it when focussing the back-link
- Making sure the outlines of focussed links match the design colors.

fix doc explorer style regressions

---

.changeset/thirty-grapes-pay.md
packages/graphiql-react/src/execution.tsx
packages/graphiql-react/src/schema.tsx
packages/graphiql-toolkit/src/create-fetcher/lib.ts
packages/graphiql-toolkit/src/format/index.ts
packages/graphiql/cypress/integration/errors.spec.ts
packages/graphiql/cypress/integration/graphqlWs.spec.ts
packages/graphiql/cypress/integration/incrementalDelivery.spec.ts
packages/graphiql/cypress/integration/init.spec.ts
packages/graphiql/cypress/support/commands.ts
packages/graphiql/resources/renderExample.js
packages/graphiql/test/e2e-server.js
yarn.lock

Fixes #2534
The issue is caused by the default ws-fetcher which wraps joins multiple error messages and wraps them in a new error.
Open TODOs:

fix error display for websocket fetchers

---

packages/graphiql-react/src/editor/style/auto-insertion.css
packages/graphiql-react/src/editor/style/codemirror.css
packages/graphiql-react/src/editor/style/fold.css
packages/graphiql-react/src/editor/style/hint.css
packages/graphiql-react/src/editor/style/info.css
packages/graphiql-react/src/editor/style/lint.css
packages/graphiql-react/src/explorer/components/argument.css
packages/graphiql-react/src/explorer/components/default-value.css
packages/graphiql-react/src/explorer/components/deprecation-reason.css
packages/graphiql-react/src/explorer/components/directive.css
packages/graphiql-react/src/explorer/components/doc-explorer.css
packages/graphiql-react/src/explorer/components/field-link.css
packages/graphiql-react/src/explorer/components/schema-documentation.css
packages/graphiql-react/src/explorer/components/search.css
packages/graphiql-react/src/explorer/components/type-documentation.css
packages/graphiql-react/src/explorer/components/type-link.css
packages/graphiql-react/src/history/style.css
packages/graphiql-react/src/style/root.css
packages/graphiql-react/src/toolbar/button.css
packages/graphiql-react/src/toolbar/execute.css
packages/graphiql-react/src/ui/button-group.css
packages/graphiql-react/src/ui/button.css
packages/graphiql-react/src/ui/dialog.css
packages/graphiql-react/src/ui/markdown.css
packages/graphiql-react/src/ui/menu.css
packages/graphiql-react/src/ui/spinner.css
packages/graphiql-react/src/ui/tabs.css
packages/graphiql/src/style.css

Inspired by #2635, this is a proposal for how we can prepare v2 so that adding a theme prop down the road won't be a breaking change.
The main idea is to move the color conversion (non-transparent to transparent) into CSS instead of doing it in JS. We achieve this by storing the HSL values as list in the CSS variables. To applying a color we can then just do `hsl(var(--color-pink)`. To apply a transparent shade of a color we can do `hsla(var(--color-pink), 0.15)`.
This reduces the number of CSS variables that users need to care about when creating their custom theme, and it should align nicely with the idea of @jonathanawesome to have a theme prop like this in future versions:
```jsx
<GraphiQL theme={{ colors: { primary: "<some-color>" } }} />
```

use hsl values and reduce number of CSS variables

---

.changeset/afraid-kiwis-notice.md
packages/graphiql-react/src/editor/context.tsx
packages/graphiql-react/src/editor/header-editor.tsx
packages/graphiql-react/src/editor/query-editor.tsx
packages/graphiql-react/src/editor/tabs.ts
packages/graphiql-react/src/execution.tsx
packages/graphiql-react/src/schema.tsx
packages/graphiql/src/components/GraphiQL.tsx

In the midst of some final cleanup for v2 I noticed that after the initial refactoring there are some props which are now "duplicated" in some places. In particular:
- `externalFragments` was passed separately to `ExecutionContextProvider` and `QueryEditor`
- `shouldPersistHeaders` was passed separately to `EditorContextProvider`, `ExecutionContextProvider` and `HeaderEditor`
This makes it possible to have somewhat inconsistent state. This PR attempts to clean this up by only passing these two props to `EditorContextProvider` (semantically it makes the most sense to have it there). The provider component includes the props in the context value, so they can be consumed by other parts of the UI.
I also did the same for `validationRules` even though it was only passed to one component …

[@graphiql/react] deduplicate props

---

packages/graphiql-react/src/editor/style/auto-insertion.css
packages/graphiql-react/src/editor/style/codemirror.css
packages/graphiql-react/src/editor/style/fold.css
packages/graphiql-react/src/editor/style/hint.css
packages/graphiql-react/src/editor/style/lint.css
packages/graphiql-react/src/explorer/components/argument.css
packages/graphiql-react/src/explorer/components/default-value.css
packages/graphiql-react/src/explorer/components/deprecation-reason.css
packages/graphiql-react/src/explorer/components/directive.css
packages/graphiql-react/src/explorer/components/doc-explorer.css
packages/graphiql-react/src/explorer/components/field-link.css
packages/graphiql-react/src/explorer/components/schema-documentation.css
packages/graphiql-react/src/explorer/components/search.css
packages/graphiql-react/src/explorer/components/type-documentation.css
packages/graphiql-react/src/explorer/components/type-link.css
packages/graphiql-react/src/history/style.css
packages/graphiql-react/src/style/root.css
packages/graphiql-react/src/toolbar/button.css
packages/graphiql-react/src/toolbar/execute.css
packages/graphiql-react/src/ui/button.css
packages/graphiql-react/src/ui/markdown.css

Following up on #2637, this renames our CSS variables for colors as proposed by @jonathanawesome in #2635.

rename CSS variables for colors

---

packages/graphiql-react/src/toolbar/button.tsx
packages/graphiql-react/src/ui/button-group.tsx
packages/graphiql-react/src/ui/button.tsx
packages/graphiql-react/src/ui/dialog.tsx
packages/graphiql-react/src/ui/markdown.tsx
packages/graphiql-react/src/ui/spinner.tsx
packages/graphiql-react/src/ui/tabs.tsx

I think this is a best-practice for simple UI component: All "native" props for the element that is being rendered (often times it's the only one) are now passed to that component. We also wrap the components with `forwardRef` so that users can access the DOM elements returned from these components.

forward refs and props for UI components

---

.changeset/eight-poems-call.md
.changeset/five-carrots-learn.md
.changeset/mean-peas-rush.md
packages/graphiql-react/src/editor/context.tsx
packages/graphiql-react/src/editor/query-editor.tsx
packages/graphiql-react/src/execution.tsx
packages/graphiql/resources/renderExample.js
packages/graphiql/src/components/ExecuteButton.tsx
packages/graphiql/src/components/GraphiQL.tsx

Currently the `operationName` and `onEditOperationName` props do not really work. I can't trace back exactly when this was introduced, but it's likely that it's again a bug introduced when we started pulling stuff out into `@graphiql/react`.
Now it should work as expected:
- The `operationName` prop controls the operation name sent with the request when executing. It does not check if there actually exists an operation with this name, this has to be done in userland. When this prop is set, the `ExecutionButton` skips showing the dropdown if there are multiple operations.
- The `onEditOperationName` prop is now triggered whenever the operation name is changed. That includes
- when changing the operation name in the query editor
- when executing a different operation from the same document …

fix operation name props

---

.changeset/silly-squids-cheat.md
packages/graphiql-react/src/editor/context.tsx
packages/graphiql-react/src/editor/hooks.ts
packages/graphiql-react/src/editor/response-editor.tsx
packages/graphiql/src/components/GraphiQL.tsx

Noticed this little inconsistency where we passed the value props for all editors *except* the response editor to the context provider. This PR cleans that up, now all editor value props are passed to the `EditorContextProvider`.

move response editor value prop to context provider

---

packages/graphiql/__mocks__/@graphiql/react.ts

I noticed that there are some type errors in the file where we mock editor hooks and components for our unit tests. This PR fixes these.

fix type errors in mocked editors

---

.prettierrc

Follow up to #2648, this cleans up the config and removes settings that are deprecated of mirror the default value.

remove deprecated and default prettier config options

---

.changeset/famous-dragons-confess.md
packages/graphiql-react/src/execution.tsx
packages/graphiql/src/components/ExecuteButton.tsx

This property is only meant for internal use. In order to know if a request is in-flight there is the `isFetching` property. In order to stop a running subscription there is the `stop` method.

remove `subscription` property from `ExecutionContext`

---

.changeset/famous-dragons-confess.md
.changeset/quick-pumas-fly.md
packages/graphiql-react/src/editor/response-editor.tsx
packages/graphiql-react/src/schema.tsx
packages/graphiql/src/components/DocExplorer.tsx
packages/graphiql/src/components/DocExplorer/__tests__/TypeDoc.spec.tsx
packages/graphiql/src/components/__tests__/DocExplorer.spec.tsx

Spotted more stuff that should not be exposed on contexts. This time we actually did not use it anyways.

remove methods from `SchemaContext` meant for internal use

---

custom-words.txt
package.json
packages/graphql-language-service-server/package.json
packages/graphql-language-service/package.json
packages/vscode-graphql/esbuild.js
yarn.lock

Hiya 👋  This is likely somewhat incomplete, as I'm really only focusing on fixing VSCode. If there's more to do for other packages, let me know!
This PR bumps `ts-node` to 10.x, so that TypeScript based configs (i.e. `.graphqlrc.ts`) will continue to work. It also bumps to the latest patch releases of `graphql-config` fixed several issues with TypeScript loading ([v4.3.2](https://github.com/kamilkisiela/graphql-config/releases/tag/v4.3.2), [v4.3.3](https://github.com/kamilkisiela/graphql-config/releases/tag/v4.3.3)).
Before this upgrade, the following appeared in my logs:
```8/10/2022, 9:23:24 PM [1] (pid: 8154) graphql-language-service-usage-logs: WARNING: graphql-config error, only highlighting is enabled:
Failed to compile TypeScript: Debug Failure. False expression: Non-string value …
```

Fix TypeScript GraphQL config file loading.

---

.changeset/six-yaks-heal.md
custom-words.txt
package.json
packages/graphql-language-service-server/package.json
packages/graphql-language-service/package.json
packages/vscode-graphql/esbuild.js
yarn.lock

Reverts the bugfix graphql/graphiql#2658 to fix #2662, a repeat of the bug from last week that it seemed #2658 had introduced. This will break things for `graphql.config.ts` users again, but make the extension work for more users again

Revert "Fix TypeScript GraphQL config file loading."

---

.github/workflows/canary.yml
.github/workflows/license-check.yml
.github/workflows/pr-check.yml
.github/workflows/pr-graphql-compat-check.yml
.github/workflows/pr-tests.yml
.github/workflows/release.yml
packages/graphql-language-service-server/package.json
packages/graphql-language-service-server/src/__tests__/GraphQLCache-test.ts
yarn.lock

because it's good for the earth 🌍 and the patience of contributors 😆 
i wish you could use `paths-ignore` further down, to skip individual tasks
note:
i decided to upgrade `actions/setup-node` usage as well for similar reasons, it appears to be faster but brings some bugs, so i will finish this up tonight

reduce CO2 usage by running less unneccesary GH actions workflows

---

.changeset/chilly-radios-tap.md
custom-words.txt
packages/graphiql-react/README.md
packages/graphiql-react/package.json
packages/graphiql-react/src/editor/components/header-editor.tsx
packages/graphiql-react/src/editor/components/variable-editor.tsx
packages/graphiql-react/src/editor/context.tsx
packages/graphiql-react/src/editor/hooks.ts
packages/graphiql-react/src/editor/index.ts
packages/graphiql-react/src/editor/query-editor.tsx
packages/graphiql-react/src/editor/variable-editor.tsx
packages/graphiql-react/src/execution.tsx
packages/graphiql-react/src/explorer/components/argument.tsx
packages/graphiql-react/src/explorer/components/default-value.tsx
packages/graphiql-react/src/explorer/components/deprecation-reason.tsx
packages/graphiql-react/src/explorer/components/directive.tsx
packages/graphiql-react/src/explorer/components/doc-explorer.tsx
packages/graphiql-react/src/explorer/components/field-documentation.tsx
packages/graphiql-react/src/explorer/components/field-link.tsx
packages/graphiql-react/src/explorer/components/schema-documentation.tsx
packages/graphiql-react/src/explorer/components/section.tsx
packages/graphiql-react/src/explorer/components/type-documentation.tsx
packages/graphiql-react/src/explorer/components/type-link.tsx
packages/graphiql-react/src/explorer/context.tsx
packages/graphiql-react/src/history/context.tsx
packages/graphiql-react/src/index.ts
packages/graphiql-react/src/schema.tsx
packages/graphiql-react/src/utility/resize.tsx
packages/graphiql/__mocks__/@graphiql/react.tsx
packages/graphiql/src/components/GraphiQL.tsx

This adds some more documentation in the simplest form possible: JSDoc comments :D Those should also be picked up by typedoc and enhance the docs we generate and push to Netlify already.
TODOs:

add documention for `@graphiql/react`

---

.changeset/chatty-timers-heal.md
.changeset/smart-cats-marry.md
.eslintrc.js
.vscode/launch.json
examples/monaco-graphql-webpack/babel.config.js
examples/monaco-graphql-webpack/src/editors.ts
examples/monaco-graphql-webpack/src/index.html.ejs
examples/monaco-graphql-webpack/src/index.ts
examples/monaco-graphql-webpack/src/schema.ts
examples/monaco-graphql-webpack/src/style.css
packages/codemirror-graphql/src/__tests__/hint-test.ts
packages/graphiql-toolkit/src/create-fetcher/lib.ts
packages/graphql-language-service-server/src/GraphQLLanguageService.ts
packages/graphql-language-service/src/interface/__tests__/__schema__/StarWarsSchema.graphql
packages/graphql-language-service/src/interface/__tests__/getAutocompleteSuggestions-test.ts
packages/graphql-language-service/src/interface/getAutocompleteSuggestions.ts
packages/graphql-language-service/src/parser/Rules.ts
packages/graphql-language-service/src/parser/types.ts
packages/monaco-graphql/src/LanguageService.ts
packages/monaco-graphql/src/languageFeatures.ts

When editing type system definitions, the autocomplete suggestions aren't super helpful (and kinda hard not to accidentally trigger at the top-level of the document):
In this PR I've updated one of the examples (so I could play with this behavior) to have an editor for the SDL that gets loaded in, which is applied to the query editor upon editing (I've added `fakeField` in the screenshot):
<details><summary>🖼 Screenshot of modified example</summary><img src="https://user-images.githubusercontent.com/2136754/183768056-c911ac13-da30-4ba8-8cfb-ffc9740a0ee0.png" width="1792" alt="" /></details>
And I've added some autocomplete suggestions for the right keywords at the top-level, plus keywords that go after `extend`:
<details>
<summary>🖼 Gif </summary><img …

[language-services] Improve autocomplete suggestions when editing type system definitions

---

packages/graphiql-react/src/editor/style/hint.css
packages/graphiql-react/src/editor/style/info.css
packages/graphiql-react/src/editor/style/lint.css
packages/graphiql-react/src/explorer/components/search.css
packages/graphiql-react/src/style/root.css
packages/graphiql-react/src/ui/dialog.css
packages/graphiql-react/src/ui/dropdown.css
packages/graphiql-react/src/ui/tooltip.css

A quick fix for popover styles (tooltips, dialogs, etc) in the dark theme. Box shadows only really work with a light theme, in a dark theme the subtle contrast is barely noticeable. This PR removes the box shadow in the dark theme and instead applies a light border around the popover.
| --- | --- |
| <img width="1282" alt="CleanShot 2022-08-20 at 11 55 50@2x" src="https://user-images.githubusercontent.com/22288634/185740261-632615a4-eda3-4f2f-ae31-45d4d6a658f6.png"> | <img width="1286" alt="CleanShot 2022-08-20 at 11 57 14@2x" src="https://user-images.githubusercontent.com/22288634/185740307-6220ab9c-c70f-430d-a68a-e4d3153f25d4.png"> |
| <img width="351" alt="CleanShot 2022-08-20 at 11 56 03@2x" src="https://user-images.githubusercontent.com/22288634/185740262-80d51234-b …

[v2] make popover styles look good in dark mode

---

custom-words.txt
examples/graphiql-explorer/.eslintrc
examples/graphiql-explorer/.gitignore
examples/graphiql-explorer/index.html
examples/graphiql-explorer/package.json
examples/graphiql-explorer/src/App.tsx
examples/graphiql-explorer/src/customArgs.ts
examples/graphiql-explorer/src/graphiql-explorer.d.ts
examples/graphiql-explorer/src/index.css
examples/graphiql-explorer/src/main.tsx
examples/graphiql-explorer/src/vite-env.d.ts
examples/graphiql-explorer/tsconfig.json
examples/graphiql-explorer/tsconfig.node.json
examples/graphiql-explorer/vite.config.ts
examples/monaco-graphql-react-vite/package.json
package.json
yarn.lock

This adds an example for how to add the popular [`graphiql-explorer`](https://github.com/OneGraph/graphiql-explorer) as plugin in GraphiQL v2. There's some additional styling thrown in to make it blend in with the new design, I'm pretty happy with the looks for the minimal amount of style overrides one needs to pass in. Eventually it would be awesome if `graphiql-explorer` follows suit and adapts its default design to match the new GraphiQL design. But for now this should give folks something that is useable.
I deployed a preview at https://graphiql-explorer-thomasheyenbrock.vercel.app/

add example for `graphiql-explorer`

---

.changeset/ninety-tips-thank.md
packages/graphiql-react/src/execution.tsx
packages/graphiql-toolkit/src/create-fetcher/__tests__/buildFetcher.spec.ts
packages/graphiql-toolkit/src/create-fetcher/types.ts

This has been deprecated for a while now. If users are interested in this value they can look it up in the `EditorContext` instead.

don't pass `shouldPersistHeaders` to fetcher anymore

---

.github/workflows/canary.yml
.github/workflows/license-check.yml
.github/workflows/pr-check.yml
.github/workflows/pr-graphql-compat-check.yml
.github/workflows/pr-tests.yml
.github/workflows/release.yml

This fixes a regressions around publishing canary versions for PRs that might have come in with #2626. I also switched back to Node 16 for now as some parts of the build are not working properly.

fix publishing canary versions from PRs

---

.changeset/wise-pans-hear.md
packages/graphiql/src/components/GraphiQL.tsx

This should fix #2698, it looks like that when there are headers in localstorage we try to access `isHeadersEditorEnabled` before it is instantiated 😊

Instantiate `isHeadersEditorEnabled` early

---

examples/graphiql-cdn/index.html

Overlooked this when initially renaming the prop

fix props in the CDN example

---

.changeset/healthy-cougars-sell.md
packages/graphiql-react/src/editor/context.tsx
packages/graphiql-react/src/editor/tabs.ts

Fixes #2380 
I refactored the code a bit so that the computation of the initial editor values and the initial tabs happen at the same place. To avoid any inconsistencies we now store the tab state directly after deriving it in the initial render.

fix initial state computation to avoid duplicate tabs

---

.changeset/eight-wombats-refuse.md
.changeset/sweet-tomatoes-protect.md
packages/graphiql-react/src/editor/style/editor.css
packages/graphiql-react/src/explorer/components/doc-explorer.css

This fixes two small issues:
- Make sure that invisible editors are hidden off screen so they don't cause overflow that makes scrollbars visible. (Can happen depending on how you define the height of the container element.)
- Properly hide the back link and the title when focussing the search field in the docs. (Currently the back link stays visible because the background of the input field is a transparent color.)

fix minor style issues

---

examples/graphiql-cdn/index.html

The current `graphQLFetcher` in the example doesn't support headers. But it seems easier to just use `createFetcher`?

chore: use `createFetcher` in CDN example

---

.changeset/tricky-seas-flash.md
packages/graphiql-plugin-explorer/CHANGELOG.md
packages/graphiql-plugin-explorer/package.json

I forgot to remove the `private` field from the `package.json` after moving the explorer plugin code from an example to a package in #2715. This fixes that and reverts the version so that CI will hopefully publish it in the next run.

make `@graphiql/plugin-explorer` package public

---

.changeset/friendly-seals-develop.md
packages/graphiql-plugin-explorer/src/graphiql-explorer.d.ts
packages/graphiql-plugin-explorer/src/index.tsx

I've imported _graphiql-explorer.d.ts_ so the types for `graphiql-explorer` are visible in user projects and I've solved the _ts(8020)_ JSDoc type error in it — probably a leftover of some Flow code?
Closes https://github.com/graphql/graphiql/issues/2730 and https://github.com/graphql/graphiql/issues/2729.

[plugin-explorer] Fix an error in `graphiql-explorer.d.ts` and import it in `types/index.d.ts`

---

.changeset/modern-queens-compare.md
packages/graphiql-toolkit/src/create-fetcher/createFetcher.ts

Fixes #2721
Avoid throwing an error in the fetcher if there is no document AST. This can happen when the query string is empty, it just contains comments or when there is a syntax error. In any case, we always want to actually send the request to the server and let the final parsing and validation take place there.

fix throwing an error inside the fetcher when there is no AST

---

.changeset/fuzzy-seahorses-exist.md
packages/graphiql-plugin-explorer/package.json

Oversight from my end, the peer dependency versions should be more loose and align with the ones we declare for the other packages.

fix peer dependency versions

---

.changeset/cool-zebras-grow.md
.changeset/thin-hairs-thank.md
packages/graphiql-react/src/toolbar/execute.css
packages/graphiql-react/src/ui/button-group.css
packages/graphiql-react/src/ui/button.css
packages/graphiql/src/components/GraphiQL.tsx
packages/graphiql/src/components/__tests__/GraphiQL.spec.tsx
packages/graphiql/src/style.css

Following up on https://github.com/graphql/graphiql/discussions/2216#discussioncomment-3508021, this adds hover styles to all the buttons.
https://user-images.githubusercontent.com/22288634/188168413-db95acb7-7d96-4f76-bf6a-d6628d4f64bc.mp4

add hover styles for buttons

---

.changeset/calm-falcons-arrive.md
packages/graphiql-plugin-explorer/package.json

Specify `MIT` `license` in `package.json` for the new `graphiql-explorer` plugin so that it passes our own and user checks!

package.json license field for graphiql-explorer

---

.changeset/pink-weeks-fetch.md
packages/graphiql/src/style.css

Fixes #2743. I left a code comment that explains why we need these styles.

avoid CodeMirror overlapping with other parts of the UI

---

.changeset/poor-kiwis-divide.md
packages/graphiql-plugin-explorer/README.md
packages/graphiql-plugin-explorer/package.json

Otherwise changeset will always use [a major version bump](https://github.com/changesets/changesets/blob/main/docs/decisions.md) for the explorer plugin package when we change anything about `@graphiql/react`. It's also easier when installing the plugin as package.

make `@graphiql/react` a real dependency instead of a peer dependency

---

.changeset/quick-bulldogs-impress.md
packages/graphiql-toolkit/src/async-helpers/index.ts

Ran into this when trying to reproduce an issue. Passing `null` values into these functions caused them to throw.

correctly handle `null` when type-guarding promises and observables

---

.changeset/dull-bulldogs-bow.md
packages/graphiql-toolkit/README.md
packages/graphiql-toolkit/docs/create-fetcher.md
packages/graphiql-toolkit/package.json

Fixes #2322
It's only conditionally imported when the fetcher needs to support subscriptions. I also did some editorial changes for the docs and README of the toolkit package.

make `graphql-ws` an optional peer dependency

---

.changeset/fair-gifts-smell.md
.changeset/sweet-terms-fold.md
packages/graphiql-plugin-explorer/src/index.css
packages/graphiql-plugin-explorer/src/index.tsx
packages/graphiql-react/src/editor/style/auto-insertion.css
packages/graphiql-react/src/editor/style/codemirror.css
packages/graphiql-react/src/editor/style/fold.css
packages/graphiql-react/src/editor/style/hint.css
packages/graphiql-react/src/editor/style/info.css
packages/graphiql-react/src/explorer/components/argument.css
packages/graphiql-react/src/explorer/components/deprecation-reason.css
packages/graphiql-react/src/explorer/components/doc-explorer.css
packages/graphiql-react/src/explorer/components/search.css
packages/graphiql-react/src/history/style.css
packages/graphiql-react/src/style/root.css
packages/graphiql-react/src/toolbar/button.css
packages/graphiql-react/src/ui/button-group.css
packages/graphiql-react/src/ui/button.css
packages/graphiql-react/src/ui/dialog.css
packages/graphiql-react/src/ui/dropdown.css
packages/graphiql-react/src/ui/markdown.css
packages/graphiql-react/src/ui/spinner.css
packages/graphiql-react/src/ui/tabs.css
packages/graphiql/src/style.css

This refactoring is a preparation for iterating over the color contrasts. Currently we always define the alpha values inline, so we can't ensure consistency and we have to change a bunch of files if we'd ever like to change one of these values. These set of variables should help with that (in fact this will help with a PR I'm gonna open later today 😜 )

add CSS variables for color shades

---

.changeset/violet-mangos-explain.md
packages/graphiql-plugin-explorer/src/index.tsx
packages/graphiql-react/src/editor/style/codemirror.css

[It was noted](https://twitter.com/alexey_rodionov/status/1567227215234072576) that we use the same colors for field and argument names in the explorer plugin. This stems from the colors we chose for the editor theme. To avoid using the same color in the explorer and also keep it consistent with the editor theme, we update the color for argument names. (I double-checked that this introduces no "color conflicts" where we would show two different adjacent tokens in the same color.)

use different colors for field names and argument names

---

packages/graphiql-react/src/editor/style/codemirror.css
packages/graphiql-react/src/style/root.css
packages/graphiql/src/style.css

This tries to improve the color contrasts for GraphiQL:
- Increasing the alpha for secondary and tertiary neutral colors
- Adding the box shadow from the design around the main editor card
- Using a yellow color for matching brackets
| --- | --- |
| ![CleanShot 2022-09-02 at 17 39 29@2x](https://user-images.githubusercontent.com/22288634/188190245-3487028a-f54b-4dc7-b4da-5215972dcaec.png) | ![CleanShot 2022-09-02 at 17 37 37@2x](https://user-images.githubusercontent.com/22288634/188190329-dcc162d1-3d60-4b9b-9bbd-48c4e8d83564.png) |
| ![CleanShot 2022-09-02 at 17 39 18@2x](https://user-images.githubusercontent.com/22288634/188190305-4cfe523c-8e77-4e82-bf44-4966e1fe76c0.png) | ![CleanShot 2022-09-02 at 17 38 35@2x](https://user-images.githubusercontent.com/22288634/1881903 …

better color contrasts

---

.changeset/twenty-walls-drive.md
packages/graphiql-toolkit/src/storage/base.ts

only remove namespaced items when clearing `localStorage`

---

.changeset/late-queens-visit.md
packages/graphiql-toolkit/src/create-fetcher/createFetcher.ts
packages/graphiql-toolkit/src/create-fetcher/lib.ts

Fixes #2181 
This matches the behavior of graphql-playground by allowing to use `Headers` to configure the payload of the `connection_init` frame.

feat: pass subscription Headers as connection_init payload

---

.changeset/friendly-flies-battle.md
packages/graphiql-react/src/schema.tsx
packages/graphiql/src/components/__tests__/GraphiQL.spec.tsx

If you construct a `GraphiQL` instance with a bad fetcher `fetchError` gets persisted in `SchemaContextType` forever. You can still fetch a new schema but the `DocExplorer` will always show "Error fetching schema"

fix: fix fetchError persisting across different fetchers

---

docs/migration/graphiql-2.0.0.md

There doesn't seem to be a `usePrettifyQuery` export; I assume `usePrettifyEditors` was what was intended?

docs: fix usePrettifyQuery -> usePrettifyEditors

---

.changeset/tricky-glasses-try.md
packages/graphiql-react/src/explorer/components/__tests__/doc-explorer.spec.tsx
packages/graphiql-react/src/style/root.css
packages/graphiql-react/src/toolbar/button.css
packages/graphiql-react/src/vite-env.d.ts
packages/graphiql/src/components/GraphiQL.tsx
packages/graphiql/src/components/__tests__/GraphiQL.spec.tsx
packages/graphiql/src/style.css

This PR address the issues described in #2777 by adding the well-known box model reset to all children of the container into which we render GraphiQL.
A new class and associated styles are added to contain the sidebar controls, and adjustments are made to the toolbar button css to fit the new box model.

Simple box model reset

---

.changeset/selfish-terms-sing.md
packages/graphiql-react/src/editor/style/info.css

| --- | --- |
| <img width="428" alt="CleanShot 2022-10-05 at 12 32 49@2x" src="https://user-images.githubusercontent.com/22288634/194042487-579f6746-f3f9-4d81-bef4-4b48bca9b242.png"> | <img width="424" alt="CleanShot 2022-10-05 at 12 32 34@2x" src="https://user-images.githubusercontent.com/22288634/194042490-36bf1fc4-8c30-4a65-888b-75af47f5be2f.png"> |

fix(@graphiql/react): show info overlay over scrollbar

---

packages/graphiql-react/package.json
packages/graphiql-toolkit/package.json
packages/graphql-language-service-server/package.json
packages/graphql-language-service/package.json

The existing bug tracker links reference labels which no longer exist in this repository.

fix: update bug tracker links

---

.github/workflows/pr-graphql-compat-check.yml
.github/workflows/release.yml

This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …

GitHub Workflows security hardening

---

.github/workflows/pr-graphql-compat-check.yml
.github/workflows/release.yml

Reverts graphql/graphiql#2769 which breaks the release workflow (it prevents a git push)

Revert "GitHub Workflows security hardening"

---

.changeset/thick-years-sort.md
packages/graphql-language-service-server/src/MessageProcessor.ts
packages/graphql-language-service-server/src/WorkspaceMessageProcessor.ts
packages/graphql-language-service-server/src/__tests__/MessageProcessor-test.ts
packages/vscode-graphql/package.json

A true revert-revert thanks to my shoegun merge 😆 
thank you @Foo-x for your patience and understanding, not to mention your contributions!
reverts the revert PR graphql/graphiql#2612

Introduce multi-root workspaces support

---

packages/graphql-language-service-server/src/MessageProcessor.ts
packages/graphql-language-service-server/src/WorkspaceMessageProcessor.ts
packages/graphql-language-service-server/src/__tests__/GraphQLCache-test.ts
packages/graphql-language-service-server/src/__tests__/MessageProcessor-test.ts

Massive optimization for multi-project users!
Warning: this changes the cache lifecycle a lot, especially after config change. Might need some fine tuning 😆
I should add lots of tests actually.
`WorkspaceMessageProcessor._updateGraphQLConfig()` becomes `_loadAndCacheProjectConfig(projectName: string)`, which has grown up and become more discerning and instead of re-building all project config caches, we just load the project config it needs to handle that event, of course! What a poor design of mine before.
Because of this, the cache invalidation strategy on configuration and settings changes must change, and also allow project caches to lazily load as needed.

Initialize the project cache more selectively

---

.changeset/eight-rockets-run.md
packages/vscode-graphql-execution/package.json
yarn.lock

use `workspaces.nohoist` to ensure the workspace has everything we need to bundle `node_modules` with `vsce`!
I had too many issues with `esbuild` and the exec extension, so I had to opt out from bundling, but it's not to bad if we keep `nohoist` in check I guess?

use nohoist in exec extension

---

.changeset/sweet-peaches-tap.md
packages/vscode-graphql/package.json

so many `vsce` unknowns, lets just skip his for now...
until I can figure out how to bundle `graphql.vscode-graphql-execution` with `vsce` in a yarn monorepo context! worked fine before outside of the monorepo.

disable exec for now until vsce issues are resolved

---

.changeset/twelve-peas-study.md
packages/graphql-language-service-server/src/MessageProcessor.ts
packages/graphql-language-service-server/src/WorkspaceMessageProcessor.ts
packages/graphql-language-service-server/src/__tests__/GraphQLCache-test.ts
packages/graphql-language-service-server/src/__tests__/MessageProcessor-test.ts

Revert "Initialize the project cache more selectively"

---

.changeset/happy-cherries-add.md
packages/graphiql-react/src/index.ts
packages/graphiql/__mocks__/@graphiql/react.tsx

Any other ContextProvider are exposed, with exception PluginContextProvider.
So in my opinion https://github.com/graphql/graphiql/pull/2674 only miss this expose

expose PluginContextProvider

---

packages/codemirror-graphql/src/variables/lint.ts

At least variable section do a big red warning for missing values of field with a default value, 
this intend to silence that.

Support Default values in lint variables

---

README.md

Cristina (@cshaver) began helping with `monaco-graphql` and `graphiql` in late 2019 or 2020, providing some of the implementation that's in both `@graphiql/react` and `monaco-graphql` today. She has also helped with issue triage in the past.
She would like to help us advance`monaco-graphql` and `graphiql` and `@graphiql/react`. Her eye for a11y and both DX and UX will help so much!

Add Cristina Shaver as co-maintainer

---

.changeset/calm-poets-invite.md
.changeset/curly-guests-heal.md

Forgot this detail in your pr @imolorhe my bad! Otherwise there won't be a release. We don't use conventional commits anymore, we use atlassian changesets now.
This will attribute the mode to me now in the changelog which is unfortunate. Do you want to re-create this PR yourself so it gives you credit? It will still link just to the changeset commit, and not the PR where you added this mode, but you can link to that from the changelog entry at least!

add missing changeset for cm6-graphql

---

.changeset/great-mayflies-camp.md
packages/graphql-language-service-server/src/parseDocument.ts
packages/vscode-graphql/src/apis/statusBar.ts
packages/vscode-graphql/src/extension.ts

Fixes #2857
The LSP server wasn't registered for svelte files.
Note: the PR does not have tests

[vscode-graphql] fix Svelte support

---

.changeset/spicy-ducks-fail.md
packages/vscode-graphql-syntax/README.md

huge typo. caused this user bug https://github.com/graphql/graphiql/issues/2843#issuecomment-1294685543

docs: typo - `/* GraphQL */` not `/* GraphiQL */`!

---

.changeset/khaki-otters-brush.md
custom-words.txt
packages/graphql-language-service-server/src/GraphQLLanguageService.ts
packages/graphql-language-service/src/interface/__tests__/getAutocompleteSuggestions-test.ts
packages/graphql-language-service/src/interface/getAutocompleteSuggestions.ts
packages/monaco-graphql/README.md
packages/monaco-graphql/src/LanguageService.ts
packages/monaco-graphql/src/api.ts
packages/monaco-graphql/src/typings/index.ts
packages/monaco-graphql/src/workerManager.ts

Users found this generally annoying by default, especially when there are required arguments
Fixes https://github.com/graphql/graphiql/issues/2121
Without automatically prompting autocompletion of required arguments as well as lead expansion, it makes the extension harder to use
You can now supply this in your graphql config:
`config.extensions.languageService.fillLeafsOnComplete`
Setting it to to `true` will enable this feature.
Will soon add the ability to manually enable this in `monaco-graphql` as well.
For both, this kind of behavior would be better as a keyboard command, context menu item &/or codelens prompt. We could even re-create the graphiql behavior for this, where after choosing an autocomplete item, `CMD` + `return` will automatically fill leaf fields

Disable`fillLeafsOnComplete` by default

---

.changeset/olive-tips-deliver.md
packages/graphiql-react/src/editor/__tests__/tabs.spec.ts
packages/graphiql-react/src/editor/context.tsx
packages/graphiql-react/src/editor/tabs.ts
packages/graphiql-react/src/provider.tsx
packages/graphiql/src/components/GraphiQL.tsx
packages/graphiql/src/components/__tests__/GraphiQL.spec.tsx

Initial tabs

---

.changeset/moody-moose-sin.md
packages/cm6-graphql/src/lint.ts

fix: fixed "Mark decorations may not be empty"  error in codemirror 6 lint extension.

fix: fixed "Mark decorations may not be empty"  error

---

package.json

The wall of text while running tests is a stack trace via Jest, which is unusable as a stack trace because it's all minified/transformed code. This PR adds the [--noStackTrace](https://jestjs.io/docs/cli#--nostacktrace) CLI option to remove the wall of text.

removes stack trace from Jest output

---

.changeset/sweet-papayas-run.md
packages/graphiql-react/src/editor/context.tsx
packages/graphiql-react/src/editor/tabs.ts
packages/graphiql-react/src/provider.tsx
packages/graphiql/cypress/integration/headers.spec.ts
packages/graphiql/resources/renderExample.js
packages/graphiql/src/components/GraphiQL.tsx

fixes https://github.com/dotansimha/graphql-yoga/issues/1163

feat(graphiql/@graphiql/react): add `defaultHeaders` prop + e2e tests

---

.eslintrc.js
examples/monaco-graphql-webpack/src/index.ts
packages/graphiql-toolkit/src/create-fetcher/lib.ts
packages/graphql-language-service-server/src/GraphQLCache.ts
packages/graphql-language-service-server/src/Logger.ts
packages/monaco-graphql/src/GraphQLWorker.ts
packages/monaco-graphql/src/LanguageService.ts
packages/monaco-graphql/src/languageFeatures.ts
packages/monaco-graphql/src/workerManager.ts
packages/vscode-graphql-execution/src/extension.ts
packages/vscode-graphql/src/extension.ts
packages/vscode-graphql/src/server/index.ts

explicitly disable them with `eslint-disable-next-line`

change severity of `no-console` rule to `error` to clean up eslint output

---

.changeset/forty-pens-obey.md
packages/graphiql-plugin-code-exporter/README.md

chore(@graphiql/plugin-code-exporter): Fix Typo

---

.changeset/poor-vans-kiss.md
packages/graphiql-react/src/toolbar/execute.tsx

If you have multiple operations defined in the editor, clicking the execute button will show a dropdown to choose which operation to run.
If an operation is running, the stop button still shows the dropdown. Since only one operation can be running at any point in time, showing the dropdown is useless. This merge request makes sure that the dropdown is only shown, if no operation is currently running

Do not show dropdown for execute button if an operation is currently running

---

.changeset/silver-planets-pay.md
packages/graphql-language-service-server/src/MessageProcessor.ts

reload on legacy config file change

---

package.json
packages/graphiql-react/package.json
packages/graphiql-react/src/explorer/components/__tests__/field-documentation.spec.tsx
packages/graphiql-react/src/explorer/components/__tests__/type-documentation.spec.tsx
packages/graphiql-react/src/explorer/components/__tests__/type-link.spec.tsx
packages/graphiql-react/src/history/__tests__/components.spec.tsx
packages/graphiql/package.json
packages/graphiql/src/components/__tests__/GraphiQL.spec.tsx
yarn.lock

This PR removes the act() warnings we've been experiencing with tests. Apologies for the lack of more precise commits, turned out there were additional issues that I discovered while updating the tests that just need to be fixed in place. These included updating tests that tested _no longer used_ props and removing the ts-nocheck comment and fixing up the TS bits.
I've also updated the testing-library packages to the nearest allowed version with our React 17 requirement.
There are still two `no-op` errors in the output that, based on [this](https://github.com/facebook/react/pull/22114) Facebook PR, are likely false positives. These errors have been removed in React 18 but won't be back-ported to React 17.
Resolves #2892

Fix react testling library context errors

---

.changeset/fresh-readers-walk.md
packages/graphiql-react/src/editor/completion.ts
packages/graphiql-react/src/editor/style/hint.css

This broke when we introduced `box-sizing: border-box` as default.
| --- | --- |
| ![CleanShot 2022-11-15 at 12 29 49](https://user-images.githubusercontent.com/22288634/201909465-20154b31-f69c-4a85-b275-477b303280f4.gif) | ![CleanShot 2022-11-15 at 12 29 11](https://user-images.githubusercontent.com/22288634/201909475-b14c6dd5-ab0f-4a66-abbe-21a90c083a62.gif) |

fix autocomplete popover styles

---

.changeset/chilly-weeks-invent.md
packages/graphiql/src/components/GraphiQL.tsx
packages/graphiql/src/style.css

Noticed that there were some broken styles:
- One of the variables was shown as active (bold color) even when no editor was visible
- The chevron in the toggle button was not visible
| --- | --- |
| <img width="582" alt="CleanShot 2022-11-15 at 12 42 12@2x" src="https://user-images.githubusercontent.com/22288634/201911727-b2a44af4-ba48-4573-954a-8d3828780366.png"> | <img width="578" alt="CleanShot 2022-11-15 at 12 41 51@2x" src="https://user-images.githubusercontent.com/22288634/201911764-33d45c8b-403a-40c9-92a9-1939272cb24a.png"> |
| <img width="577" alt="CleanShot 2022-11-15 at 12 42 19@2x" src="https://user-images.githubusercontent.com/22288634/201911797-7bfde38c-9d8e-4146-8299-08989a03f16f.png"> | <img width="578" alt="CleanShot 2022-11-15 at 12 41 58@2x" …

fix styles of secondary editor buttons

---

.changeset/red-ligers-scream.md
packages/graphiql-react/src/editor/context.tsx

Following up on https://github.com/graphql/graphiql/pull/2886, this adds a missing effect dependency so that updates to the `defaultHeaders` prop are reflected when subsequently adding new tabs.

add missing effect dep for default headers

---

.changeset/rich-humans-rescue.md
packages/graphiql-react/src/execution.tsx
packages/graphiql-react/src/toolbar/execute.tsx

I noticed this after looking at https://github.com/graphql/graphiql/pull/2885: We're currently not showing the stop button while a multipart request (e.g. a subscription) is running. The only state provided by the context is the boolean `isFetching` which is `true` only until the first (partial) response is returned.
This PR solves the issue by exposing another boolean `isSubscribed` which is `true` if there is an active subscription running (i.e. the fetcher function returned an unsubscribable).
Sidenote: We can't just change the semantics of the `isFetching` state. It also controls the loading spinner which should indeed only be shown while the first response is loading.

show multipart requests as running until they are finished or cancelled

---

.changeset/loud-beans-mate.md
packages/graphiql-react/src/editor/__tests__/tabs.spec.ts
packages/graphiql-react/src/editor/context.tsx
packages/graphiql-react/src/editor/tabs.ts
packages/graphiql-react/src/provider.tsx
packages/graphiql/src/components/GraphiQL.tsx
packages/graphiql/src/components/__tests__/GraphiQL.spec.tsx

Following up on https://github.com/graphql/graphiql/pull/2821 (I didn't manage to review even though it was open for a while, sorry for that 🙈 ).
This PR suggests a different naming for the `initialTabs` prop. The word "initial" suggests that GraphiQL will always spawn with a certain set of tabs if I pass them to this prop. But it's actually just the default set of tabs that will be shown if there is no tab state persisted in `localStorage`. Imho, `defaultTabs` would be a better wording here and also aligns with other props like `defaultQuery`.
As renaming would be a breaking change now (the new prop is already released), we deprecate the existing prop and add a new one. The deprecated prop can then be removed in a future major version.

rename the `initialTabs` prop to `defaultTabs`

---

.changeset/loud-guests-drive.md
packages/graphiql-react/src/explorer/components/doc-explorer.tsx

This PR prevents the default event when clicking the doc explorer's back button. Without this change, clicking the back button will cause the page to navigate away in some use-cases.

fix: prevent default event for graphiql-doc-explorer-back link

---

.changeset/heavy-dancers-deliver.md
packages/graphql-language-service-server/src/findGraphQLTags.ts
packages/graphql-language-service-server/src/parseDocument.ts
packages/vscode-graphql-syntax/grammars/graphql.js.json
packages/vscode-graphql/src/extension.ts

Resolves #2855 
Introduces support for the `.cts` and `.mts` in the VSCode extension(s) and the LSP server
note: no tests were created for this patch

fix: support cts/mts extensions

---

.changeset/gold-cups-scream.md
packages/graphiql-toolkit/src/storage/__tests__/base.spec.ts
packages/graphiql-toolkit/src/storage/base.ts

I noticed we were overriding `localStorage.clear` method when the `StorageAPI` constructor ran, and this could cause unexpected behavior when someone is building a GraphQL Editor and using the `StorageContext`.
This makes sure we are not affecting the local storage prototype.

Remove side-effect in StorageAPI that overrides localStorage.clear

---

packages/cm6-graphql/tsconfig.json

when we added `cm6-graphql` we forgot to add the workspace `references`, to teach typescript project references about the dependency tree
This will fix a bug we are seeing in netlify (e.g. #2928)

fix workspaces bug on merge

---

.changeset/lazy-camels-trade.md
custom-words.txt
packages/graphiql-react/package.json
packages/graphiql-react/src/editor/components/header-editor.tsx
packages/graphiql-react/src/editor/components/variable-editor.tsx
packages/graphiql-react/src/history/components.tsx
packages/graphiql-react/src/toolbar/button.tsx
packages/graphiql-react/src/toolbar/listbox.tsx
packages/graphiql-react/src/toolbar/menu.tsx
packages/graphiql-react/src/ui/button-group.tsx
packages/graphiql-react/src/ui/button.tsx
packages/graphiql-react/src/ui/dialog.tsx
packages/graphiql-react/src/ui/dropdown.tsx
packages/graphiql-react/src/ui/markdown.tsx
packages/graphiql-react/src/ui/spinner.tsx
packages/graphiql-react/src/ui/tabs.tsx
packages/graphiql-react/src/utility/compose.ts
yarn.lock

`clsx` is tiny and fastest library for class concatenation (compared to `classnames` library)

[@graphiql/react]: replace `compose.ts` with `clsx` for class concatenation

---

.changeset/polite-crabs-double.md
.eslintrc.js
examples/monaco-graphql-react-vite/src/App.tsx
packages/graphiql-react/src/utility/resize.ts
packages/graphql-language-service-server/src/GraphQLCache.ts

found code that does nothing https://github.com/graphql/graphiql/blob/695100bd317940ff3ffd8f56b54248c1dba1ac04/packages/graphiql-react/src/utility/resize.ts#L158
a good case to enable this rule

enable `@typescript-eslint/no-unused-expressions` rule

---

packages/graphiql-plugin-explorer/examples/index.html

The example `index.html` was overwritten in #2835 with an incorrect unpkg URL.

fix for graphiql-plugin-explorer example

---

.changeset/sweet-foxes-drive.md
packages/graphiql-react/src/editor/__tests__/tabs.spec.ts
packages/graphiql-react/src/editor/context.tsx
packages/graphiql-react/src/editor/tabs.ts
packages/graphiql/src/components/GraphiQL.tsx
packages/graphiql/src/components/__tests__/GraphiQL.spec.tsx
packages/graphiql/src/style.css

Resolves https://github.com/graphql/graphiql/issues/2793
Adds a user control in the settings dialog for persisting headers. This is only visible if the `shouldPersistHeaders` is explicitly set as `false`.
Demo and brief explanation: https://www.loom.com/share/d72cf65025b04b1f9d6d5e518445bc25
I also found 2 potential issues when working on this:
- https://github.com/graphql/graphiql/issues/2891 (Accessibility related, I think the ButtonGroup we use in the settings dialog doesn't have the correct accessibility behavior and attributes. I decided to keep it as a separate issue to keep this PR smaller, I'll work on that one once this one is completed)
- https://github.com/graphql/graphiql/issues/2892
**Note for the future:** I think it would be nice to somehow refactor this out into a user …

Add user facing setting for persisting headers

---

packages/graphiql-react/src/editor/__tests__/tabs.spec.ts
packages/graphiql-react/src/editor/tabs.ts

A small regex fix with additional tests to address #2949.
Additionally, I visually tested this out by modifying `renderExample.js` to pass in default tabs.
Asking for review from @thomasheyenbrock (touched this code most recently) and @n1ru4l (originator).

Fix graphiql react issue with setting tabs title

---

.changeset/fifty-points-share.md
packages/graphql-language-service/src/utils/__tests__/__schema__/RecursiveSchema.graphql
packages/graphql-language-service/src/utils/__tests__/getVariablesJSONSchema.spec.ts
packages/graphql-language-service/src/utils/getVariablesJSONSchema.ts

add a marker to mark analyzed InputObject to avoid infinity recursiveness while generating JsonSchema.
see https://github.com/graphql/graphiql/issues/2685

fix: avoid infinity recursiveness in getVariablesJSONSchema

---

.changeset/eight-crews-clean.md
packages/graphql-language-service/src/utils/getVariablesJSONSchema.ts

`any` is not an accepted value for [type](https://json-schema.org/draft/2020-12/json-schema-validation.html#name-type), which gives an error in validation.
In order to accept any value, we should just not add the `type` property at all.
before:
after:

fix: VariableJSONSchema for custom scalars

---

packages/graphql-language-service/src/interface/__tests__/getDiagnostics-test.ts
packages/graphql-language-service/src/interface/getDiagnostics.ts

Hello! 
This PR adds a unit test with the reproduction of a bug in undefined variables validation: `getDiagnostics` function returns an "undefined variable" error twice and has the wrong end position for the second entry.
For instance for a following query on star wars schema:
`{ hero(episode: $ep) { name } }`
1. it returns two "Variable \\"$ep\\" is not defined." erros instead of one 
2. The second error has end position = 48 which is greater than the query itself

Reproduction of a bug in validation of undefined variables

---

packages/graphql-language-service/src/utils/getVariablesJSONSchema.ts

Not 100% sure how this came in given that we're linting on each PR. Maybe we merged the PR that adjusted the rule and another PR that did changes here at the same time? Anyways, this fixes linting on `main`

fix eslint error

---

packages/vscode-graphql/README.md

ref: https://github.com/graphql/graphiql/issues/2843
related: https://github.com/graphql/graphiql/pull/2849
It seems that there was a part of the problem that we forgot to address in #2849.
I confirmed with `git grep` that there are no other omissions.
```console
$ git grep "\/\* GraphiQL \*\/"
packages/vscode-graphql-syntax/CHANGELOG.md:  (not `/* GraphiQL */`) is the delimiter for `vscode-graphql-syntax` &
packages/vscode-graphql/CHANGELOG.md:  (not `/* GraphiQL */`) is the delimiter for `vscode-graphql-syntax` &
```

Fix typo (`/* GraphiQL */` => `/* GraphQL */`)

---

.eslintrc.js
packages/codemirror-graphql/src/index.d.ts
packages/graphql-language-service/src/interface/getAutocompleteSuggestions.ts

related https://github.com/graphql/graphiql/issues/2894
rebase after merging https://github.com/graphql/graphiql/pull/2962

[wip] 🛠️ ESLint: extends `plugin:@typescript-eslint/recommended` config

---

.changeset/ninety-peaches-crash.md
packages/graphiql-react/src/explorer/components/__tests__/doc-explorer.spec.tsx
packages/graphiql-react/src/explorer/context.tsx
packages/graphiql-react/src/schema.tsx

Previously:
- when you click the schema reload button, the doc explorer stack was reset even if the schema is unchanged 😞 
- when you passed a new schema in, the doc explorer stack is _unaffected_, meaning it can render invalid content or even crash in some circumstances 🐞
I'm not sure what the need for resetting the explorer stack is, so I've raised this PR to begin discussions. I believe that the doc explorer should only be reset when an incompatible schema is loaded, and even then we should aim to keep the compatible parts of the stack where possible. I've attempted to achieve this (and included tests for the same) in this PR.

feat: maintain DocExplorer stack on schema update

---

.changeset/eighty-rabbits-ring.md
packages/vscode-graphql-syntax/grammars/graphql.json

Adding fragment argument syntax highlighting to VSCode. This is needed as per discussion in https://github.com/graphql/graphql-wg/discussions/1239#discussioncomment-4908699
Before:
After:
To test this:
- Download VSCode from https://code.visualstudio.com/docs
- Download the *GraphQL Foundation* **GraphQL Syntax Highlighting** extension (in my case, v1.0.6)
- Write a `test.graphql` file and ensure syntax highlighting is working as expected.
- Copy `graphiql/packages/vscode-graphql-syntax/grammars/graphql.json` to `~/.vscode/extensions/graphql.vscode-graphql-syntax-1.0.6/grammars/graphql.json`
- Reload VSCode
*Probably* the fast-devex way to make changes here is to have some `ln -s` symlink from `~/.vscode/extensions/` to `graphiql/packages/vscode-graphql-syntax`, but this change was simple …

feature: add fragment arguments syntax highlights

---

.browserslistrc
examples/graphiql-webpack/package.json
examples/monaco-graphql-webpack/package.json
examples/monaco-graphql-webpack/src/editors.ts
examples/monaco-graphql-webpack/tsconfig.json
examples/monaco-graphql-webpack/webpack.config.js
packages/graphiql/package.json
packages/graphiql/resources/webpack.config.js
packages/graphql-language-service-server/package.json
yarn.lock

upgrade to webpack 5!
both remix and next.js are shipping with webpack 5, so it's still a viable option until we switch fully to vite.
Next:
- pnpm & pnp mode!

upgrade to webpack 5, re-add monaco workspace

---

.changeset/warm-hotels-compare.md
examples/monaco-graphql-nextjs/package-lock.json
examples/monaco-graphql-nextjs/src/pages/_app.tsx
examples/monaco-graphql-nextjs/src/pages/_document.tsx
examples/monaco-graphql-nextjs/src/pages/index.tsx
examples/monaco-graphql-webpack/CHANGELOG.md
packages/cm6-graphql/CHANGELOG.md
packages/codemirror-graphql/CHANGELOG.md
packages/graphiql-plugin-explorer/CHANGELOG.md
packages/graphiql-react/CHANGELOG.md
packages/graphiql-react/tsconfig.cjs.json
packages/graphiql-react/vite.config.d.ts
packages/graphiql-react/vite.config.js
packages/graphiql-toolkit/CHANGELOG.md
packages/graphiql/CHANGELOG.md
packages/graphql-language-service-cli/CHANGELOG.md
packages/graphql-language-service-server/CHANGELOG.md
packages/graphql-language-service/CHANGELOG.md
packages/monaco-graphql/CHANGELOG.md
packages/monaco-graphql/package.json
packages/monaco-graphql/src/typings/refs.d.ts
packages/vscode-graphql-execution/CHANGELOG.md
packages/vscode-graphql-syntax/CHANGELOG.md
packages/vscode-graphql/CHANGELOG.md
yarn.lock

- fix monaco peer dependencies
- fix linting issue with nextjs example
- run `yarn format`
note - it seems we need to run `yarn format` after changelogs are generated

fix monaco peer deps and linting

---

.changeset/two-icons-rhyme.md
.eslintrc.js
docs/migration/graphiql-2.0.0.md
packages/graphiql-plugin-code-exporter/src/index.tsx
packages/graphiql-plugin-explorer/src/index.tsx
packages/graphiql/README.md

```
You may rely on useMemo as a performance optimization, not as a semantic guarantee. 
In the future, React may choose to “forget” some previously memoized values and recalculate them on next render, 
e.g. to free memory for offscreen components. 
Write your code so that it still works without useMemo — and then add it to optimize performance.
```
https://github.com/shuding/nextra/pull/1209#discussion_r1064560233

avoid `useMemo` with empty array `[]` since React can't guarantee stable reference, + lint restrict syntax for future mistakes

---

packages/graphql-language-service-server/src/GraphQLCache.ts

just saw a piece of code where `fs.readFile` was used with `new Promise`

use promise version of fs.readFile

---

.changeset/twenty-flies-unite.md
.eslintrc.js
custom-words.txt
packages/graphiql-plugin-code-exporter/src/index.tsx
packages/graphiql-plugin-code-exporter/tsconfig.json
packages/graphiql-plugin-code-exporter/vite.config.ts
packages/graphiql-plugin-explorer/src/index.tsx
packages/graphiql-plugin-explorer/tsconfig.json
packages/graphiql-plugin-explorer/vite.config.ts
packages/graphiql-react/vite.config.ts

We currently include code from `react/jsx-runtime` in the bundled output files. That prevents anybody from using these packages with Preact, as using React-packages with Preact relies on import aliasing. We solve that for all affected packages in two different ways:
- For `@graphiql/react` we're simply marking `react/jsx-runtime` as external.
- For the plugin packages (`@graphiql/plugin-explorer` and `@graphiql/plugin-code-exporter`) the above doesn't work because these packages also provide a UMD build. There's currently no file provided by `react` that would allow to load the JSX runtime transform as UMD bundle. So instead we fall back to the "classic" JSX transform that requires us to `import React from 'react'` in all `tsx` files. However, these plugins are quite lean and only consist …

avoid bundling code from `react/jsx-runtime`

---

packages/graphql-language-service-server/src/GraphQLCache.ts

do not destructure `Kind` from graphql

---

.changeset/green-radios-fix.md
packages/cm6-graphql/README.md
packages/codemirror-graphql/README.md

Updated cm6-graphql package README

Updated cm6-graphql package README

---

.changeset/tasty-socks-swim.md
packages/vscode-graphql-syntax/README.md
packages/vscode-graphql-syntax/grammars/graphql.scala.json
packages/vscode-graphql-syntax/package.json

Adds syntax highlighting for graphql\gql strings in Scala

feat: add syntax highlighting in Scala

---

.changeset/breezy-laws-sneeze.md
.eslintrc.js
examples/monaco-graphql-webpack/src/index.ts
packages/codemirror-graphql/src/utils/collectVariables.ts
packages/codemirror-graphql/src/utils/runParser.ts
packages/codemirror-graphql/src/variables/lint.ts
packages/graphiql-react/src/editor/hooks.ts
packages/graphiql-toolkit/src/graphql-helpers/auto-complete.ts
packages/graphiql/cypress/e2e/init.cy.ts
packages/graphiql/resources/renderExample.js
packages/graphql-language-service-server/src/GraphQLCache.ts
packages/graphql-language-service-server/src/findGraphQLTags.ts
packages/graphql-language-service/benchmark/index.ts
packages/graphql-language-service/src/interface/getAutocompleteSuggestions.ts
packages/graphql-language-service/src/interface/getDefinition.ts
packages/graphql-language-service/src/interface/getDiagnostics.ts
packages/graphql-language-service/src/parser/__tests__/OnlineParserUtils.ts
packages/graphql-language-service/src/utils/collectVariables.ts
packages/graphql-language-service/src/utils/fragmentDependencies.ts
packages/graphql-language-service/src/utils/getVariablesJSONSchema.ts
packages/monaco-graphql/src/LanguageService.ts
packages/monaco-graphql/src/languageFeatures.ts
packages/vscode-graphql-execution/src/helpers/network.ts
packages/vscode-graphql-execution/src/helpers/source.ts
scripts/buildFlow.js
scripts/renameFileExtensions.js

A "for-of" loop is faster, as it doesn't need to execute the body function for each iteration (it's just a scope). This especially matters if the loop body is complex. https://github.com/sindresorhus/eslint-plugin-unicorn/issues/1522#issuecomment-917831928
also, GitHub has its own rule that does the same that unicorn plugin https://github.com/github/eslint-plugin-github/blob/main/docs/rules/array-foreach.md
I explicitly added a changeset

[ESLint] replace `.forEach` with `for..of`

---

.eslintrc.js
packages/codemirror-graphql/src/utils/info-addon.ts
packages/graphiql-react/src/explorer/components/__tests__/type-documentation.spec.tsx

Enforces the use of, for example, `child.remove();` over `child.parentNode.removeChild(child);`. The DOM function [`Node#remove()`](https://developer.mozilla.org/en-US/docs/Web/API/ChildNode/remove) is preferred over the indirect removal of an object with [`Node#removeChild()`](https://developer.mozilla.org/en-US/docs/Web/API/Node/removeChild).
https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-dom-node-remove.md

[ESLint] enable `unicorn/prefer-dom-node-remove`

---

.eslintrc.js
examples/monaco-graphql-webpack/src/index.ts
packages/codemirror-graphql/src/info.ts
packages/codemirror-graphql/src/utils/info-addon.ts
packages/graphiql-react/src/editor/completion.ts
packages/graphiql/__mocks__/@graphiql/react.tsx
packages/graphiql/__mocks__/codemirror.ts

Enforces the use of, for example, `document.body.append(div)`; over `document.body.appendChild(div)`; for DOM nodes. There are [some advantages of using Node#append()](https://developer.mozilla.org/en-US/docs/Web/API/ParentNode/append), like the ability to append multiple nodes and to append both [DOMString](https://developer.mozilla.org/en-US/docs/Web/API/DOMString) and DOM node objects.
https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-dom-node-append.md

[ESLint] enable `unicorn/prefer-dom-node-append`

---

.changeset/tasty-glasses-report.md
.eslintrc.js
packages/graphiql-toolkit/src/async-helpers/index.ts
packages/graphql-language-service-cli/src/cli.ts
packages/graphql-language-service-server/src/GraphQLCache.ts
packages/graphql-language-service-server/src/__tests__/MessageProcessor-test.ts
packages/graphql-language-service-server/src/startServer.ts
packages/monaco-graphql/src/initializeMode.ts
packages/vscode-graphql-execution/src/providers/exec-content.ts
packages/vscode-graphql/src/server/index.ts

why for non-React - because it's ugly have `async IIFE` inside `useEffect`

[ESLint] enable `promise/prefer-await-to-then` for non React packages

---

.changeset/eight-swans-destroy.md
packages/graphql-language-service-server/src/__tests__/findGraphQLTags-test.ts
packages/graphql-language-service-server/src/findGraphQLTags.ts

fixes: [#2836](https://github.com/graphql/graphiql/issues/2836)
When there is no `<script>` tag in the file, it's ok. We will not have any `graphql`.
Let's not log an error in this situation.

fix: vue & svelte wo script tag

---

.changeset/eight-swans-destroy.md

just adding `vscode-graphql` to the changeset so that users see that this terrible bug has been patched!

tweak LSP/vscode changelog entry

---

.changeset/many-sloths-shop.md
packages/graphql-language-service-server/src/GraphQLCache.ts
packages/graphql-language-service-server/src/GraphQLLanguageService.ts
packages/graphql-language-service-server/src/__tests__/GraphQLLanguageService-test.ts

Fixes: https://github.com/graphql/graphiql/issues/2575
Fixes the issue where a schema like 
```graphql
union X = A | B
type A { x: String }
type B { x: String }
type Query { a: X }
```
won't allow you to click through to X. 
Also fixes the case where this is split across two files (e.g. `type Query { a: X }` is in one file and the rest are in another)

fix(graphql-language-service-server): allow getDefinition to work for unions

---

.changeset/shy-starfishes-clap.md
packages/graphql-language-service-server/src/GraphQLCache.ts

Resolves: https://github.com/graphql/graphiql/issues/2989 (and perhaps others)

Fix GraphQLCache to read both documents and schema

---

.changeset/thin-poems-search.md
packages/graphql-language-service-server/src/__tests__/findGraphQLTags-test.ts
packages/graphql-language-service-server/src/findGraphQLTags.ts

closes https://github.com/graphql/graphiql/issues/3115
Related:
https://github.com/graphql/graphiql/pull/2827#issuecomment-1333707395
Description:
This fixes Intellisense for Vue SFC files which contain template code above the script (both setup and normal). The issue was that the line locations inside the ASTs returned from `compileScript` where relative to the start of the script tag and not the start of the file. This lead to intellisense and errors working with the wrong line information when the file contained a template above the script.
The fix returns a `scriptOffset` from `parseVueSFC`, which should contain the correct offset of the script tag
I added some tests and also tested it visually with a project for which i had problems with.

fix: script offset if vue-sfc contains template above

---

.changeset/dry-olives-crash.md
.eslintrc.js
custom-words.txt
examples/graphiql-parcel/src/index.tsx
examples/graphiql-webpack/src/index.jsx
package.json
packages/graphiql-plugin-explorer/src/index.tsx
packages/graphiql-react/src/editor/components/header-editor.tsx
packages/graphiql-react/src/explorer/components/field-documentation.tsx
packages/graphiql-react/src/explorer/components/search.tsx
packages/graphiql-react/src/explorer/components/type-documentation.tsx
packages/graphiql-react/src/history/components.tsx
packages/graphiql-react/src/toolbar/button.tsx
packages/graphiql/src/components/GraphiQL.tsx
yarn.lock

setup https://github.com/arthurgeron/eslint-plugin-react-usememo plugin and refactor different places to use `useMemo`/`useCallback`

avoid unnecessary rerenders React components

---

.changeset/two-chicken-pretend.md
.eslintrc.js
examples/monaco-graphql-webpack/src/index.ts
packages/cm6-graphql/src/completions.ts
packages/graphiql-react/src/editor/completion.ts

Enforces the use of `.textContent` over `.innerText` for DOM nodes.
There are [some advantages of using `.textContent`](https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent), like performance and more predictable behavior when updating it
https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-dom-node-text-content.md

[ESLint] Prefer `.textContent` over `.innerText`

---

.changeset/shaggy-chairs-explode.md
packages/graphiql-react/src/editor/header-editor.ts
packages/graphiql-react/src/editor/variable-editor.ts

related https://github.com/graphql/graphiql/pull/3126
also, it could catch cyrillic chars too

replace rest of `event.keyCode` usages by `event.code`

---

.changeset/sour-monkeys-film.md
packages/codemirror-graphql/src/utils/info-addon.ts

Makes tooltips work when not using Graphiql full page and window has scrolled.
Closes #3202

fix: make tooltips work when Graphiql is not full page and window has scrolled

---

.changeset/shiny-carpets-rescue.md
packages/graphiql-plugin-code-exporter/package.json
packages/graphiql-plugin-explorer/package.json
packages/graphiql-react/package.json
packages/graphiql-react/src/explorer/components/doc-explorer.css
packages/graphiql-react/src/explorer/components/doc-explorer.tsx
packages/graphiql-react/src/explorer/components/search.css
packages/graphiql-react/src/explorer/components/search.tsx
packages/graphiql-react/src/toolbar/menu.tsx
packages/graphiql/cypress/e2e/docs.cy.ts
packages/graphiql/cypress/support/commands.ts
packages/graphiql/package.json
packages/graphiql/resources/index.html.ejs
packages/graphiql/resources/renderExample.js
yarn.lock

currently, radix doesn't have `Combobox` unstyled component (a related issue https://github.com/radix-ui/primitives/issues/1342)
After a long googling I found a perfect alternative a lightweight [`cmdk`](https://github.com/pacocoursey/cmdk) that uses under the hood only 1 dependency `@radix-ui/react-dialog` but it has peerDependency of React 18 because it uses React.useId https://github.com/pacocoursey/cmdk/blob/db1e29aa7ee173bf3ac269f9f815ee45ebbabd56/cmdk/src/index.tsx#L165
So I propose to release GraphiQL v3 with replaced Reach UI with Radix/CMDK with React 18 and bump GraphiQL v4 with Monaco instead Codemirror

4️⃣ replace `@reach/combobox` with `Combobox` from `@headlessui/react`

---

examples/graphiql-cdn/index.html
examples/graphiql-create-react-app/package.json
examples/graphiql-create-react-app/src/index.tsx
examples/graphiql-parcel/package.json
examples/graphiql-parcel/src/index.tsx
examples/graphiql-webpack/package.json
examples/graphiql-webpack/src/index.jsx
examples/monaco-graphql-react-vite/package.json
examples/monaco-graphql-react-vite/src/index.tsx
packages/graphiql-plugin-code-exporter/examples/index.html
packages/graphiql-plugin-explorer/examples/index.html
packages/graphiql-react/src/editor/response-editor.tsx
packages/graphiql-react/src/ui/dialog.css
packages/graphiql-toolkit/docs/create-fetcher.md
packages/graphiql/README.md

fixes https://github.com/graphql/graphiql/issues/3081

5️⃣ replace all `ReactDOM.render(...)` by `createRoot(...)` from React 18

---

.changeset/gentle-ears-compare.md
.changeset/gold-lizards-march.md
.changeset/hip-ways-provide.md
.changeset/poor-lizards-jam.md
.changeset/shiny-carpets-rescue.md
packages/graphiql-react/src/toolbar/execute.tsx
packages/graphiql-react/src/toolbar/menu.tsx
packages/graphiql-react/src/ui/dropdown.css
packages/graphiql-react/src/ui/dropdown.tsx
packages/graphiql/src/cdn.ts
packages/monaco-graphql/src/languageFeatures.ts

fixes https://github.com/graphql/graphiql/issues/3187 cc @jetsstarplus
https://github.com/graphql/graphiql/assets/7361780/f17569a5-8ac0-4dac-99dc-be4f695ffee3

fixed long list items in dropdown were hidden, rename `<Menu />` to `<DropdownMenu />`

---

.github/ISSUE_TEMPLATE/vscode-graphql-syntax-bug.yml

this PR clarifies the issue template for `vscode-graphql-syntax`. 
thanks @B2o5T for noticing the incorrect usage!

renames file and updates copy

---

.changeset/metal-cats-hammer.md
packages/graphql-language-service/src/interface/getAutocompleteSuggestions.ts

Fixes https://github.com/graphql/graphiql/issues/2874
The hover docs were off by one position. This was due to autocomplete suggestions and hover docs using the same `getTokenAtPosition` function. For autocomplete, the behavior of the function was expected since your cursor is _after_ the token you want to get when requesting autocomplete results, but with hover docs you want the cursor _at_ the cursor position.

fix: Hover docs were offset one position

---

DEVELOPMENT.md

A quick PR to add a helpful note to the `DEVELOPMENT.md` file with the dev URL for graphiql access.

add note about graphiql dev URL

---

.eslintrc.js
packages/monaco-graphql/src/initializeMode.ts
packages/monaco-graphql/src/languageFeatures.ts
packages/monaco-graphql/src/monaco.contribution.ts

in The Guild we use this rule to prevent `<...>` assertions

enable `@typescript-eslint/consistent-type-assertions`

---

.changeset/soft-dingos-report.md
packages/graphql-language-service-server/src/GraphQLCache.ts
packages/graphql-language-service-server/src/MessageProcessor.ts
packages/vscode-graphql/src/extension.ts

Currently, the schema is cached permanently and never reloaded. This makes it very awkward when you're developing the graphql api and the front-end at the same time, as the auto completion and validation will rely on incorrect data.
I found a function named `_invalidateSchemaCacheForProject` that did what I needed, however it's not actually used anywhere. I assume this was removed by accident, so I found somewhere I think is appropriate to invoke it.
* Invalidate the schema cache when changed in handleWatchedFilesChangedNotification
* Add .json to watched files so it will pick up changes to introspection files

fix: reload schema when a change to the schema file is detected

---

.changeset/nice-sheep-fold.md
packages/graphiql-plugin-code-exporter/package.json
packages/graphiql-plugin-code-exporter/vite.config.ts
packages/graphiql-plugin-explorer/package.json
packages/graphiql-plugin-explorer/vite.config.ts

fix https://github.com/graphql/graphiql/issues/3242

always bundle `package.json#dependencies` for UMD for `@graphiql/plugin-code-exporter` and `@graphiql/plugin-explorer`

---

.eslintrc.js
examples/monaco-graphql-nextjs/src/components/editor.tsx
examples/monaco-graphql-react-vite/src/App.tsx
examples/monaco-graphql-webpack/src/index.ts
package.json
packages/graphiql-react/src/editor/completion.ts
packages/graphiql-toolkit/src/storage/history.ts
packages/graphiql/__mocks__/codemirror.ts
packages/graphql-language-service-server/src/findGraphQLTags.ts
packages/graphql-language-service-server/src/startServer.ts
packages/graphql-language-service/src/interface/getAutocompleteSuggestions.ts
yarn.lock

to avoid https://github.com/graphql/graphiql/pull/3140#discussion_r1169353266 and https://github.com/graphql/graphiql/pull/3140#discussion_r1169355858

setup `@shopify/prefer-early-return` and `sonarjs/no-inverted-boolean-check`

---

.eslintrc.js
examples/cm6-graphql-parcel/src/testSchema.ts
examples/monaco-graphql-webpack/src/index.ts
packages/cm6-graphql/src/completions.ts
packages/codemirror-graphql/src/__tests__/testSchema.ts
packages/graphiql-react/src/editor/query-editor.ts
packages/graphiql-toolkit/src/async-helpers/index.ts
packages/graphiql-toolkit/src/create-fetcher/lib.ts
packages/graphiql-toolkit/src/storage/__tests__/base.spec.ts
packages/graphiql-toolkit/src/storage/base.ts
packages/graphiql/resources/webpack.config.js
packages/graphiql/test/schema.js
packages/graphql-language-service-server/src/MessageProcessor.ts
packages/graphql-language-service-server/src/__tests__/MessageProcessor-test.ts
packages/graphql-language-service-server/src/findGraphQLTags.ts
packages/graphql-language-service/benchmark/index.ts
packages/graphql-language-service/src/interface/getOutline.ts
packages/monaco-graphql/src/languageFeatures.ts
packages/vscode-graphql/src/extension.ts

less code written
```js
foo: (bar) => {
foo(bar) {
```

enable avoidExplicitReturnArrows: true option for `object-shorthand` rule

---

.github/workflows/pr-graphql-compat-check.yml

we only need to worry about old 15.x versions and latest 16.x that we support.

update regression test matrix

---

.github/workflows/pr-tests.yml

previously, if you opened a PR that included any markdown changes, even if there were also code changes, the ci would skip tests
essentially, `paths-ignore` does not work the way we hope

fix: run tests for commits that include markdown, etc changes

---

functions/schema-demo.js
package.json
packages/graphiql/package.json
packages/graphiql/resources/webpack.config.js
packages/graphiql/test/beforeDevServer.js
packages/graphiql/test/e2e-server.js
yarn.lock

`express-graphql` has been deprecated. `graphql-http` is now the transport wg reference implementation. because we are a reference implementation of a reference implementation, we should be using this library instead, or whatever the wg is using.

replace `express-graphql` with `graphql-http`

---

.changeset/shaggy-eyes-melt.md
packages/graphiql-plugin-explorer/src/graphiql-explorer.d.ts
packages/graphiql-plugin-explorer/src/index.tsx

Hi!
While working on https://github.com/gatsbyjs/gatsby/pull/38279 I saw failures in our E2E testing suite.
We use the GraphiQL explorer plugin and when opening that tab the page just got blank and the console threw an error:
It errors at this call:
https://github.com/graphql/graphiql/blob/2f15e202b194387a1bd78fc778268fb9b8c0fa12/packages/graphiql-plugin-explorer/src/index.tsx#L130
Because the import is an object with `Explorer` and `default`.
If I compare https://unpkg.com/browse/@graphiql/plugin-explorer@0.1.22/dist/index.mjs with https://unpkg.com/browse/@graphiql/plugin-explorer@0.1.20/dist/graphiql-plugin-explorer.es.js you can see that older versions had helper functions to pick `.default` if available.

fix(graphiql-plugin-explorer): Use named `Explorer` import from `graphiql-explorer`

---

package.json

- fixes a false positive non 0 exit error on husky git commit hooks when no files are found with [--no-must-find-files](https://github.com/streetsidesoftware/cspell/issues/2594#issuecomment-1072751914)
- `--no-progress` makes output easier to read locally and in CI
Notes:
- it would be nice to add these to the config file, but reading the code for `cspell`, it appears these flags are used by the CLI only, thus why they aren't configurable in the config file
- in another PR, we should consider replacing husky with [lefthook](https://www.npmjs.com/package/lefthook), or upgrading husky. this version is not compatible with `pnpm`, and the compatible upgrade will require config changes

[tooling] use cspell `--no-must-find-files` on git hooks, simplify output

---

package.json
packages/graphiql/package.json
packages/graphiql/resources/webpack.config.js

this we should've done a long time ago!
by combining the webpack dev and production builds, we reduce build time overall, as the dependency build happens only once
the first of many PRs pieced out from the #3306 effort

[tooling] combine webpack builds for faster builds & simpler tooling

---

.changeset/late-tables-teach.md
.gitignore
custom-words.txt
examples/graphiql-webpack/package.json
examples/graphiql-webpack/src/index.jsx
examples/graphiql-webpack/src/snippets.js
netlify.toml
package.json
packages/graphiql-plugin-code-exporter/README.md
packages/graphiql-plugin-code-exporter/examples/index.html
packages/graphiql-plugin-code-exporter/package.json
packages/graphiql-plugin-code-exporter/src/index.tsx
packages/graphiql-plugin-explorer/README.md
packages/graphiql-plugin-explorer/examples/index.html
packages/graphiql-plugin-explorer/src/index.tsx
resources/webpack.config.js
yarn.lock

this will incur breaking changes to the plugins, but it seems we have a funky workaround pattern being used that is causing regressions for users, and by moving the logic of getting/setting the editor value to become an internal concern again, we can:
- simplify plugin development
- simplify plugin implementation
- fix #2859 lifecycle bugs
- drop the `use` prefix, because they should not be invoked as react hooks, but widely used eslint rules will assume they are hooks

[graphiql] fix  graphiql plugin lifecycle bugs, simplify

---

.changeset/fifty-numbers-draw.md
packages/graphiql-react/src/explorer/components/deprecation-reason.tsx
packages/graphiql-react/src/explorer/components/field-documentation.tsx
packages/graphiql/resources/webpack.config.js

fixes #3348
also a quick fix for the graphiql dev server

fix multiline deprecation display issue

---

.changeset/six-bears-smile.md
packages/graphiql-plugin-code-exporter/src/index.tsx
packages/graphiql-plugin-code-exporter/vite.config.ts
packages/graphiql-plugin-explorer/src/index.tsx
packages/graphiql-react/src/editor/hooks.ts
packages/graphiql-react/src/editor/index.ts
packages/graphiql-react/src/index.ts

this abstracts away some editor specific details
until we can leverage `<Suspense />`
- add `useOperationsEditorState()`
- add `useVariablesEditorState()`
- match up `@graphiql/react` globals
- simplify plugin implementations

fix code exporter on early init, new hooks: useOperationsEditorState()

---

examples/graphiql-cdn/README.md
examples/graphiql-cdn/index.html
packages/graphiql-plugin-explorer/examples/index.html

- cleanup cdn examples
- add a plugin import  and headers (the most requested customizations) to examples/graphiql-cdn which is one of the highest traffic visits after the readme! 👀 
- remove a static version from the explorer example, many less web oriented server/framework devs are not aware that you can request the latest version by omitting one it seems

update the highest traffic examples

---

package.json

this makes pre-commit much faster if you have a cache already

use eslint cache on pre-commit hook

---

.changeset/lemon-snakes-exist.md
packages/graphiql-react/src/explorer/components/search.tsx
packages/graphiql/cypress/e2e/docs.cy.ts

Fixes #3307 
Temporarily disable the `onBlur` behavior, because it's more important to have the search results clickable than to dismiss the dropdown `onBlur` - already, simply by clicking outside the dropdown, you can dismiss it.

fix search dropdown click

---

.changeset/sour-maps-ring.md
packages/graphiql-react/src/editor/context.tsx
packages/graphiql-react/src/editor/tabs.ts

Solves #2825, an old bug where new tabs were created on every refresh
the bug occurred when:
1. `shouldPersistHeaders` is not set to true
2. `headers` or `defaultHeaders` are provided as props
3. the user refreshes the browser
I could not get cypress to re-create the bug, but I was able to manually confirm the fix

Avoid creating new tabs on header state

---

.github/workflows/pr.yml
scripts/canary-release.js

it seems `GITHUB_TOKEN` env variable is also missing from this step

add GITHUB_TOKEN to canary release

---

.changeset/few-hats-move.md
.changeset/tame-lions-teach.md
packages/graphql-language-service/src/utils/__tests__/__schema__/StarWarsSchema.graphql
packages/graphql-language-service/src/utils/__tests__/getVariablesJSONSchema.spec.ts
packages/graphql-language-service/src/utils/getVariablesJSONSchema.ts
packages/monaco-graphql/src/LanguageService.ts
packages/monaco-graphql/src/typings/index.ts

This PR fixes the following issues:
- In GraphQL, optional input variables and types are also nullable.
- in the JSON Schema, `enum` should not be combined with `type` (removed)
- custom scalars should only accept basic primitives (i.e. no objects, arrays, etc)

feat: Add support for custom scalar validation

---

packages/graphiql/resources/index.html.ejs
packages/graphiql/resources/renderExample.js
packages/graphiql/test/beforeDevServer.js

this will complete #3374 and make it much easier to test #3346,
furthermore, this allows us to add standalone e2e tests for the plugin, that can run off the same e2e setup used by the `graphiql` project

add plugins to webpack dev bundle

---

.changeset/blue-rice-arrive.md
packages/cm6-graphql/package.json
packages/cm6-graphql/src/lint.ts
packages/cm6-graphql/src/state.ts
yarn.lock

Relint when schema changes. Codemirror 6 normally only runs linting whenever the document changes. However this means whenever the GraphQL schema changes, the linting is not run again until the document changes. This can be lead to confusing behaviors.
A new option was added to the linter [recently](https://github.com/codemirror/lint/commit/2da5dbdae05e28af5b6b52334f7b10e70fd1111e) that allows configuring a predicate to determine when the linter will be ran when the state changes. We are leveraging the same here to trigger linting whenever the schema or passed option changes.
Note: linting always runs on document changes irrespective of what we define in this predicate, _which is what we want_.
Related issue: https://github.com/altair-graphql/altair/issues/2242

relint when schema changes

---

.changeset/slimy-needles-taste.md
packages/graphql-language-service-server/src/GraphQLCache.ts
packages/graphql-language-service-server/src/MessageProcessor.ts

When loading `vscode-graphql` it constantly crashes.
In the output there's lots of
```
[Error - 8:27:20 AM] there was an error loading the project config for this file YDe: File '[SNIPPED OUT FILENAME HERE].json' doesn't match any project
/Users/ben/.vscode/extensions/graphql.vscode-graphql-0.8.18/out/server/index.js:4640
'${t.documents}'`),this._logger.error(String(r))}}async _cacheAllProjectFiles(t){if(t?.projects)return Promise.all(Object.keys(t.projects).map(async r=>{let n=t.getProject(r);await this._cacheSchemaFilesForProject(n),await this._cacheDocumentFilesforProject(n)}))}_isRelayCompatMode(t){return t.includes("RelayCompat")||t.includes("react-relay/compat")}async _updateFragmentDefinition(t,r){let n=this._graphQLCache.getGraphQLConfig().dirpath;await …
```

Fix crash when when editing a file that doesn't belong to a project

---

.changeset/silver-lions-build.md
packages/cm6-graphql/src/lint.ts

It turns out that `getDiagnostics` may throw errors which codemirror 6 doesn't handle in the lint. Wrapping the logic in try..catch to handle errors and just return an empty array instead.

Wrap cm6-graphql lint logic in try..catch

---

.changeset/two-doors-shave.md
packages/cm6-graphql/src/interfaces.ts
packages/cm6-graphql/src/lint.ts
packages/cm6-graphql/src/state.ts

Create a lint diagnostic from invalid schema
Follow up from https://github.com/graphql/graphiql/pull/3461

Create a lint diagnostic from invalid schema

---

packages/graphql-language-service-server/src/MessageProcessor.ts

Reverts graphql/graphiql#3464 so we can re-do with a changeset without force pushing a rebase against main

Revert "fix: LSP server crashing in case of error in schema"

---

packages/graphql-language-service-server/src/MessageProcessor.ts
packages/vscode-graphql/package.json

I ran into a problem similar to https://github.com/graphql/graphiql/issues/2985 with a massive schema graphql file (~2MB file). The performance was fine when the schema is not opened (e.g, hovering for type definintions and autocomplete), but the LSP was stuck at 100% as soon as I opened the schema. It looks like the language server was stuck in `getOutline`, which is called by `textDocument/documentSymbol`. I'm not sure why this is so slow, but I generally don't care about the outline in such a large file anyway, so it seems OK to disable that feature. 
This PR adds a configuration option `largeFileThreshold`  which defaults to 1000000. At the moment, it just disables document symbols computation, but there might be other expensive operations we could disable with this option as well. 
I …

Disable document symbol request for files over 1MB

---

.changeset/curvy-balloons-allow.md
packages/graphiql/src/components/GraphiQL.tsx

Closes issue: #3373 
Description:
- Now we can control the use of tabs and allow disabling tabs.
Result UI:
- No tabs at all:

GraphiQL component: `disableTabs` prop

---

.github/workflows/main-test.yml
jest.config.base.js
packages/graphql-language-service-server/package.json
packages/graphql-language-service-server/src/GraphQLCache.ts
packages/graphql-language-service-server/src/MessageProcessor.ts
packages/graphql-language-service-server/src/__tests__/MessageProcessor-test.ts
packages/graphql-language-service-server/src/__tests__/findGraphQLTags-test.ts
packages/graphql-language-service-server/src/constants.ts
packages/graphql-language-service-server/src/findGraphQLTags.ts
packages/graphql-language-service-server/src/parseDocument.ts
packages/graphql-language-service-server/src/parsers/babel.ts
packages/graphql-language-service-server/src/parsers/svelte.ts
packages/graphql-language-service-server/src/parsers/types.ts
packages/graphql-language-service-server/src/parsers/vue.ts
packages/graphql-language-service-server/src/startServer.ts
packages/vscode-graphql-execution/package.json
yarn.lock

This is a revival of an effort from #3204 by @tadeokondrak to add more comprehensive svelte parsing by using the svelte compiler
I think this test case covers some more advanced usage?
Todo:

happy svelte parsing

---

DEVELOPMENT.md
packages/graphiql-react/README.md

I was setting up the repo and realized `start-graphiql` doesn't exist. 
This PR updates the startup command to `dev-graphiql`.

docs: Update command for development

---

.changeset/wet-bikes-complain.md
packages/graphql-language-service-server/package.json
packages/vscode-graphql/esbuild.js
yarn.lock

re-add typescript as a direct dependency of `graphql-language-service-server`, at a fixed version, because of svelte2tsx
this should resolve #3496 #3497

add ts dependency

---

.changeset/wet-bikes-complain.md
packages/graphql-language-service-server/package.json
yarn.lock

make sure to use the latest version of typescript. i get confused with the autocomplete and copilot, oops!

use latest typescript version in lsp server

---

.changeset/beige-parrots-sleep.md
packages/graphql-language-service-server/package.json
packages/graphql-language-service-server/src/__tests__/findGraphQLTags-test.ts
packages/graphql-language-service-server/src/findGraphQLTags.ts
packages/graphql-language-service-server/src/parsers/svelte.ts
packages/vscode-graphql/esbuild.js
yarn.lock

Temporarily revert svelte parsing until we can fix bundling issues with svelte2tsx. For now we return to using the vue parser to parse svelte files which will invariably cause some issues, such as being off by several characters

temporarily revert svelte parsing until we can fix bundling issues

---

.changeset/grumpy-moles-grin.md
custom-words.txt
packages/graphql-language-service-server/package.json
packages/graphql-language-service-server/src/constants.ts
packages/graphql-language-service-server/src/findGraphQLTags.ts
packages/graphql-language-service-server/src/parsers/astro.ts
packages/vscode-graphql-execution/package.json
packages/vscode-graphql-syntax/grammars/graphql.js.json
packages/vscode-graphql-syntax/package.json
packages/vscode-graphql/.vscodeignore
packages/vscode-graphql/esbuild.js
packages/vscode-graphql/package.json
packages/vscode-graphql/src/apis/statusBar.ts
packages/vscode-graphql/src/extension.ts
yarn.lock

Adds Astro syntax grammar support, language server parsing support, and misc wirings.

feat: add astro support for VSCode extension

---

.vscode/settings.json
custom-words.txt
packages/graphql-language-service-server/package.json
packages/graphql-language-service-server/src/MessageProcessor.ts
packages/graphql-language-service-server/src/__tests__/MessageProcessor-test.ts
packages/graphql-language-service-server/src/__tests__/findGraphQLTags-test.ts
packages/graphql-language-service-server/src/__tests__/parseDocument-test.ts
packages/graphql-language-service-server/src/findGraphQLTags.ts
packages/graphql-language-service-server/src/parseDocument.ts
packages/graphql-language-service/src/interface/getDiagnostics.ts
yarn.lock

- mockfs strategy
- move parseDocument tests to their own file
- config failure/lifecycle tests
current issue: inline requires in cosmiconfig seem to break fs-mock in weird ways. un-skipping the last test leads to a segfault

improve LSP tests

---

.changeset/nice-cars-rush.md
packages/monaco-graphql/src/workerManager.ts

There was a race condition in the workerManager. 
Which caused `worker` to be null [here](https://github.com/graphql/graphiql/blob/main/packages/monaco-graphql/src/languageFeatures.ts#L120).
This happened when several GraphQL editors on different models were present. `getLanguageServiceWorker()` called very quickly several times.
The root cause was that [here](https://github.com/graphql/graphiql/blob/main/packages/monaco-graphql/src/workerManager.ts#L61), `this._client` was still resolving (and therefore was null), but `this._worker` was present.

fix: Race condition in the workerManager

---

.changeset/new-tools-unite.md
packages/cm6-graphql/__tests__/cases.txt
packages/cm6-graphql/src/language.ts
packages/cm6-graphql/src/syntax.grammar

This PR fixes and issue where block strings aren't properly highlighted when they containe a new due to how their ANTLR grammar is defined in `cm6-graphql`
before:
https://github.com/graphql/graphiql/assets/105317851/67dcdc08-cf6c-4b68-905f-141b3a385642
after:
https://github.com/graphql/graphiql/assets/105317851/82d013fb-6bea-4c8b-9ec1-5b5bc163e6e8

fix: block strings syntax highlighting in cm6-graphql

---

.changeset/healthy-toes-grab.md
packages/monaco-graphql/src/languageFeatures.ts

When working with different editors, the JSON schemas are always overridden by new ones

fix: Do not override existing json diagnostic schemas

---

.changeset/fresh-rabbits-move.md
.changeset/silent-spoons-shout.md
packages/graphiql-plugin-explorer/src/index.tsx
packages/graphiql-react/src/editor/hooks.ts
packages/graphiql-react/src/editor/index.ts
packages/graphiql-react/src/index.ts

To see a reproduction of this issue, check out: https://github.com/graphile/crystal/issues/1845
The issue stems from some delays interfering with the reactivity model of React - when you type a character into Explorer, that change gets transformed into a GraphQL document string which is sent upstream into GraphiQL, GraphiQL then updates everything and sends the result back down stream to GraphiQL Explorer, which renders the new data. The issue is that if the user has typed another character in the interrim, their keypress will be overwritten by this flow because there is (I think!) a delay somewhere, i.e. the state is not updated synchronously. If the user types faster than this update loop, characters will be lost.
To solve this, we could use the "throttle" or "debounce" patterns to only …

Fix bug in Explorer plugin where characters are dropped when typing quickly

---

.changeset/angry-pots-return.md
packages/vscode-graphql-syntax/grammars/graphql.js.json
packages/vscode-graphql-syntax/tests/__fixtures__/test.js
packages/vscode-graphql-syntax/tests/__snapshots__/js-grammar.spec.ts.snap

fixes #3515
i broke this by introducing support for double quote graphql strings, which are much less common that these important doc annotations
adds test cases to confirm this still works

fix triple quote comment syntax

---

.changeset/famous-games-begin.md
packages/vscode-graphql-syntax/grammars/graphql.js.json
packages/vscode-graphql-syntax/tests/__fixtures__/test-js.md
packages/vscode-graphql-syntax/tests/__fixtures__/test.js
packages/vscode-graphql-syntax/tests/__fixtures__/test.ts
packages/vscode-graphql-syntax/tests/__snapshots__/js-grammar.spec.ts.snap
packages/vscode-graphql-syntax/tests/__snapshots__/markdown-grammar.spec.ts.snap

We're currently working on [`gql.tada`](https://github.com/0no-co/gql.tada), which is _mostly_ compatible with the expected syntax of `graphql` calls.
However, while getting this in users hands we noticed that a specific grammar that Prettier formats `graphql()` calls into fails to be matched by the Textmate grammar in `vscode-graphql-syntax`.
Specifically, when a GraphQL string literal is placed on a new line, the `begin` pattern of the rules can't match. This is a limitation in Textmate grammars, as it turns out, and we can't even manually match `\n` patterns.
I'm not an expert at Textmate grammars, but, in theory, a grammar rule that matches GraphQL calls as a lookbehind, then matches the inner string literal separately, should do the trick.
<table>
<thead><tr> …

fix: Fix vscode-graphql-syntax’s grammar to support string literals on separate lines

---

.changeset/green-houses-raise.md
packages/cm6-graphql/__tests__/cases.txt
packages/cm6-graphql/src/syntax.grammar

arguments separated by commas we not being parsed by the grammar leading to incorrect syntax highlighting in cm6-graphql package. 
Add an optional comma to Arguments in the grammar. This allows comma separated arguments as seen in the spec: https://spec.graphql.org/October2021/#sec-Language.Arguments.Arguments-are-unordered

multiple argument syntax highlighting

---

.changeset/famous-ads-jam.md
packages/vscode-graphql-syntax/grammars/graphql.js.json
packages/vscode-graphql-syntax/tests/__fixtures__/test-js.md
packages/vscode-graphql-syntax/tests/__fixtures__/test.js
packages/vscode-graphql-syntax/tests/__fixtures__/test.ts
packages/vscode-graphql-syntax/tests/__snapshots__/js-grammar.spec.ts.snap
packages/vscode-graphql-syntax/tests/__snapshots__/markdown-grammar.spec.ts.snap

Reverts graphql/graphiql#3518 which caused a new bug #3542

Revert "fix: Fix vscode-graphql-syntax’s grammar to support string literals on separate lines"

---

.changeset/warm-cups-explain.md
packages/vscode-graphql/package.json

I think this will fix the open VSX issue, because as it turns out, `ovsx` cli just uses `vsce` to re-build your project if you don't pass `extensionFile` on `publish`! oops!

fix OpenVSX dependency bug by tweaking openvsx publish

---

.changeset/sharp-rules-hide.md
packages/codemirror-graphql/src/info.ts

I created #3565 to document a bug that I was only able to reproduce with GraphiQL embedded inside of Grafana. Some behavior or bug in Grafana was causing clicking on an `a` tag with an href of 'javascript:void 0' to navigate away from the page. Although this isn't supposed to happen when the href is 'javascript:void 0', this PR is a one-liner fix to this issue by calling `event.preventDefault()`, which prevents the default behavior of trying to navigate to `javascript:void 0`.
Closes #3565

fix: Stop a tag with href of 'javascript:void 0' from navigating

---

.changeset/smooth-rings-trade.md
packages/graphiql-react/package.json
packages/graphiql/package.json
yarn.lock

This resolves a vulnerability: https://security.snyk.io/vuln/SNYK-JS-MARKDOWNIT-6483324 
The changelog seems like it won't impact

Update to markdown-it 14.x

---

.changeset/clean-pets-dance.md
packages/graphiql-react/src/execution.tsx

Hello fellow GraphiQL friends 👋 
We recently stumbled over the fact that GraphiQL does not yet implement the latest incremental response format for defer/stream, concretely the `incremental` payload property is not handled.
This PR cleans up the merge logic and makes it work for any incremental response payload. (Big inspiration taken from `graphql-tools/utils`, but if felt overkill to add the whole package just for this one utility, and since this is the official reference implementation for a GraphQL IDE it felt appropriate to have that utility as first-class citizen in our code.)
Some before-after illustrations:
| Feature | Before | After |
| --- | --- | --- |
| Defer | ![CleanShot 2024-04-10 at 11 16 14](https://github.com/graphql/graphiql/assets/22288634/086aee26-9fa8-4a2b-955f-7041bf …

implement correct merging of incremental respones (@defer/@stream)

---

.changeset/twenty-chicken-shout.md
packages/graphiql-react/src/ui/tooltip.tsx

The tooltip can accept any React Node as prop, no need to limit it to only `string`.

fix TS type of Tooltip.label prop

---

.changeset/nervous-numbers-push.md
packages/graphiql-react/src/icons/index.tsx

Setting `Component.defaultProps` issues some warnings in the console as the feature is considered deprecated. Replacing it with spreading component props with a default value instead.

avoid Component.defaultProps for icon components

---

.changeset/blue-points-taste.md
packages/graphiql-react/src/explorer/components/doc-explorer.css

https://github.com/graphql/graphiql/assets/7361780/2671e217-bfa7-4619-a8b7-6dee9bf97267
https://github.com/graphql/graphiql/assets/7361780/09464327-d2fc-42fa-b52a-e8d8050a4d82

fix doc explorer search input is cut off while clicking on autocomplete results

---

.changeset/ten-mangos-judge.md
packages/graphql-language-service-server/src/__tests__/findGraphQLTags.test.ts
packages/graphql-language-service-server/src/constants.ts
packages/graphql-language-service-server/src/findGraphQLTags.ts
packages/graphql-language-service-server/src/parsers/astro.ts
yarn.lock

the astro parsing is not causing the esbuild bundling process to fail, but the resultant `vscode-graphql` bundle does fail on server init
follow up to re-introduce astro support: we need to refactor parseDocument and it's children to be async, and to call this.parse() asynchronously throughout the language server to work around the node worker implementation of this which causes many issues
Note: you cannot re-create this by using the vscode debug runner, but by manually running `vsce:package` and installing the bundled vsix

fix: temporarily disable astro parsing again

---

package.json

corepack report error while installing dependencies
```text
! The local project doesn't define a 'packageManager' field. Corepack will now add one referencing yarn@1.22.22+sha512.a6b2f7906b721bba3d67d4aff083df04dad64c399707841b7acf00f6b133b7ac24255f2652fa22ae3534329dc6180534e98d17432037ff6fd140556e2bb3137e.
! For more details about this field, consult the documentation at https://nodejs.org/api/packages.html#packagemanager
yarn install v1.22.22
```

add `packageManager` field in `package.json`

---

.changeset/ten-mangos-judge.md

Now that I've fixed the astro parsing and made the vsix bundle happy, we don't want to clutter the changelog with this confusion

Remove changeset for astro removal

---

.changeset/loud-cherries-crash.md
packages/graphiql/package.json

after https://github.com/graphql/graphiql/pull/3655#issuecomment-2262788115 I realized that there is no need to have `@graphiql/toolkit` in `dependencies` too

[graphiql] move `@graphiql/toolkit` to `devDependecies` because umd build is bundled with all dependencies in one file

---

.github/workflows/main-test.yml
.github/workflows/pr.yml
packages/graphiql/package.json
yarn.lock

needs for vite migration https://github.com/graphql/graphiql/pull/3679

[1] update cypress to v13

---

.changeset/green-pugs-worry.md
packages/graphiql/src/components/GraphiQL.tsx

this never worked as expected, since when you open a new chrome tab -> you will get query/variables from the previous tab

[v4] remove `disableTabs` option

---

.changeset/few-steaks-clap.md
packages/graphiql-react/src/style/root.css
packages/graphiql/cypress/e2e/tabs.cy.ts
packages/graphiql/src/components/GraphiQL.tsx
packages/graphiql/src/components/__tests__/GraphiQL.spec.tsx
packages/graphiql/src/style.css

it's hard to find `Add tab` when there is only 1 tab
I think we should follow Chrome UX and show tabs even when there is 1 tab

[v4] show tabs even there is only 1 tab

---

packages/graphql-language-service-server/src/__tests__/MessageProcessor.spec.ts

I had always failed tests on my machine
after investigation, I found that `genSchemaPath` doesn't include `os.tempdir()` but on CI it pass
https://github.com/graphql/graphiql/blob/7404e8e6c62b06107f452142493297ec70f1649c/packages/graphql-language-service-server/src/__tests__/MessageProcessor.spec.ts#L67-L68
сс @acao

fix failed tests from `MessageProcessor.spec.ts` on MacOS

---

.changeset/old-zebras-knock.md
.changeset/shaggy-rice-doubt.md
packages/graphiql/cypress/e2e/tabs.cy.ts
packages/graphiql/src/components/GraphiQL.tsx
packages/graphiql/src/style.css

<s>I firstly did mistake and remove `#graphiql-session` id, I was thinking it nowhere used</s> but it was used by `aria-controls="graphiql-session"`

[v4] polish `tabs.cy` tests, remove `.graphiql-session` class

---

.changeset/serious-forks-sip.md
packages/graphiql-react/src/style/root.css
packages/graphiql/src/style.css

[v4] rollback `position: absolute` style for `.graphiql-logo` because tabs will behind logo

---

.changeset/add-on-prettify-callback.md
packages/graphiql-react/src/editor/hooks.ts
packages/graphiql-react/src/editor/query-editor.ts
packages/graphiql/cypress/e2e/prettify.cy.ts
packages/graphiql/resources/renderExample.js
packages/graphiql/src/components/GraphiQL.tsx

based on https://github.com/graphql/graphiql/pull/3640
fixes https://github.com/graphql/graphiql/issues/3385 https://github.com/graphql/graphiql/issues/1517

Add support for onPrettifyQuery callback to enable customised query formatting

---

.changeset/gold-ears-knock.md
packages/graphiql-toolkit/src/create-fetcher/__tests__/lib.spec.ts
packages/graphiql-toolkit/src/create-fetcher/createFetcher.ts
packages/graphiql-toolkit/src/create-fetcher/lib.ts
packages/graphiql-toolkit/tsconfig.json
packages/graphiql-toolkit/tsup.config.ts
packages/monaco-graphql/test/monaco-editor.test.ts

fixes https://github.com/graphql/graphiql/issues/3668

[@graphiql/toolkit] do not include `require` statements in ESM build, include `import` in esm and `require` in cjs builds

---

.changeset/lemon-mirrors-accept.md
packages/cm6-graphql/src/helpers.ts
packages/codemirror-graphql/src/utils/jump-addon.ts
packages/graphiql-react/src/editor/common.ts
packages/graphiql-react/src/explorer/components/doc-explorer.css
packages/graphiql-react/src/explorer/components/search.tsx
packages/graphiql-react/src/index.ts
packages/graphiql-react/src/utility/is-macos.ts
packages/graphiql/src/components/GraphiQL.tsx
packages/graphiql/test/beforeDevServer.js

fixes https://github.com/graphql/graphiql/issues/3436
https://github.com/user-attachments/assets/8baa492d-e9f2-45bd-b6db-12e33700e7fc
https://github.com/user-attachments/assets/7fced4de-c27b-4042-8b39-752d5f83d1ec

[graphiql] fix placeholder `⌘ K` in doc explorer search input for non mac devices, replace by `Ctrl K`

---

.github/workflows/pr-graphql-compat-check.yml

if we re-enable this github action, we should check against the latest alpha

update to v17-alpha.7, testing bug fixed

---

packages/graphiql/cypress/e2e/docs.cy.ts
packages/graphiql/package.json
packages/graphiql/test/beforeDevServer.js
packages/graphiql/test/e2e-server.js
yarn.lock

since we have rolled back to graphql@16 we are no longer testing incremental delivery and do not need to use graphql-helix for incremental delivery.

switch back to graphql-http

---

.github/workflows/pr-graphql-compat-check.yml

The matrix regression test is designed to show us _which_ versions have regressions, so cancelling them when one fails does not make sense. Let's try to make sure we peer review changes to these workflows!

Remove cancellation of regression tests

---

.changeset/neat-houses-explode.md
.github/workflows/pr-graphql-compat-check.yml
packages/cm6-graphql/package.json
packages/codemirror-graphql/package.json
packages/graphiql-plugin-code-exporter/package.json
packages/graphiql-plugin-explorer/package.json
packages/graphiql-react/package.json
packages/graphiql-toolkit/package.json
packages/graphiql/package.json
packages/graphql-language-service-cli/package.json
packages/graphql-language-service-server/package.json
packages/graphql-language-service/package.json
packages/monaco-graphql/package.json

after re-enabling the regression tests, we can see that we are no longer compatible with even the last major 15.x version of graphql, so we must remove it from `peerDependencies`

deprecate graphql@15 support

---

.changeset/three-lions-yawn.md
packages/vscode-graphql-syntax/grammars/graphql.json
packages/vscode-graphql-syntax/tests/__fixtures__/StarWarsSchema.graphql
packages/vscode-graphql-syntax/tests/__snapshots__/graphql-grammar.spec.ts.snap

See https://spec.graphql.org/October2021/#sec-Type-System.Directives

feature: Add syntax highlighting support for the repeatable keyword on a directive definition.

---

.changeset/four-dogs-swim.md
packages/graphiql-react/src/utility/context.ts

See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Deprecated_caller_or_arguments_usage
While it's helpful during development to have as much information as possible about which component doesn't have the necessary context, it's very not helpful to have the error message itself throw a blocking error due to this deprecated usage 😅 
In a future PR, it might be nice to rename the `caller` argument found throughout GraphiQL packages to something like `callerFn` for clarity, making it clear at a glance that it's a custom arg and not an attempt to access `Function.prototype.caller`.

fix: remove deprecated Function.prototype.caller reference

---

.changeset/two-owls-approve.md
packages/graphiql-toolkit/src/create-fetcher/lib.ts

fixes #2405 
switching to a type import will prevent bundling issues with legacy bundlers, as the older babel/ts transforms will know to strip type only imports before build time

fix: graphql-ws type import

---

.changeset/silly-nails-double.md
jest.config.base.js
packages/graphiql-react/src/editor/common.ts
packages/graphiql-react/src/editor/header-editor.ts
packages/graphiql-react/src/editor/query-editor.ts
packages/graphiql-react/src/editor/response-editor.tsx
packages/graphiql-react/src/editor/variable-editor.ts
packages/graphiql-react/vite.config.mts

These files absolutely shouldn't be included in `dist`, they should rely on an installed version from `node_modules`
```
dmytro@MacBook-Pro-9  ~/Desktop/GUILD/graphiql   do-not-bundle-codemirror  yarn workspace @graphiql/react build
yarn workspace v1.22.22
yarn run v1.22.22
$ rimraf dist types
$ tsc --emitDeclarationOnly && vite build
vite v5.3.6 building for production...
✓ 178 modules transformed.
dist/style.css                53.95 kB │ gzip: 10.24 kB
dist/forEachState.cjs.js       0.42 kB │ gzip:  0.25 kB │ map:   0.82 kB
dist/mode-indent.cjs.js        0.45 kB │ gzip:  0.28 kB │ map:   0.88 kB
dist/mode.cjs.js               0.89 kB │ gzip:  0.44 kB │ map:   1.66 kB
dist/codemirror.cjs.js         1.01 kB │ gzip:  0.50 kB │ map:   0.13 kB
dist/lint.cjs2.js              1.03 kB │ …
```

[1/3] [v3] Exclude `codemirror/...` and `codemirror-graphql/...` imports from bundle

---

.changeset/friendly-apricots-rest.md
packages/graphiql-react/src/explorer/components/search.tsx

closes https://github.com/graphql/graphiql/issues/3842

fix regression in documentation explorer search when clicking on results in dropdown

---

working-group/agendas/2025/03-Mar/11-graphiql-wg-march-2025.md

We may not actually need a meeting for this, but I'd like to discuss archiving GraphQL Playground. If we agree to do so, I think we ideally need a document that details how to move from Playground to GraphiQL - does such a document already exist? Then we'll update the playground README to point to it, and mark the repo as archived.
Main reason for archiving: it seems unmaintained, and most of the functionality is now available in GraphiQL?
cc @acao @dimaMachina @thomasheyenbrock @yaacovCR

Add Benjie and archiving Playground to next meeting

---

package.json

#3883 breaks release action, with the following errors https://github.com/graphql/graphiql/actions/runs/14684686099/job/41329136728
This PR rolls back the previous behaviour to unblock the release workflow. Let's figure out later what's a proper fix

Rollback #3883

---

.changeset/wild-paws-smash.md
packages/graphql-language-service-server/src/MessageProcessor.ts
packages/graphql-language-service-server/src/__tests__/MessageProcessor.test.ts

I recently submitted a (rejected) [PR in Neovim](https://github.com/neovim/neovim/pull/33692) because LSPs including `graphiql` and `vtsls` are returning empty hover \`contents\` arrays when there is no result, which is almost always the case for `graphiql` since it would only ever be expected to produce hover results for embedded `#graphql` query strings.
The effect of this is that `graphiql` is showing up in the Neovim LSP hover summary every time a hover request is made, even when there are no results, at locations in the code where results from `graphiql` would never be expected:
Since the [LSP spec](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_hover) allows a hover request to return \`null\`, this change is to align with the …

fix(graphql-language-service): return `null` instead of empty `contents` array when hover results are empty

---

.changeset/ten-badgers-crash.md
packages/cm6-graphql/package.json
yarn.lock

fix https://github.com/graphql/graphiql/pull/3789

chore(cm6-graphql): remove unneeded rollup/esbuild dev dependencies

---

.changeset/early-camels-protect.md
packages/graphiql-react/src/ui/tabs.css
packages/graphiql-react/src/utility/resize.ts
packages/graphiql/src/GraphiQL.spec.tsx
packages/graphiql/src/GraphiQL.tsx

fixes https://github.com/graphql/graphiql/issues/3931

add scroll-x to graphiql tabs area

---

packages/graphql-language-service-server/README.md
packages/graphql-language-service-server/src/MessageProcessor.ts
packages/graphql-language-service-server/src/__tests__/MessageProcessor.test.ts
packages/graphql-language-service-server/src/types.ts

Currently `locateCommand` is described as accepting "relay style" locations, which are interpreted as `uri:startLine:endLine`.
Relay actually uses `uri:line:column` which aligns with with how locations are represented in stack traces. 
The values are also being interpreted as 0 indexed, when I believe they are actually 1 index in relay and stack traces

[lsp] Fix parsing of relay style locations in locateCommand results

---

packages/graphql-language-service-server/README.md
packages/graphql-language-service-server/src/MessageProcessor.ts
packages/graphql-language-service-server/src/__tests__/MessageProcessor.test.ts
packages/graphql-language-service-server/src/types.ts

Revert "[lsp] Fix parsing of relay style locations in locateCommand results"

---

.changeset/nine-mayflies-teach.md
packages/graphql-language-service-server/README.md
packages/graphql-language-service-server/src/MessageProcessor.ts
packages/graphql-language-service-server/src/__tests__/MessageProcessor.test.ts
packages/graphql-language-service-server/src/types.ts

Revert "Revert "[lsp] Fix parsing of relay style locations in locateCommand results""

---

.vscode/settings.json

This PR updates the VSCode settings file so that the workspace version of TypeScript is used for the project rather than the latest version.

pin vscode tsc to workspace version

---

.changeset/tiny-adults-call.md
packages/graphiql-plugin-doc-explorer/src/context.ts
packages/graphiql-plugin-explorer/src/index.tsx
packages/graphiql-plugin-history/src/__tests__/components.spec.tsx
packages/graphiql-plugin-history/src/components.tsx
packages/graphiql-plugin-history/src/context.tsx
packages/graphiql-react/src/editor/components/header-editor.tsx
packages/graphiql-react/src/editor/components/response-editor.tsx
packages/graphiql-react/src/editor/components/variable-editor.tsx
packages/graphiql-react/src/editor/context.tsx
packages/graphiql-react/src/editor/header-editor.ts
packages/graphiql-react/src/editor/hooks.ts
packages/graphiql-react/src/editor/index.ts
packages/graphiql-react/src/editor/query-editor.ts
packages/graphiql-react/src/editor/response-editor.tsx
packages/graphiql-react/src/editor/tabs.ts
packages/graphiql-react/src/editor/variable-editor.ts
packages/graphiql-react/src/execution.tsx
packages/graphiql-react/src/index.ts
packages/graphiql-react/src/schema.ts
packages/graphiql-react/src/toolbar/execute.tsx
packages/graphiql-react/src/utility/context.ts
packages/graphiql-react/src/utility/index.ts
packages/graphiql-toolkit/src/create-fetcher/types.ts
packages/graphiql/src/GraphiQL.tsx

closes https://github.com/graphql/graphiql/issues/3969

revert https://github.com/graphql/graphiql/pull/3946 to have support multiple embedded graphiql instances on the same page

---

.changeset/good-turtles-speak.md
.gitignore
packages/graphiql-plugin-code-exporter/package.json
packages/graphiql-plugin-code-exporter/src/index.tsx
packages/graphiql-plugin-code-exporter/src/vite-env.d.ts
packages/graphiql-plugin-code-exporter/tsconfig.json
packages/graphiql-plugin-code-exporter/vite.config.mts
packages/graphiql-plugin-explorer/package.json
packages/graphiql-plugin-explorer/src/index.tsx
packages/graphiql-plugin-explorer/tsconfig.json
packages/graphiql-plugin-explorer/vite.config.mts
packages/graphiql/package.json
packages/graphiql/src/e2e.ts

in v5 we remove umd builds, previously marked deprecated in v4. we'll suggest use ESM-based CDNs such as esm.sh

graphiql 5: remove UMD builds

---

.changeset/gorgeous-lobsters-run.md
packages/graphiql-react/src/components/provider.tsx
packages/graphiql-react/src/utility/hooks.ts
packages/graphiql/cypress/e2e/headers.cy.ts
packages/graphiql/cypress/e2e/history.cy.ts
packages/graphiql/cypress/e2e/prettify.cy.ts
packages/graphiql/cypress/e2e/tabs.cy.ts
packages/graphiql/cypress/e2e/theme.cy.ts
packages/graphiql/src/e2e.ts

closes https://github.com/graphql/graphiql/issues/3495

graphiql 5: run cypress tests in React strict mode

---

DEVELOPMENT.md

Changed the required versions in DEVELOPMENT.md to yarn 4 and node 18 or greater, reflecting updated development environment prerequisites.

Update development requirements for yarn and node

---

.changeset/wise-deers-bake.md
packages/graphiql-react/package.json
packages/graphiql-react/src/monaco-editor.ts

closes https://github.com/graphql/graphiql/issues/4041

graphiql 5: fix `Fixes Uncaught Error: can't access property "offsetNode", hitResult is null` on Mozilla

---

.changeset/nervous-comics-happen.md
packages/graphiql-react/src/style/editor.css
packages/graphiql-react/src/utility/create-editor.ts

closes https://github.com/graphql/graphiql/issues/4040

fix incorrect caret position on Windows

---

.changeset/five-ghosts-bathe.md
.changeset/proud-bottles-punch.md
docs/migration/graphiql-2.0.0.md
docs/migration/graphiql-5.0.0.md
packages/graphiql-react/README.md
packages/graphiql-react/src/components/index.ts
packages/graphiql-react/src/components/markdown-content/index.css
packages/graphiql-react/src/components/operation-editor.tsx
packages/graphiql-react/src/components/provider.tsx
packages/graphiql-react/src/components/request-headers-editor.tsx
packages/graphiql-react/src/components/response-editor.tsx
packages/graphiql-react/src/components/variables-editor.tsx
packages/graphiql-react/src/constants.ts
packages/graphiql-react/src/stores/editor.ts
packages/graphiql-react/src/utility/create-editor.ts
packages/graphiql-react/src/utility/tabs.ts
packages/graphiql-toolkit/src/create-fetcher/types.ts
packages/graphiql/cypress/e2e/lint.cy.ts
packages/graphiql/cypress/support/commands.ts
packages/graphiql/src/GraphiQL.spec.tsx
packages/graphiql/src/GraphiQL.tsx
packages/graphiql/src/style.css

fix multiple GraphiQL instances, suffix a unique id for operation, request headers, variables and response URI.
E.g., the first GraphiQL instance will have:
- `1-operation.graphql`
- `1-request-headers.json`
- `1-variables.json`
- `1-response.json`
The 2nd instance will have:
- `2-operation.graphql`
- `2-request-headers.json`
- `2-variables.json`
- `2-response.json`
etc.

fix multiple GraphiQL instances, append an incremented number for operation, request headers, variables and reponse URI.

---

packages/graphiql/README.md
resources/custom-words.txt

closes https://github.com/graphql/graphiql/issues/3589

update graphiql docs, add Usage with a Custom Storage Namespace

---

.changeset/brave-points-bathe.md
packages/graphiql-react/src/constants.ts
packages/graphiql-react/src/utility/jsonc.ts

we don't need prettier on initial loading, it's only used by clicking on format query button/shortcut
diff from vite example
```diff
-dist/assets/index-BMgFrxsd.js             4,911.53 kB │ gzip: 1,339.77 kB
+dist/assets/index-BlpzusGL.js             4,221.28 kB │ gzip: 1,145.58 kB
```
cc @Benjie

graphiql 5: reduce bundle size, import `prettier` dynamically to avoid bundling Prettier

---

README.md

- This pull request fixes a broken link in the [README.md](https://github.com/graphql/graphiql/blob/main/README.md) file.
- Closes [issue - #3890](https://github.com/graphql/graphiql/issues/3890)
- Fixes an existing  Github PR Action failure, due to `prettier` checks 👨‍🔧
- [pull #4111](https://github.com/graphql/graphiql/pull/4111#issuecomment-3357350024)

docs(README): fix broken link and close #3890 👨‍🔧
