- css/show-hint.css
> Fix hint fonts

- example/README.md
> fix example readme

- README.md
> add live demo to readme

- package.json
- src/components/DocExplorer.js
- src/components/ExecuteButton.js
- src/components/GraphiQL.js
- src/components/QueryEditor.js
- src/components/ResultViewer.js
- src/components/VariableEditor.js
Thought this might be helpful during development :)
> Add PropTypes to components.

- src/components/GraphiQL.js
- `TypeError: Cannot read property 'storage' of undefined`
- `TypeError: this.storageGet is not a function`
> Fix GraphiQL component trying to use undefined properties

- example/index.html
Same as graphql/express-graphql#25
> Set `credentials` to `include` in graphQLFetcher

- css/app.css
- example/index.html
allows standalone GraphiQL app integrations - addresses #71
> separate out html/body styles to example app

- src/components/DocExplorer.js
> Escape HTML embedded description by sanitizing output

- src/components/GraphiQL.js
In addition to the refactoring, fixes a small bug is that if a schema isn't `undefined`, `keydown` event handler won't be attached, hence no Cmd + Enter action.
> refactor schema introspection fetch logic

- src/components/DocExplorer.js
- Debounce user actions typing in search box
- Limit the search results to 200 (including types and fields)
> Improve performance in Search in Documentation Explorer

- README.md
Intuitively I clicked on the screenshot to open the demo.
> Open live demo when clicking on the screenshot

- example/README.md
fix to the readme for people that don't have babel installed globally.
Personally had this problem and npm installing everything fixed it
> readme-fix

- README.md
- src/components/GraphiQL.js
> Added onToggleDocs prop

- example/index.html
Looks like this might have been missed in d5f027ae851d357c6d83e6b908baba888b5b7282
> Update React to v15 in example template

- css/app.css
- css/doc-explorer.css
- css/loading.css
- src/components/GraphiQL.js
> Use `className` for a top-level container instead of `id`

- example/index.html
> fix example code by including 'graphql' to the fetch URL

- css/codemirror.css
- example/build.sh
- example/package.json
- example/server.js
- src/components/ResultViewer.js
Fixes https://github.com/graphql/graphiql/issues/160
Also fixes a few issues found when using the `example` directory for testing. I could also write some scripts for watching fs changes to tighten the feedback loop when developing (currently you have to build and restart the example server).
> Adds in search functionality to result-viewer, bugfixes for example

- src/components/ExecuteButton.js
Travis is currently complaining about this ([example build](https://travis-ci.org/graphql/graphiql/builds/181706048)).
> Fix lint errror in ExecuteButton.js

- package.json
- yarn.lock
Closes #237
https://greenkeeper.io/
> chore(package): update babel-plugin-transform-object-rest-spread to version 6.20.2

- package.json
- yarn.lock
> chore(package): update watchify to version 3.8.0

- package.json
Closes #257
https://greenkeeper.io/
> chore(package): update jsdom to version 9.9.1

- package.json
Closes #278
https://greenkeeper.io/
> fix(package): update codemirror-graphql to version 0.6.1

- README.md
- css/app.css
- src/components/GraphiQL.js
- src/components/ToolbarButton.js
- src/components/ToolbarGroup.js
- src/components/ToolbarMenu.js
- src/components/ToolbarSelect.js
This adds a few more UI elements to the kit exported in `GraphiQL.Toolbar` which makes adding custom tools much easier.
Toolbar.Group: Groups together related elements.
Toolbar.Select: Basically a <select>.
Toolbar.Menu: A dropdown menu.
Also adds some minor stylistic improvments.
> [RFC] UI Toolkit

- css/doc-explorer.css
- src/components/DocExplorer.js
- src/components/DocExplorer/Argument.js
- src/components/DocExplorer/SearchBox.js
- src/components/DocExplorer/SearchResults.js
This PR improves the UI of the docs search bar, improves the behavior of searching, and allows searching of fields on a specific type in addition to searching an entire schema.
> Search more things

- README.md
Closes: https://github.com/graphql/graphiql/issues/302
> Fix Component names in usage example

- README.md
> Update links to live demo

- test/README.md
Kind of a trivial PR but I was working on something else and noticed that it now randomizes the port number.
> Update address step in test/README.md

- example/README.md
Similar to what @AGS- did in 7c8aa74b.
> Remove hard-coded port number from example README

- src/utility/getSelectedOperationName.js
`prevIndex` should be compared to `-1`, not to the falseyness.
> fix to properly check the index

- src/components/GraphiQL.js
> Update GraphiQL storage prop type

- README.md
Updated wepack link to their new site
> chore: update link to webpack + cosmetic fixes

- css/doc-explorer.css
This will facilitate text cope of field and class names
> Make the explorer title selectable

- package.json
- yarn.lock
Closes #411
https://greenkeeper.io/
> chore(package): update browserify to version 14.3.0

- package.json
> chore(package): update react-dom to version 15.5.4

- package.json
Would have caught:
https://github.com/graphql/graphiql/pull/461
> Run build in CI as part of test run to confirm it works

- package.json
> chore(package): update uglify-js to version 3.0.7

- src/components/GraphiQL.js
> Trigger events on history item selection

- package.json
- resources/build.sh
- yarn.lock
Closes: https://github.com/graphql/graphiql/issues/528
> Fix min build

- css/codemirror.css
https://github.com/graphql/graphiql/issues/545
> fix too strong css for cursor color for CodeMirror so it could be overriden

- package.json
- yarn.lock
As per this comment:
https://github.com/graphql/graphiql/issues/534#issuecomment-320768229
> Update codemirror-graphql dependency

- src/components/GraphiQL.js
> Follow-ups to doc explorer resize PR

- src/components/QueryEditor.js
- src/components/ResultViewer.js
- src/components/VariableEditor.js
cc @wincent @AGS- 
A normal search box goes away when the enter key is pressed one time, but this PR persists it throughout all searches.
> implement persistent search boxes in editors

- test/schema.js
- test/server.js
I ran prettier over the test folder because prettier added unnecessary formatting changes to the diff in PR #593. Hopefully this will mitigate this issue going forward.
> Run prettier over test/ folder

- README.md
fix invalid spread operator as mentioned in #615
> fix invalid spread operator

- css/app.css
Fixes regression introduced in fc4f1aae.
> Prevent toolbar menu drop-downs from being clipped

- README.md
> Update README.md to reflect codemirror theme api change

- src/components/DocExplorer/TypeDoc.js
Closes https://github.com/graphql/graphiql/issues/575
> The field description should be rendered as markdown

- css/app.css
> Remove border radius for document toggle button

- README.md
These badges will show the version on CDNJS & npm
> Add CDNJS & npm version badges in README.md

- .travis.yml
> Update npm credentials for repository

- src/components/ExecuteButton.js
- src/components/HistoryQuery.js
> Fix warnings for invalid className attributes

- package.json
> Upgrade codemirror-graphql to 0.8.3

- package.json
Ala https://github.com/graphql/graphql-js/pull/1855
Prevents causing issues similar to #797
> Add 'yarn check --integrity' to test script

- package.json
- yarn.lock
Manually confirmed that dev watch, build dist are the same
> upgrade browserify

- package.json
- resources/mocha-bootload.js
- yarn.lock
- `url` config is required for localStorage origin
- `prentendToBeVisual` is required for `document` properties and `requestAnimationFrame`/`cancelAnimationFrame`
- prettify resources/mocha-bootload.js
> upgrade jsdom as per #728 by @langpavel

- package.json
- yarn.lock
- tested manually just in case
- makes minified bundle slightly larger
> upgrade uglifyify and uglify-js

- README.md
GitHub can now syntax highlight GraphQL code
> Add syntax highlighting to Readme

- src/components/QueryEditor.js
- src/utility/normalizeWhitespace.js
>  Prevents crashing on Shift-Alt-Space and paste queries with no-break spaces

- css/doc-explorer.css
Fix issue that was introduced in 0e85c75 (#232)
> Fix: explorer title is not selectable anymore #778

- wg-agendas/05-14-2019.md
> add agenda to repository

- wg-agendas/05-14-2019.md
> Add Rikki Schulte to 5/14/19 agenda

- wg-agendas/05-14-2019.md
> Meeting Outcomes for 5/14

- package.json
- src/components/QueryEditor.js
- src/components/VariableEditor.js
- yarn.lock
The problem I'm having is that the `hint` DOM elements get created as children of `<body>`. If we pass in the container, they are created as children of the container which is more appropriate.
> hint DOM nodes liveoutside the codemirror DOM tree.

- src/components/GraphiQL.js
- src/utility/introspectionQueries.js
Very simply PR to add the operation name to the initial IntrospectionQuery.
> Add operation name to introspection query

- README.md
https://graphql.github.io/swapi-graphql/ works. Old one doesn't. It's taken more than 5 seconds to fix. Use this one instead, even if it's just temporary until you fix the old one.
Broken for at least 9 days: https://github.com/graphql/graphiql/issues/834
> Fix swapi demo link in README

- wg-agendas/06-18-2019.md
Confirmed I can't make this today I'm afraid - sorry folks! 
Will read the notes
> Scratch out orta form graphiQL WG

- packages/graphiql/example/README.md
> Docs(graphiql): update docs

- packages/graphql-language-service-interface/src/__tests__/getAutocompleteSuggestions-test.js
- packages/graphql-language-service-interface/src/getAutocompleteSuggestions.js
>  feat(language-service-interface): add __typename field suggestion against object type

- packages/graphiql/css/app.css
> Fix check mark not being visible

- packages/graphql-language-service-server/src/MessageProcessor.js
- packages/graphql-language-service-server/src/__tests__/MessageProcessor-test.js
- packages/graphql-language-service-server/src/findGraphQLTags.js
This adds support for autocomplete inside gql template tags which is useful in apollo projects.
> Add support for gql template tags

- wg-agendas/2019-08-21.md
> Add myself to next WG

- packages/graphiql-examples/cdn/index.html
Thanks to @marceloverdijk
Fixes #757
> Capital letter and punctuation fix

- packages/graphql-language-service-server/src/GraphQLCache.js
- packages/graphql-language-service-server/src/__tests__/GraphQLCache-test.js
> Invalidate schema cache on file changes to schemaPath

- packages/graphiql/src/components/QueryEditor.js
Keyboard bind edit for Prettify shortcut. Fix for #905
> fix for #905 - Prettify query shortcut change

- packages/graphiql/css/doc-explorer.css
Sorry for the delay :)
See https://github.com/graphql/graphiql/issues/949
> #949 Beautify code tag in doc explorer

- packages/graphiql/src/components/ToolbarButton.js
> Remove unofficial ARIA prop `aria-description`

- packages/graphiql/src/components/QueryHistory.js
> fix(graphiql): duplicate query history key issue, fixes #988

- packages/graphiql/package.json
- packages/graphiql/resources/webpack.config.js
- packages/graphiql/test/dev-server.js
- packages/graphql-language-service-utils/src/file.ts
- hmr bug was loading minified version in dev server index.html
- file resolution warnings from .d.ts and map files.
- we will want those for ts-loader soon!
- analyzer path for deploy previews at /analyzer
> fix: hmr, file resolution warnings

- packages/graphiql/README.md
There were some typos in the React example. This fixes those.
> Fix React example in README

- .github/workflows/issue.yml
this looks OK according to the docs
> chore: tweak issue action

- packages/graphiql/__mocks__/codemirror.js
- packages/graphiql/src/components/GraphiQL.js
- packages/graphiql/src/components/ResultViewer.js
- packages/graphiql/src/components/__tests__/GraphiQL.spec.js
- removed usage of findDOMNode and replaced with refs
- added tests to ensure behavior is not affected
- added more elements to be rendered by the mockCodeMirror for testing
> fix: remove use of find dom node

- packages/graphql-language-service-utils/src/validateWithCustomRules.ts
make sure to use `||` to exclude a few conditions for validation rules
> fix: exclusions rule for custom rules

- .github/workflows/main.yml
> Cleanup PR branches on merge

- .github/workflows/ci-merge.yml
vscode vs github ui for workflows gave me different linting?!
> ci: on pull_request types [closed]

- packages/graphql-language-service/src/__tests__/client-test.ts
- packages/graphql-language-service/src/client.ts
resolves #1319 by @yoshiakis
re-creates the already reviewed #1320 which for some reason is having a yarn.lock issue
> fix: error formatting, #1319

- working-group/agendas/2020-03-10.md
> Add me to the list

- working-group/minutes/2020-03-10.md
> chore: add 2020-03-10 meeting minutes

- packages/graphql-language-service-server/src/MessageProcessor.ts
fixes https://github.com/graphql/graphiql/issues/1307
> fix: typo to fix hover

- packages/graphql-language-service/src/cli.ts
> feat(cli): recommend matching commmands

- packages/graphiql/src/components/GraphiQL.tsx
Fix for https://github.com/graphql/graphiql/issues/1439
> fix: fix query argument missing from onEditQuery call

- packages/graphql-language-service-interface/package.json
- packages/graphql-language-service-server/package.json
- packages/graphql-language-service-types/package.json
- packages/graphql-language-service-utils/package.json
- packages/graphql-language-service/package.json
- yarn.lock
This upgrades `graphql-config` to their first `rc` version, which contains a feature I really want to use 👼
> chore: upgrade graphql-config

- working-group/agendas/2020-04-14.md
@acao As discussed over Discord, kindly add me to the attendee list for the 5th GraphiQL Working Group. Thank you! :)
> Add me as an attendee

- packages/graphiql/src/state/schemaActions.ts
- packages/graphiql/src/state/sessionActions.ts
* used the return type of the action creators for the action types
> feat: action types

- .eslintrc.js
- package.json
- packages/graphiql/src/new-components/Layout.stories.js
- packages/graphql-language-service-utils/src/__tests__/file-test.ts
- resources/pretty.js
- yarn.lock
Changes in this pull request:
- As requested, added eslint plugin to validate the rules of hooks
- Fixed components in Layout.Stories.js that failed this linting rule
- Fixed a windows specific issue to the pretty.js formatting script
- Fixed a unit test that was failing on windows due to differences in paths (`/` vs` \`)
> chore: fixed minor platform specific test failures and lint errors

- packages/graphql-language-service-parser/src/CharacterStream.ts
- packages/graphql-language-service-parser/src/RuleHelpers.ts
- packages/graphql-language-service-parser/src/Rules.ts
- packages/graphql-language-service-parser/src/onlineParser.ts
- packages/graphql-language-service-types/src/index.ts
- packages/graphql-languageservice/README.md
- packages/graphql-languageservice/package.json
- packages/graphql-languageservice/src/index.ts
- packages/graphql-languageservice/tsconfig.esm.json
- packages/graphql-languageservice/tsconfig.json
- resources/tsconfig.build.cjs.json
- resources/tsconfig.build.esm.json
> feat: new graphql-languageservice package

- packages/graphql-language-service-interface/src/GraphQLLanguageService.ts
addresses some outstanding exception trapping i spotted, related to #1481 and #1482. @divyenduz @zth what do you think?
> improvement: don't trap these other schema loading errors

- packages/graphql-language-service-interface/src/GraphQLLanguageService.ts
- packages/graphql-language-service-interface/src/__tests__/getDiagnostics-test.ts
- packages/graphql-language-service-interface/src/getDiagnostics.ts
- packages/graphql-language-service-interface/src/index.ts
- packages/graphql-language-service-server/src/Logger.ts
This just seemed like a great idea in the monaco effort, and will come in handy when that gets merged here real soon. also takes weight of the monaco PR
> refactor: friendlier to read diagnostic codes

- examples/graphiql-parcel/README.md
- examples/graphiql-parcel/package.json
- examples/graphiql-parcel/src/index.html
- examples/graphiql-parcel/src/index.tsx
- examples/graphiql-parcel/tsconfig.json
> feat: Add Parcel Example for GraphiQL

- packages/graphiql/src/api/actions/sessionActions.ts
- packages/graphiql/src/api/providers/GraphiQLSessionProvider.tsx
- packages/graphiql/src/components/GraphiQL.tsx
This PR adds context for session tabs
@acao can you review this PR
> feat: add tabs in session context

- packages/graphiql/src/components/common/Layout.stories.tsx
- packages/graphiql/src/components/common/Nav.stories.tsx
- packages/graphiql/src/components/common/Nav.tsx
Improved Nav Component to allow children and added stories file for it.
@acao can you review this
> chore: improve nav component

- packages/graphiql/src/components/HistoryQuery.tsx
- packages/graphiql/src/components/QueryEditor.tsx
- packages/graphiql/src/new-components/Toolbar/Tabs.tsx
- packages/graphiql/src/new-components/themes/decorators.tsx
- packages/graphiql/src/new-components/themes/types.ts
- packages/graphiql/tsconfig.json
> fix: graphiql non-relative import issues (#1534) fixes #1530

- examples/monaco-graphql-webpack/src/index.ts
- packages/monaco-graphql/package.json
- packages/monaco-graphql/src/GraphQLWorker.ts
- packages/monaco-graphql/src/typings/monaco.d.ts
- use reference types=
- export typings properly
- fix monaco.d.ts
> improvement: cleaner types for monaco-graphql

- packages/graphiql/README.md
> docs: version notices for the GraphiQL readme

- packages/graphiql/src/components/GraphiQL.tsx
This issue is related to (https://github.com/graphql/graphiql/issues/1515)(1515)
React implementation of network cancelation
> fix: Safe setState

- packages/graphiql/src/components/GraphiQL.tsx
Closes #1515 
Move all functionality from `componentWillUnMount` lifecycle
@acao can you review this PR
> fix: Move all componentWillUnMount functionality to respective events

- packages/graphiql/src/components/GraphiQL.tsx
@acao this PR will fix the storage issue
> fix: call debounce statements as they are functions

- packages/graphiql/src/components/HeaderEditor.tsx
- packages/graphiql/src/components/QueryEditor.tsx
- packages/graphiql/src/components/ResultViewer.tsx
- packages/graphiql/src/components/VariableEditor.tsx
- packages/graphiql/src/utility/onHasCompletion.ts
ref #118
cc @acao this issue was re-introduced in https://github.com/graphql/graphiql/pull/1242
> fix: fix server side rendering by using type only codemirror import

- packages/graphiql/src/components/HeaderEditor.tsx
- packages/graphiql/src/components/VariableEditor.tsx
@acao New release would be great :wink:
> fix: more server side rendering fixes

- packages/graphiql/src/components/GraphiQL.tsx
This PR is to add headers to local storage.
> fix: Set headers to localstorage

- packages/graphiql/README.md
This PR is to add `shouldPersistHeaders` prop in README
> chore: Add `shouldPersistHeaders` prop in README.md

- netlify.toml
- package.json
- packages/graphiql/.gitignore
- packages/graphiql/index.html
- typedoc.json
- yarn.lock
we removed it because the netlify build was taking so long! need to split into seperate actions
> ci: reintroduce docs build

- README.md
- packages/monaco-graphql/README.md
This PR is fix the type in typedocs links
> chore: fix typedocs link

- packages/graphiql/src/components/DocExplorer/TypeDoc.tsx
Fixes: #1599,
This PR is to add only the deprecated fields to the deprecated list.
> chore: add only the fields which are deprecated to deprecation list

- packages/graphql-language-service-cli/README.md
- packages/graphql-language-service-cli/src/cli.ts
- packages/graphql-language-service-server/README.md
- packages/graphql-language-service-server/src/GraphQLCache.ts
- packages/graphql-language-service-server/src/MessageProcessor.ts
- packages/graphql-language-service-server/src/__tests__/GraphQLCache-test.ts
- packages/graphql-language-service-server/src/__tests__/MessageProcessor-test.ts
- packages/graphql-language-service-server/src/findGraphQLTags.ts
- packages/graphql-language-service-server/src/parseDocument.ts
- packages/graphql-language-service-server/src/startServer.ts
- packages/graphql-language-service-server/src/types.ts
- cache paths were not matching up b/c of last minute change
- improve documentation, improve underlying interfaces
- add all loadConfig options as startServer param, deprecate configDir
> fix: pre-cacheing schema bugs, new server config options

- packages/graphql-language-service-server/package.json
- packages/graphql-language-service-server/src/MessageProcessor.ts
- yarn.lock
write the schema async so we know we are ready to read it.
> fix: recursively write tmp directories, write schema async

- packages/graphiql/src/components/GraphiQL.tsx
Fixes #1650 
This PR is to fix the history pane and documentation explorer pane state
> chore: fix handle history pane and handle documentation explorer state

- packages/graphql-language-service-server/src/findGraphQLTags.ts
See issue https://github.com/prisma-labs/vscode-graphql/issues/176.
Related to PR https://github.com/prisma-labs/vscode-graphql/pull/211
> improvement: associate with graphqls file extension

- packages/graphql-language-service-server/src/MessageProcessor.ts
- cleanup
- swallow definition exceptions for now
- improve nullish coalescing/inline condition for retrieving `useSchemaFileDefinitions` setting
> fix: useSchemaFileDefinitions, cleanup

- packages/graphql-language-service-server/README.md
graphql-config - https://graphql-config.com/introduction
loadConfig - https://graphql-config.com/load-config
Language Server Protocol - https://microsoft.github.io/language-server-protocol/specification
> Fixed broken links

- packages/graphiql/src/components/DocExplorer/SchemaDoc.tsx
Resolves: https://github.com/graphql/graphiql/issues/656
> fix: display schema description if available

- packages/graphiql/src/components/GraphiQL.tsx
> feat: also support fetcher functions that return Promise<Observable> or Promise

- packages/graphiql/src/components/GraphiQL.tsx
Closes https://github.com/graphql/graphiql/issues/1638
> fix: unify how observables are consumed within GraphiQL

- packages/graphql-language-service-cli/README.md
> chore: fix broken graphql-config link in graphql-language-service-cli readme

- README.md
Signed-off-by: Brian Warner <brian@bdwarner.com>
> Add instructions for EasyCLA

- packages/graphiql-create-fetcher/package.json
- packages/graphiql-create-fetcher/src/lib.ts
- packages/graphiql/cypress/integration/incrementalDelivery.spec.ts
- packages/graphiql/src/components/GraphiQL.tsx
- yarn.lock
Upgrades `meros ` which now support multiple payloads per yield for a more optimized experience.
> feat: upgrades meros to not eagerly yield

- DEVELOPMENT.md
- README.md
Minor change updating instructions.
Signed-off-by: Brian Warner <brian@bdwarner.com>
> Update EasyCLA info

- README.md
I made the choice of adding this to the readme w/o consulting colleauges
My co-maintainers are being forced to take sides and this is unfair
The technical steering commitee will review this decision, & decide what best reflects our interests together.
First and foremost, they will decide on a policy to make sure a rouge maintainer action like this cannot happen again without a decision making process involving the TSC.
I apologize for making this choice but not what I said, and will continue supporting an end to the apartheid in my own personal venues.
Please leave my co-maintainers and colleauges be.
> fix: remove statement pending discussion

- packages/graphiql/README.md
I tried UMD as per the README, but it did not work.
It seems that the arguments written in the README are wrong.
> docs: Fix usage of graphiql in umd

- README.md
I would like to add the prolific @dotansimha as a co-maintainer to the repository :)
> Proposal: add @dotansimha as co-maintainer

- LICENSE
See https://github.com/graphql/graphql-wg/issues/662
> Evergreen LICENSE/copyright

- .changeset/lovely-cycles-call.md
- packages/graphiql-toolkit/docs/create-fetcher.md
- packages/graphiql-toolkit/package.json
- packages/graphiql-toolkit/src/create-fetcher/lib.ts
- packages/graphiql-toolkit/src/create-fetcher/types.ts
- packages/graphiql/cypress/integration/docs.spec.ts
- packages/graphiql/cypress/integration/graphqlWs.spec.ts
- packages/graphiql/cypress/integration/init.spec.ts
- packages/graphiql/package.json
- packages/graphiql/resources/renderExample.js
- packages/graphiql/resources/webpack.config.js
- packages/graphiql/src/components/GraphiQL.tsx
- packages/graphiql/test/afterDevServer.js
- packages/graphiql/test/e2e-server.js
- packages/graphiql/test/schema.js
- packages/graphiql/tsconfig.esm.json
- packages/graphiql/tsconfig.json
- yarn.lock
Should take care of #2006 and others
> graphql-ws upgrade, move to peerDependency

- packages/graphiql/README.md
> Absolute links to examples, to work on npm listing

- .changeset/lucky-hairs-flash.md
- packages/codemirror-graphql/src/utils/mode-factory.ts
> codemirror-graphql's mode-factory.ts to use graphql-language-service

- .changeset/orange-trees-relate.md
- packages/codemirror-graphql/package.json
Added cm6-legacy to files list of codemirror-graphql
> Added cm6-legacy to files list

- .changeset/ninety-wasps-grin.md
- packages/graphiql/package.json
Follow up to #2047 - hopefully my last PR for a bit - sorry this wasn't included in that one.
> Include source maps for minified JS and CSS in the graphiql package.

- .github/workflows/deploy-preview.yml
until we fix deploy previews for forks
> fail deploy previews quietly for now

- .changeset/shiny-starfishes-reflect.md
- .github/workflows/deploy.yml
- examples/monaco-graphql-webpack/package.json
- packages/graphql-language-service/src/LanguageService.ts
- packages/monaco-graphql/README.md
- packages/monaco-graphql/package.json
- yarn.lock
- fix deploy on merge to main
- make sure to pass the optional external fragments on validation
- some more docs
> a few tiny fixes for monaco-graphql

- .github/workflows/release.yml
Based on the warning in the release output
> fix: changesets action version

- .changeset/nasty-hornets-mix.md
- packages/graphql-language-service-server/package.json
- packages/graphql-language-service-server/src/__tests__/MessageProcessor-test.ts
- packages/graphql-language-service-server/src/findGraphQLTags.ts
this adds some support for template strings with variable replacement expressions.
they will be replaced by a blank whitespace character.
characters *will* be off for the same line
> support for template strings with replacement expressions

- working-group/agendas/2022-01-11.md
- working-group/minutes/2022-01-11.md
We actually had Working Group 8 on Jan 11, 2022. However, we didn't add the agenda or meeting minutes so far.
> Add Working Group 8 agenda and minutes

- working-group/agendas/2022-22-02-monaco.md
We can make this into a monthly thing, as we focus on issues that are a bit too low level for graphiql WG, or for requirements beyond the needs of graphiql (such as SDL editing)
> Add monaco-graphql special wg minutes

- packages/graphiql-toolkit/docs/create-fetcher.md
This PR incorrect subscription client object initialization.
> Fix legacy client fetcher example code

- README.md
Based on discussion and guidelines that we've had up for discussion for a very long time in https://github.com/graphql/graphql-wg/pull/696, I'm cleaning up this README file.
Please don't take this PR as a value statement on this particular message. The process I'm working through is to first get us to a clean state, after which we can ensure any future messages atop that clean slate adhere to that policy.
Please see our TSC document with a section describing this:
https://github.com/graphql/graphql-wg/blob/main/GraphQL-TSC.md#speaking-on-behalf-of-the-graphql-project
> Cleaning up README based on GraphQL project voice rules

- .changeset/cold-monkeys-compare.md
Add missing changeset from https://github.com/graphql/graphiql/pull/2220
> chore: add changeset for externalFragments fix

- .github/workflows/pr-tests.yml
> update node version matrix

- working-group/agendas/2022-03-08.md
> Add password to GraphiQL call

- packages/graphql-language-service-server/src/GraphQLCache.ts
> fix: typo in GraphQLCache.ts

- .changeset/giant-hats-camp.md
- packages/graphql-language-service-cli/package.json
- yarn.lock
we need to look into why changesets is not resolving lockfile changes for implicit patch increments?!
> fix lockfile and imports from LSP merge

- .changeset/spicy-suits-ring.md
- packages/graphql-language-service-cli/package.json
> Re-add graphql-language-service-server as a dep

- packages/vscode-graphql/package.json
> use release not publish script

- .changeset/light-rocks-smell.md
- packages/graphiql/src/components/GraphiQL.tsx
- yarn.lock
> fix: A query request was sent for subscriptions after tab change

- .changeset/old-laws-compare.md
- packages/graphiql/src/components/GraphiQL.tsx
> Fix wrong request type after restoring a subscription

- packages/graphql-language-service/src/utils/validateWithCustomRules.ts
> Fix typo in validateWithCustomRules.ts

- packages/vscode-graphql/esbuild.js
> fix esbuild script

- .eslintignore
- .eslintrc.js
- packages/graphiql-2-rfc-context/src/components/GraphiQL.tsx
Fragments should contain more than one child
> enable `react/jsx-no-useless-fragment`

- packages/graphiql-toolkit/src/create-fetcher/types.ts
> Fix typo in types.ts

- packages/graphiql/cypress/integration/tabs.spec.ts
- packages/graphiql/cypress/support/commands.ts
Adding some more tests to make sure that the upcoming refactoring of the tabs state hopefully doesn't break anything! 😊
> add e2e test suite for tabs

- .changeset/smooth-badgers-compete.md
- packages/monaco-graphql/src/LanguageService.ts
- packages/monaco-graphql/src/typings/index.ts
- packages/monaco-graphql/src/workerManager.ts
renamed all `exteral` cases since it's a typo
added a changeset
> rename `exteralFragmentDefinitions` to `externalFragmentDefinitions`

- .changeset/dull-pears-clap.md
- .changeset/early-roses-shop.md
I forgot to update the changeset messages in #2461 after changing the component to a hook
> correct changeset messages

- .github/workflows/release.yml
- packages/vscode-graphql/package.json
This should be the last ingredient to getting the vscode release workflow working!
> fix release script, expect default env args

- .changeset/strange-schools-wave.md
- packages/graphiql/src/components/GraphiQL.tsx
> fix the default value of the `headerEditorEnabled` prop

- .changeset/fair-snails-drum.md
- packages/graphiql-react/package.json
- packages/graphiql-react/src/editor/hooks.ts
- packages/graphiql/cypress/integration/prettify.spec.ts
- yarn.lock
Inspired by the prettier support we introduced in `monaco-graphql` in 2020! And endless demands to add prettier support to graphiql
> prettier!!!

- .changeset/fair-snails-drum.md
- packages/graphiql-react/package.json
- packages/graphiql-react/src/editor/hooks.ts
- packages/graphiql/cypress/integration/prettify.spec.ts
- yarn.lock
I had meant to merge #2501 and not  graphql/graphiql#2502. This change requires more input
> Revert "prettier!!!"

- packages/graphiql/README.md
> fix API docs link

- packages/graphiql/cypress/integration/docs.spec.ts
> fix race condition in test by waiting for search results to appear

- custom-words.txt
add Chnapy from changelog step
we need to automate adding new usernames from changelog file on the changeset task somehow, or this will break on every release with a new contributor!
> fix cspell config from last release

- packages/graphiql-react/src/editor/common.ts
Following up on https://github.com/graphql/graphiql/pull/2545#discussion_r915048473
> avoid mapping over array without changing it

- .changeset/smooth-countries-shout.md
- packages/graphiql-react/src/ui/index.ts
- packages/graphiql-react/src/ui/spinner.css
- packages/graphiql-react/src/ui/spinner.tsx
- packages/graphiql/__mocks__/@graphiql/react.tsx
- packages/graphiql/src/components/DocExplorer.tsx
- packages/graphiql/src/components/GraphiQL.tsx
- packages/graphiql/src/style.css
Part of #2325 
Small PR that extracts a reusable loading spinner component into `@graphiql/react`.
> [redesign] loading spinner

- .changeset/five-pillows-fail.md
- .changeset/tender-impalas-provide.md
- packages/graphiql-react/package.json
- packages/graphiql-react/src/style/root.css
- packages/graphiql-react/src/ui/button.css
- packages/graphiql-react/src/ui/button.tsx
- packages/graphiql-react/src/ui/dialog.css
- packages/graphiql-react/src/ui/dialog.tsx
- packages/graphiql-react/src/ui/index.ts
- packages/graphiql-toolkit/src/storage/base.ts
- packages/graphiql/__mocks__/@graphiql/react.tsx
- packages/graphiql/src/components/GraphiQL.tsx
- packages/graphiql/src/style.css
- yarn.lock
Part of #2325
This adds the settings dialog. The only option for now is to clear the storage, theme selection will be added in the next PR.
> [redesign] add settings dialog

- .changeset/thick-years-sort.md
just this small but important adjustment to reflect the scope of changes
> fix changeset for LSP ecosystem

- .changeset/lovely-dancers-complain.md
just enough detail and points of reference for everyone
> edit changelog entry for syntax extension release

- package.json
- packages/graphql-language-service-server/package.json
- packages/graphql-language-service-server/src/__tests__/GraphQLCache-test.ts
- packages/graphql-language-service/package.json
- packages/vscode-graphql/package.json
- yarn.lock
> pin undici, config versions in lsp to fix introspection bug

- packages/vscode-graphql-syntax/README.md
> revise syntax extension readme

- packages/graphiql/src/style.css
A simple, initial PR to ensure that I'm branching/PRing correctly for v2 work.
I branched off of `graphiql-v2` for this fix and would like to merge this commit into `graphiql-v2`. Is this the correct process?
> adds styles to contain the result window above any footer content

- packages/graphiql-react/src/editor/response-editor.tsx
Follow up to #2644 where I forgot to add this effect dependency
> add missing effect dep in response editor

- .github/workflows/pr-graphql-compat-check.yml
- .github/workflows/release.yml
this _should_ hopefully fix the PR merge workflow cypress build
> fix tests on PR merge

- .changeset/grumpy-bags-cheat.md
- packages/graphiql/src/components/DocExplorer.tsx
- packages/graphiql/src/components/DocExplorer/FieldDoc.tsx
- packages/graphiql/src/components/DocExplorer/SearchBox.tsx
- packages/graphiql/src/components/DocExplorer/TypeDoc.tsx
- packages/graphiql/src/components/GraphiQL.tsx
- packages/graphiql/src/components/QueryHistory.tsx
- packages/graphiql/src/components/Tabs.tsx
- packages/graphiql/src/components/ToolbarButton.tsx
Fixes #2677 
In general adding this attribute is a best practice in terms of a11y. I'll follow up with a PR that makes sure we also do this in v2.
> add `type="button"` attribute to all buttons

- .changeset/strange-mirrors-yell.md
- packages/graphiql/package.json
- packages/graphiql/src/cdn.ts
This should allow us to make an example of GraphiQL+Explorer that works via the CDN bundle :)
> Add react hooks to CDN

- .changeset/angry-phones-repair.md
- packages/graphiql/src/components/GraphiQL.tsx
- packages/graphiql/src/style.css
…so that more developers will find the repository and potentially turn into contributors!
> Link the GraphiQL logo to this repository

- packages/graphiql-plugin-explorer/examples/index.html
Just a small fix, otherwise this works pretty well!
> Use GraphiQLPluginExplorer.useExplorerPlugin instead of useExplorerPlugin

- packages/graphiql-toolkit/docs/create-fetcher.md
documenting this config option would settle a lot of confusion right now 😆
> update createGraphiQLFetcher docs

- .changeset/rotten-shoes-cry.md
- packages/graphiql-react/src/explorer/components/search.tsx
> don't propagate events too far upwards

- .changeset/good-zoos-rhyme.md
- packages/graphiql-plugin-explorer/README.md
- packages/graphiql-plugin-explorer/package.json
> remove `type` property from `package.json`

- .changeset/unlucky-poets-invent.md
- packages/vscode-graphql/package.json
- yarn.lock
use the fix version that @MariaSolOs found for #2671 !
> pin vscode-languageclient

- README.md
this wasn't documented very well, need a few more waypoints, starting with this one
> document language service merger

- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/graphiql-bug.yml
- .github/ISSUE_TEMPLATE/graphiql-feature.md
- .github/ISSUE_TEMPLATE/language-server-bug.yml
- .github/ISSUE_TEMPLATE/monaco-graphql-bug.yml
- .github/ISSUE_TEMPLATE/monaco-graphql-feature.yml
- .github/ISSUE_TEMPLATE/vscode-syntax-bug.yml
Just this to start? And then keep improving as we go?
> finally add issue forms & templates

- .github/ISSUE_TEMPLATE.md
- .github/ISSUE_TEMPLATE/graphiql-feature.md
- .github/ISSUE_TEMPLATE/language-server-feature.md
- .github/ISSUE_TEMPLATE/monaco-graphql-feature.md
- .github/ISSUE_TEMPLATE/monaco-graphql-feature.yml
Leave feature requests open ended
Swap "description" for "about"
> enhance issue templates further

- .changeset/sour-kangaroos-sing.md
- packages/graphiql-react/src/plugin.tsx
> avoid resetting visible plugin state when explorer or history context changes

- .changeset/wet-planets-boil.md
- packages/monaco-graphql/src/initializeMode.ts
this should fix some of the errors users have been seeing
> only initialize the mode once

- .changeset/tiny-mirrors-drive.md
Forgot to one here: https://github.com/graphql/graphiql/pull/2814
> add missing changeset

- .eslintrc.js
- package.json
- yarn.lock
> remove `eslint-plugin-babel`

- examples/graphiql-explorer/src/vite-env.d.ts
> remove `examples/graphiql-explorer`

- DEVELOPMENT.md
fixes https://github.com/graphql/graphiql/issues/2110
> fix broken link in `DEVELOPMENT.md`

- .changeset/hip-maps-tickle.md
- packages/graphiql-react/src/ui/tabs.css
- packages/graphiql/src/components/GraphiQL.tsx
- packages/graphiql/src/style.css
> fix tabbar overflow

- .changeset/honest-windows-scream.md
- packages/graphiql/src/cdn.ts
> removes regenerator-runtime from cdn.ts

- .prettierrc
Hoping this fix will help us https://github.com/changesets/changesets/issues/774
> fix changelog formatting issue hopefully

- .changeset/poor-mirrors-learn.md
- .eslintrc.js
- packages/graphiql-react/src/editor/components/image-preview.tsx
- packages/graphiql-react/src/editor/tabs.ts
- packages/graphiql-react/src/explorer/components/search.tsx
- packages/graphiql-react/src/schema.tsx
- packages/graphiql-toolkit/src/graphql-helpers/auto-complete.ts
- packages/graphiql-toolkit/src/storage/history.ts
- packages/graphql-language-service-server/src/GraphQLCache.ts
- packages/graphql-language-service-server/src/GraphQLLanguageService.ts
- packages/graphql-language-service-server/src/Logger.ts
- packages/graphql-language-service-server/src/MessageProcessor.ts
- packages/graphql-language-service/src/interface/getOutline.ts
- packages/graphql-language-service/src/utils/fragmentDependencies.ts
- packages/monaco-graphql/src/LanguageService.ts
- packages/monaco-graphql/src/graphqlMode.ts
- packages/vscode-graphql-execution/src/helpers/source.ts
like removing unused variables
> enable `unicorn/prefer-optional-catch-binding` rule

- .changeset/smooth-cycles-behave.md
- packages/cm6-graphql/tsconfig.esm.json
add project reference for cm6 to graphql LS
> fix netlify build

- .changeset/shiny-zebras-hide.md
- packages/graphql-language-service-server/package.json
- yarn.lock
fixes https://github.com/graphql/graphiql/issues/3013
> update babel, support `satisfies` operator

- .github/workflows/release.yml
This will fix the Version Packages pr on the next merge with a changeset
> format changes on changesets version before publish

- .changeset/config.json
- .changeset/real-teachers-smile.md
- .github/workflows/release.yml
- package.json
According to the last error, the changesets action needs a simpler command. Hopefully this doesn't cause a git conflict. I may have to disable git commit in the changesets config and manually commit?
> Format on version

- packages/graphiql/README.md
https://github.com/facebook/react/blob/6ff1733e63fdb948ae973a713741b4526102c73c/CHANGELOG.md?plain=1#L1678
> do not suggest `ReactDOM.render(..., document.body)` as it's anti pattern!

- .eslintrc.js
- examples/graphiql-webpack/src/index.jsx
- packages/codemirror-graphql/src/utils/hintList.ts
- packages/graphiql-react/src/explorer/components/search.tsx
- packages/graphiql-react/src/history/components.tsx
- packages/graphiql-toolkit/src/graphql-helpers/__tests__/merge-ast.spec.ts
- packages/graphiql-toolkit/src/graphql-helpers/auto-complete.ts
- packages/graphiql/cypress/support/commands.ts
- packages/graphiql/cypress/tsconfig.json
- packages/graphql-language-service/src/interface/autocompleteUtils.ts
- packages/graphql-language-service/src/parser/__tests__/OnlineParserUtils.ts
https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-string-replace-all.md
> [ESLint] enable `unicorn/prefer-string-replace-all` rule

- .changeset/witty-owls-burn.md
- .eslintrc.js
- packages/graphiql-react/src/editor/tabs.ts
- packages/graphiql-toolkit/src/graphql-helpers/auto-complete.ts
- packages/graphiql/resources/renderExample.js
- packages/graphql-language-service/src/parser/CharacterStream.ts
> [ESLint] Prefer String#slice() over String#substr() and String#substring()

- packages/graphiql-react/package.json
netlify is reporting this package missing, but it appears to already be present, thus no change to the lockfile
> fix new build issue

- packages/graphiql-react/src/theme.ts
https://developer.mozilla.org/en-US/docs/Web/API/Element/classList
> refactor `classList.remove` since he accept multiple arguments

- README.md
vscode-graphql was never added to the root readme!
> add vscode-graphql to the readme

- package.json
> fix: build on release

- netlify.toml
If this deploy preview passes, we will know for a fact that this fixes the issue.
I was able to confirm that this config change worked in the UI when re-deploying the last deploy preview failure.
> use netlify.toml again

- .changeset/short-bears-taste.md
- packages/graphql-language-service-server/src/GraphQLCache.ts
Seems to resolve: https://github.com/graphql/graphiql/issues/3153
> GraphQLCache: fix multiple projects in one graphqlrc

- .changeset/fifty-roses-heal.md
- packages/graphiql-react/src/editor/style/codemirror.css
Reopened PR of https://github.com/graphql/graphiql/pull/3032 after CLA issues
> fix: limit all codemirror css rules to .graphiql-container

- .changeset/red-apples-breathe.md
- packages/graphiql-react/src/style/root.css
fixes https://github.com/graphql/graphiql/issues/3144
> remove confusing ligatures, set `font-variant-ligatures: none`

- README.md
fix https://github.com/graphql/graphiql/issues/3221
@TuvalSimha for some reason redirect from graphql.org are broken https://github.com/search?q=repo%3Agraphql%2Fgraphql.github.io+swapi-graphql&type=code
> fix livedemo link Update README.md

- .github/workflows/release.yml
this is more descriptive, prevents confusion because PAT_TOKEN could refer to anything
> use VSCE_PAT only

- .changeset/hip-knives-sniff.md
- .changeset/pre.json
I think we tried this before, but let's see what happens?
this would free up the LSP side of the ecosystem
> try removing some packages from pre.json

- .changeset/little-stingrays-sin.md
- packages/graphiql-plugin-code-exporter/package.json
- packages/graphiql-plugin-code-exporter/vite.config.ts
- packages/graphiql-plugin-explorer/package.json
- packages/graphiql-plugin-explorer/vite.config.ts
| before                                                                                  | after |
|:---------------------------------------------------------------------------------------------------:|:--------------:|
| ![image](https://github.com/graphql/graphiql/assets/7361780/25f523a2-5aa3-4274-86ed-be9a24cd5154) |   ![image](https://github.com/graphql/graphiql/assets/7361780/a61a1f91-b79d-4d4d-b17a-6200587280b5)        |
| before                                                                                  | after |
|:---------------------------------------------------------------------------------------------------:|:--------------:|
| ![image](https://github.com/graphql/graphiql/assets/7361780/98389e68-99da-4219-a791-25c11ef4afb6) | …
> [plugin-code-exporter/plugin-explorer]: exclude peer dependencies and dependencies from bundle

- README.md
provide waypoints for cm5 vs cm6 users
> add cm6-graphql to the readme

- README.md
> fix header link for cm6-graphql

- packages/vscode-graphql-execution/package.json
- packages/vscode-graphql-syntax/.vscodeignore
- packages/vscode-graphql-syntax/package.json
- packages/vscode-graphql/package.json
- yarn.lock
> Fix open vsx publish

- .codecov.yml
- .github/workflows/pr-e2e-tests.yml
- .github/workflows/pr-tests.yml
re-adding this so that we get a coverage baseline again (otherwise codecov reports will always show huge coverage debt)
> fix: run tests against main for baseline

- .codecov.yml
just to make the pipeline green again
> set target really low

- .changeset/pre.json
it seems this is all we need to leave pre-release mode for now
> leave pre-release mode

- cspell.json
- custom-words.txt
- package.json
- packages/vscode-graphql/README.md
fixes https://github.com/graphql/graphiql/issues/3258
> ignore package.jsons for cspell

- .changeset/six-otters-study.md
- package.json
wsrun is passing the `main` argument accidentally
> fix ovsx release

- .changeset/four-parrots-warn.md
- .changeset/orange-turkeys-draw.md
- packages/vscode-graphql-execution/esbuild.js
- packages/vscode-graphql-execution/package.json
- packages/vscode-graphql/esbuild.js
- packages/vscode-graphql/package.json
> Fix vscode

- .codecov.yml
> lower codecov threshold

- .github/workflows/pr-graphql-compat-check.yml
to fix broken CI
Reverts graphql/graphiql#3296
> Revert "update regression test matrix"

- .eslintrc.js
- cspell.json
another attempt to fix the eslint/prettier config mismatch on release
> use ignorePatterns instead

- .changeset/lovely-glasses-cross.md
- examples/monaco-graphql-react-vite/vite.config.ts
- packages/graphiql-toolkit/src/storage/custom.ts
- packages/graphiql-toolkit/src/storage/index.ts
- packages/monaco-graphql/test/monaco-editor.test.ts
Feat:
--
- Extend the flexibility to add custom storageNamespace, 
- Related discussion here:  
[0] https://github.com/graphql/graphiql/issues/2794  
[1] https://github.com/graphql/graphiql/pull/3021
> feat: add createLocalStorage to enable custom storage namespace

- .changeset/nice-cheetahs-deny.md
- packages/graphiql/src/cdn.ts
> export createLocalStorage in UMD bundle

- packages/graphiql/resources/index.html.ejs
- packages/graphiql/resources/renderExample.js
- packages/graphiql/test/beforeDevServer.js
Reverts graphql/graphiql#3403
oops, this approach breaks the netlify build
> Revert "add plugins to webpack dev bundle"

- packages/graphql-language-service-server/src/MessageProcessor.ts
- Added try-catch block around handleWatchedFilesChangedNotification handler to prevent server crash on schema update.
fixes #3429 
/claim tailcallhq/tailcall#579
> fix: LSP server crashing in case of error in schema

- .changeset/rotten-seahorses-fry.md
- .changeset/wet-toes-mate.md
> fix changeset pkg scope

- .changeset/silly-yaks-bathe.md
todo: add CI step to validate changesets, because it seems the changeset-bot isn't doing this?
> changeset typo

- package.json
- yarn.lock
> fix graphiql dev mode

- .github/workflows/main-test.yml
- .github/workflows/pr-graphql-compat-check.yml
- .github/workflows/pr.yml
- .github/workflows/release.yml
update `actions/checkout` from v3 to v4
update `actions/setup-node` from v3 to v4
update `actions/cache` from v3 to v4
update `codecov/codecov-action` from v3 to v4
update `actions/upload-artifact` from v3 to v4
https://github.com/graphql/graphiql/actions/runs/10294084390?pr=3552
> bump github actions

- functions/graphql.ts
- packages/graphiql/test/e2e-server.js
- packages/graphiql/test/execute.js
was broken after https://github.com/graphql/graphiql/pull/3682
> fix netlify graphql function

- .changeset/red-papayas-fly.md
- .changeset/wicked-seas-laugh.md
- packages/graphiql-react/src/ui/dropdown.css
- packages/graphiql/src/components/GraphiQL.tsx
- packages/graphiql/src/style.css
> [v4] fix scrollbar appearing in sidebar

- packages/graphiql/cypress/e2e/prettify.cy.ts
we missed it with @yaacovCR in https://github.com/graphql/graphiql/pull/3682
> fix skipped test of `prettify.cy.ts`

- packages/graphiql-plugin-explorer/example.html
- packages/graphiql-plugin-explorer/vite.config.mts
to have hot reloading while local development of plugin
> add vite replace html plugin for graphiql plugin explorer

- .github/workflows/main-test.yml
- .github/workflows/pr-graphql-compat-check.yml
- .github/workflows/pr.yml
- .github/workflows/release.yml
https://github.com/styfle/cancel-workflow-action
> add `styfle/cancel-workflow-action` to github actions to cancel previous runs

- .changeset/long-parents-grow.md
- packages/graphiql-react/src/editor/hooks.ts
fix https://github.com/graphql/graphiql/issues/3836
> fix query builder updated only first selected field in query editor due recent enabled react-compiler

- .changeset/late-moose-visit.md
- packages/graphiql/package.json
closes https://github.com/graphql/graphiql/issues/3839 https://github.com/graphql/graphiql/issues/3836#issuecomment-2548593792
> [graphiql] update `@graphiql/react` dependency range to `^0.28.1`

- working-group/agendas/2025/03-Mar/11-graphiql-wg-march-2025.md
> Add Dima to next meeting

- cspell.json
- package.json
- resources/custom-words.txt
- working-group/agendas/2025/04-Apr/08-graphiql-wg-april-2025.md
- working-group/agendas/2025/05-May/13-graphiql-wg-may-2025.md
- working-group/agendas/2025/06-Jun/10-graphiql-wg-june-2025.md
- yarn.lock
AI summaries are now enabled... It might take us a while to actually use them, but they're enabled. We should note this at the start of each meeting.
> Upgrade wgutils; note AI summary tools

- .changeset/wet-kiwis-shake.md
- package.json
- packages/vscode-graphql/package.json
this also disables ignoring failed extension releases!
> fix: vscode release

- package.json
- yarn.lock
fix https://github.com/graphql/graphiql/issues/3921#issuecomment-2850798682
> Remove `husky` and` lint-staged` as they slow down the development process

- .changeset/lazy-terms-hang.md
- packages/graphiql-react/src/utility/debounce.ts
fix https://github.com/graphql/graphiql/issues/3928
> fix: `ReferenceError: window is not defined` when using with SSR

- .github/workflows/pr.yml
- packages/cm6-graphql/package.json
- packages/codemirror-graphql/package.json
- packages/graphiql-plugin-code-exporter/package.json
- packages/graphiql-plugin-doc-explorer/package.json
- packages/graphiql-plugin-doc-explorer/src/components/__tests__/doc-explorer.spec.tsx
- packages/graphiql-plugin-doc-explorer/src/context.ts
- packages/graphiql-plugin-explorer/package.json
- packages/graphiql-plugin-history/package.json
- packages/graphiql-plugin-history/src/context.tsx
- packages/graphiql-react/package.json
- packages/graphiql-react/src/plugin.tsx
- packages/graphiql-react/src/schema.ts
- packages/graphiql-react/src/storage.tsx
- packages/graphiql-react/src/utility/create-bounded-use-store.ts
- packages/graphiql-react/src/utility/index.ts
- packages/graphiql-toolkit/package.json
- packages/graphiql/package.json
- packages/graphql-language-service-cli/package.json
- packages/graphql-language-service-server/package.json
- packages/graphql-language-service/package.json
- packages/monaco-graphql/package.json
- packages/vscode-graphql-execution/package.json
- packages/vscode-graphql-syntax/package.json
- packages/vscode-graphql/package.json
related https://github.com/graphql/graphiql/pull/3946#issuecomment-2885291149
> add types check github action

- .changeset/few-lamps-rest.md
- packages/codemirror-graphql/src/utils/SchemaReference.ts
- packages/graphql-language-service-server/src/__tests__/MessageProcessor.test.ts
- packages/graphql-language-service/src/interface/getDiagnostics.ts
- packages/graphql-language-service/src/interface/getHoverInformation.ts
- packages/graphql-language-service/src/utils/getVariablesJSONSchema.ts
ref https://discord.com/channels/625400653321076807/863691102639620096/1375863840851624067
> feat(graphql-language-service) set `additionalProperties: false` to report unused variables

- .changeset/twenty-turkeys-compare.md
- packages/monaco-graphql/package.json
- packages/monaco-graphql/src/GraphQLWorker.ts
- packages/monaco-graphql/src/languageFeatures.ts
- packages/monaco-graphql/src/utils.ts
ref https://discord.com/channels/625400653321076807/863691102639620096/1375808628895911956
> fixed `monaco-graphql` severity, it was hardcoded to `5` which is not valid value of monaco severity

- .changeset/poor-ads-argue.md
- packages/graphiql-react/src/components/button/index.css
- packages/graphiql-react/src/components/execute-button/index.css
- packages/graphiql-react/src/components/execute-button/index.tsx
closes https://github.com/graphql/graphiql/issues/4036
> graphiql 5: fix execute button becomes unstyled if there are several queries present

- docs/migration/graphiql-5.0.0.md
- examples/graphiql-vite/package.json
- examples/graphiql-vite/src/App.jsx
- examples/graphiql-vite/vite.config.mjs
- yarn.lock
closes https://github.com/graphql/graphiql/issues/4038
> fix graphiql 5 with vite example

- .changeset/smart-zoos-doubt.md
- packages/graphiql/src/GraphiQL.tsx
- packages/graphiql/src/index.ts
closes https://github.com/graphql/graphiql/issues/4057
> export `GraphiQLInterface`

- README.md
- packages/graphiql/README.md
(to avoid redirect)
closes https://github.com/graphql/graphiql/issues/4034#issuecomment-3056993179
> use new swapi urls

- .changeset/early-deers-carry.md
- packages/graphiql-react/src/index.ts
- packages/graphiql-react/src/utility/hooks.ts
- packages/graphiql/setup-files.ts
- packages/graphiql/src/GraphiQL.spec.tsx
- packages/graphiql/vitest.config.mts
closes https://github.com/graphql/graphiql/issues/4053#issuecomment-3077195398
> fix broken `useOperationsEditorState` and `useEditorState` hook and add unit tests

- .changeset/twenty-walls-share.md
- packages/graphiql-react/src/components/provider.tsx
- packages/graphiql-react/src/constants.ts
- packages/graphiql-react/src/deprecated.ts
- packages/graphiql-react/src/stores/editor.ts
- packages/graphiql-react/src/stores/theme.ts
- packages/graphiql/README.md
- packages/graphiql/setup-files.ts
- packages/graphiql/src/GraphiQL.spec.tsx
- packages/graphiql/vitest.config.mts
fix popup from blogpost https://graphql.org/blog/2025-07-17-graphiql-5/
> graphiql 5: fix color in the F1 popup should be graphiql primary color

- .changeset/shaggy-panthers-grin.md
- packages/graphiql-react/README.md
- packages/graphiql-react/src/style/editor.css
- packages/graphiql/src/GraphiQL.tsx
- packages/graphiql/src/ui/sidebar.tsx
feat: add loader for initial loading of operation editor
feat: add short cut `Cmd/Ctrl + ,` for opening GraphiQL settings dialog
> fix: adjust command palette `width`, `border` and remove `box-shadow`
